import Link from "next/link";
import { CheckCircle2 } from "lucide-react";

import { getToolMetadata } from "@/lib/seo";
import Mp4ParaMovClient from "./mp4-para-mov-client";

export const metadata = getToolMetadata("mp4-para-mov");

const faq = [
  ["Como converter MP4 para MOV?", "Selecione um MP4 válido, confira os dados detectados, escolha qualidade, resolução e FPS, clique em Converter para MOV e baixe o arquivo concluído."],
  ["MP4 e MOV são codecs?", "Não. MP4 e MOV são containers que podem reunir vídeo, áudio, legendas e metadados. H.264, HEVC e AAC são exemplos de codecs."],
  ["A conversão reduz a qualidade?", "Quando o remux é possível, os streams são copiados sem recompressão e a qualidade é preservada. Se houver recodificação, pode existir alguma alteração visual."],
  ["O vídeo manterá a mesma resolução?", "Sim, por padrão. Uma resolução menor só é aplicada quando você a escolhe; a ferramenta não aumenta vídeos menores."],
  ["O áudio será preservado?", "Sim. A faixa de áudio é mantida. Codecs compatíveis são copiados e os demais são convertidos para AAC."],
  ["MOV fica maior que MP4?", "Não necessariamente. O tamanho depende principalmente dos codecs, bitrate, resolução, FPS, duração e áudio, não apenas do container."],
  ["MOV é melhor para edição?", "Pode ser mais adequado em programas e fluxos que priorizam MOV, mas nenhum container é universalmente melhor. A escolha depende do software e dos codecs."],
  ["Posso converter vídeo 4K?", "Sim, desde que a maior dimensão não ultrapasse 3840 pixels e o arquivo respeite os demais limites. O processamento 4K pode demorar mais."],
  ["A duração permanece a mesma?", "Sim. A conversão preserva a duração; pequenas diferenças de arredondamento de timestamps podem ocorrer entre containers."],
  ["O FPS será alterado?", "O padrão mantém o FPS original. Ao escolher 60, 30 ou 24, a ferramenta só reduz a taxa quando o original é maior; nunca aumenta automaticamente."],
  ["O que é conversão sem recodificação?", "É o remux: vídeo e áudio compatíveis são copiados para um container MOV novo, sem recomprimir os streams."],
  ["Por que alguns arquivos precisam ser recodificados?", "Isso acontece quando um codec interno não é adequado ao MOV ou quando você solicita outra qualidade, resolução ou FPS."],
  ["O MOV funciona no Windows?", "Sim, desde que o programa instalado suporte o container MOV e os codecs usados no arquivo. Players e editores modernos costumam oferecer suporte."],
  ["Posso usar pelo navegador?", "Sim. A interface funciona em navegadores modernos de desktop e celular, mas a reprodução do MOV pronto depende do suporte do navegador."],
  ["Qual é o limite de tamanho?", "A ferramenta aceita um arquivo por vez com até 200 MB, duração máxima de 2 horas e resolução de entrada de até 4K."],
] as const;

const schema = { "@context": "https://schema.org", "@graph": [
  { "@type": "SoftwareApplication", name: "MP4 para MOV", applicationCategory: "MultimediaApplication", operatingSystem: "Qualquer sistema com navegador moderno", url: "https://www.kivai.com.br/ferramentas/mp4-para-mov", description: "Converta vídeos MP4 para MOV preservando resolução, áudio e qualidade sempre que possível.", offers: { "@type": "Offer", price: "0", priceCurrency: "BRL" } },
  { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Início", item: "https://www.kivai.com.br" }, { "@type": "ListItem", position: 2, name: "Vídeos", item: "https://www.kivai.com.br/ferramentas/videos" }, { "@type": "ListItem", position: 3, name: "MP4 para MOV", item: "https://www.kivai.com.br/ferramentas/mp4-para-mov" }] },
  { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
] };

export default function Mp4ParaMovPage() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><Mp4ParaMovClient /><section className="border-t border-border bg-muted/10 py-12 sm:py-16"><div className="mx-auto w-full max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8">
    <div className="grid gap-6 lg:grid-cols-2"><Info title="O que é MP4?"><p>MP4 é um container amplamente usado para armazenar vídeo, áudio, legendas e metadados em um único arquivo. Ele costuma reunir vídeo H.264 ou HEVC e áudio AAC, mas a extensão sozinha não revela quais codecs estão presentes.</p></Info><Info title="O que é MOV?"><p>MOV também é um container. Ele está associado ao ecossistema QuickTime e Apple, mas é aceito por diversos programas profissionais de edição, reprodução e produção audiovisual em diferentes sistemas.</p></Info></div>
    <Info title="Por que converter MP4 para MOV?"><p>Alguns editores, dispositivos e processos de entrega solicitam MOV ou trabalham melhor com esse container. A conversão pode facilitar a importação em um projeto, atender ao formato pedido por um cliente, preparar material para arquivamento ou integrar um vídeo a um fluxo audiovisual já padronizado.</p><ul className="mt-4 grid gap-2 sm:grid-cols-2"><li className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />Edição em programas que priorizam MOV.</li><li className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />Compatibilidade com fluxos de produção.</li><li className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />Entrega no formato solicitado pelo cliente.</li><li className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />Importação em dispositivos e sistemas específicos.</li></ul></Info>
    <div className="grid gap-6 lg:grid-cols-2"><Info title="MP4 para MOV perde qualidade?"><p>Se vídeo e áudio forem compatíveis com MOV e as opções permanecerem em Automática, Manter original e Manter original, a ferramenta usa remux. Os streams são copiados para o novo container sem recompressão, preservando a qualidade visual e sonora.</p><p className="mt-3">Quando um codec é incompatível ou você solicita outra qualidade, resolução ou FPS, o vídeo é recodificado em H.264. Nesse caso pode haver alguma alteração, embora o perfil seja escolhido para manter boa qualidade.</p></Info><Info title="MOV é melhor que MP4?"><p>Nenhum dos dois é sempre melhor. MP4 é muito difundido para web, compartilhamento e reprodução. MOV pode se encaixar melhor em determinados editores e ecossistemas. A decisão correta considera software, codecs internos, compatibilidade e o destino do material.</p></Info></div>
    <div className="grid gap-6 lg:grid-cols-2"><Info title="MOV fica maior que MP4?"><p>Não necessariamente. No remux, a diferença tende a ser pequena porque os streams continuam iguais. Em uma recodificação, o tamanho varia conforme complexidade das cenas, codec, qualidade, bitrate, resolução, FPS, duração e áudio.</p></Info><Info title="Como a ferramenta decide a estratégia?"><p>O servidor analisa o container e os codecs com FFmpeg. H.264, HEVC, MPEG-4, ProRes ou MJPEG com áudio compatível podem usar remux quando nenhuma transformação foi pedida. Nos demais casos, o vídeo é convertido para H.264 e o áudio incompatível para AAC.</p></Info></div>
    <Info title="Exemplo prático"><p>Imagine que você recebeu um vídeo MP4, mas o programa utilizado no seu fluxo de edição exige ou funciona melhor com MOV. Selecione o arquivo, confira codecs e dimensões, mantenha a qualidade automática e converta. Se os streams forem compatíveis, o resultado será criado rapidamente sem recodificação.</p><p className="mt-3">Outro exemplo é um vídeo enviado por um cliente em MP4 que precisa entrar em uma produção audiovisual padronizada em MOV. A ferramenta prepara uma cópia compatível sem alterar o original.</p><ol className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Selecione o arquivo MP4.", "Confira duração, resolução e codecs.", "Mantenha ou ajuste qualidade, resolução e FPS.", "Clique em Converter para MOV.", "Aguarde o processamento real.", "Baixe o arquivo MOV válido."].map((step, index) => <li key={step} className="rounded-lg border border-border p-4 text-sm"><span className="mb-3 flex size-7 items-center justify-center rounded-full bg-primary/10 font-semibold text-primary">{index + 1}</span>{step}</li>)}</ol></Info>
    <Info title="Recursos e limites"><ul className="grid gap-2 sm:grid-cols-2">{["Entrada oficial: MP4", "Saída válida em container MOV", "Um arquivo por vez, até 200 MB", "Duração máxima de 2 horas", "Resolução máxima de entrada 4K", "Resolução e FPS nunca aumentados automaticamente", "Remux preferencial sem recompressão", "Fallback em H.264 e AAC quando necessário", "Áudio preservado por padrão", "Cancelamento durante a conversão", "Nome de saída preservado e sanitizado", "Temporários removidos após o processamento"].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />{item}</li>)}</ul></Info>
    <article className="rounded-xl border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Perguntas frequentes</h2><div className="mt-5 space-y-3">{faq.map(([question, answer]) => <details key={question} className="rounded-lg border border-border p-4"><summary className="cursor-pointer font-medium">{question}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{answer}</p></details>)}</div></article>
    <nav aria-label="Ferramentas relacionadas" className="rounded-xl border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Ferramentas relacionadas</h2><div className="mt-4 flex flex-wrap gap-3"><Related href="/ferramentas/mp4-para-avi">MP4 para AVI</Related><Related href="/ferramentas/mov-para-mp4">MOV para MP4</Related><Related href="/ferramentas/hevc-para-mp4">HEVC para MP4</Related><Related href="/ferramentas/compressor-de-videos">Compressor de Vídeos</Related><Related href="/ferramentas/video-para-audio">Vídeo para Áudio</Related><Related href="/ferramentas/redimensionar-video">Redimensionar Vídeo</Related><Related href="/ferramentas/ajustar-velocidade-video">Ajustar Velocidade</Related><Related href="/ferramentas/alterar-volume-video">Alterar Volume</Related><Related href="/ferramentas/remover-audio-video">Remover Áudio</Related><Related href="/ferramentas/dividir-video">Dividir Vídeo</Related><Related href="/ferramentas/capturar-frame-video">Capturar Frame</Related></div></nav>
  </div></section></>;
}

function Info({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">{title}</h2><div className="mt-4 leading-7 text-muted-foreground">{children}</div></article>; }
function Related({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="rounded-lg border border-border px-4 py-2 text-sm font-medium transition-colors hover:border-primary hover:text-primary">{children}</Link>; }
