"use client";
import { FormEvent, useRef, useState } from "react";
import { Check, Copy, Loader2, RotateCcw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ToolPageShell } from "@/components/tools/tool-page-shell";

type NcmData = { codigo?: string; descricao?: string; data_inicio?: string; data_fim?: string; tipo_ato?: string; numero_ato?: string; ano_ato?: string };
const normalize=(v:string)=>v.replace(/\D/g,"").slice(0,8);
const fmt=(v?:string)=>{const d=normalize(v??""); return d.length===8?`${d.slice(0,4)}.${d.slice(4,6)}.${d.slice(6,8)}`:v||"Não informado"};
const date=(v?:string)=>{if(!v)return "Não informado";const parts=v.split("-");return parts.length===3?`${parts[2]}/${parts[1]}/${parts[0]}`:v};
const display=(v?:string|null)=>v||"Não informado";

export default function ConsultaDeNcmClient(){
 const [code,setCode]=useState(""),[result,setResult]=useState<NcmData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[copied,setCopied]=useState(false);
 const ref=useRef<HTMLDivElement>(null);
 async function submit(e:FormEvent){e.preventDefault();setError("");setResult(null);setCopied(false);const n=normalize(code);if(n.length!==8){setError("Informe um código NCM com 8 dígitos.");return}setLoading(true);try{const r=await fetch("/api/consulta-ncm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:n})});const p=await r.json().catch(()=>null) as NcmData|{error?:string}|null;if(!r.ok){setError(p&&"error"in p&&p.error?p.error:"Não foi possível realizar a consulta.");return}setResult(p as NcmData);setTimeout(()=>ref.current?.scrollIntoView({behavior:"smooth",block:"start"}),0)}catch{setError("Não foi possível conectar ao serviço de consulta. Tente novamente.")}finally{setLoading(false)}}
 async function copy(){if(!result)return;try{await navigator.clipboard.writeText([`NCM: ${fmt(result.codigo)}`,`Descrição: ${display(result.descricao)}`,`Início da vigência: ${date(result.data_inicio)}`,`Fim da vigência: ${date(result.data_fim)}`,`Tipo do ato: ${display(result.tipo_ato)}`,`Número do ato: ${display(result.numero_ato)}`,`Ano do ato: ${display(result.ano_ato)}`].join("\n"));setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setError("Não foi possível copiar os dados.")}}
 function reset(){setCode("");setResult(null);setError("");setCopied(false)}
 return <ToolPageShell title="Consulta de NCM" description="Consulte códigos NCM, descrição, vigência e informações do ato legal associado ao produto." categoryName="Empresarial" categoryHref="/ferramentas" processingMode="server" privacyMessage="O código NCM informado é enviado à BrasilAPI para consulta. O Kivai não salva o resultado da consulta."><Card><CardHeader><CardTitle>Consultar NCM</CardTitle><CardDescription>Digite o código NCM com 8 dígitos, com ou sem pontos.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="flex flex-col gap-4 sm:flex-row"><div className="min-w-0 flex-1"><label htmlFor="ncm" className="text-sm font-medium">Código NCM</label><input id="ncm" value={code} onChange={e=>{setCode(normalize(e.target.value));setResult(null);setError("")}} inputMode="numeric" autoComplete="off" maxLength={8} placeholder="33051000" className="mt-2 h-11 w-full border border-border bg-background px-3 text-sm outline-none focus:border-primary"/><p className="mt-2 text-xs leading-5 text-muted-foreground">Exemplo: 3305.10.00. A consulta utiliza os dados disponibilizados pela BrasilAPI.</p></div><div className="flex items-end gap-2 sm:shrink-0"><Button type="submit" size="lg" disabled={loading||normalize(code).length!==8}>{loading?<Loader2 className="size-4 animate-spin"/>:<Search className="size-4"/>}{loading?"Consultando...":"Consultar NCM"}</Button><Button type="button" variant="outline" size="lg" onClick={reset} disabled={loading}><RotateCcw className="size-4"/>Limpar</Button></div></form>{error&&<div role="alert" className="mt-5 border border-destructive/30 bg-destructive/5 p-4 text-sm leading-6 text-destructive">{error}</div>}</CardContent></Card>{result&&<div ref={ref} className="mt-6"><Card><CardHeader><CardDescription>NCM consultado</CardDescription><CardTitle className="text-2xl sm:text-3xl">{fmt(result.codigo)}</CardTitle><p className="mt-2 text-sm leading-6 text-muted-foreground">{display(result.descricao)}</p></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2">{[["Código NCM",fmt(result.codigo)],["Descrição",display(result.descricao)],["Início da vigência",date(result.data_inicio)],["Fim da vigência",date(result.data_fim)],["Tipo do ato",display(result.tipo_ato)],["Número do ato",display(result.numero_ato)],["Ano do ato",display(result.ano_ato)]].map(([l,v])=><div key={l} className="border border-border bg-muted/10 p-4"><dt className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{l}</dt><dd className="mt-1 break-words text-sm font-medium">{v}</dd></div>)}</dl><div className="mt-5"><Button type="button" variant="outline" onClick={copy}>{copied?<Check className="size-4"/>:<Copy className="size-4"/>}{copied?"Dados copiados":"Copiar dados"}</Button></div></CardContent></Card></div>}</ToolPageShell>
}