import { test, expect } from "@playwright/test";
import { createHmac } from "node:crypto";
test("Admin activation refreshes free customer; saved calendar survives reload; Agency grants client organization; CMS matches public copy", async ({ page, context, request }) => {
 const errors: string[]=[]; page.on("pageerror",e=>errors.push(e.message));
 await context.addInitScript(()=>localStorage.setItem("kivai_user_session",JSON.stringify({access_token:"fixture-user"})));
 const payload=Buffer.from(JSON.stringify({email:"admin@example.invalid",exp:Math.floor(Date.now()/1000)+3600})).toString("base64url");
 const signature=createHmac("sha256","fixture-secret-at-least-32-characters-long").update(payload).digest("base64url");
 await context.addCookies([{name:"kivai_admin_session",value:`${payload}.${signature}`,url:"http://127.0.0.1:3103"}]);
 await page.goto('/conta');await expect(page.getByText('Plano Grátis',{exact:true})).toBeVisible();
 const admin=await context.newPage();await admin.goto('/admin/assinaturas');
 await admin.getByRole('button',{name:'Confirmar pagamento e ativar plano'}).click();
 await expect(admin.getByText('Plano ativado',{exact:true})).toBeVisible();
 await page.bringToFront();await expect(page.getByText('Plano Pro',{exact:true})).toBeVisible({timeout:25000});
 await page.goto('/ferramentas/calendario-editorial-redes-sociais');
 await page.getByRole('button',{name:'Nova publicação',exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.getByLabel('Título ou tema',{exact:true}).fill('Post salvo na nuvem');
 await dialog.getByLabel(/^Rede social/).selectOption('Instagram');await dialog.getByLabel(/^Formato/).selectOption('Post');await dialog.getByLabel(/^Objetivo/).selectOption('Engajamento');
 await dialog.getByRole('button',{name:'Adicionar publicação',exact:true}).click();
 await page.getByLabel('Nome do projeto',{exact:true}).fill('Calendário da marca');await page.getByRole('button',{name:'Salvar na conta',exact:true}).click();
 await expect(page.getByText('Projeto salvo na sua conta.',{exact:false})).toBeVisible();
 await page.evaluate(()=>localStorage.removeItem('kivai:calendario-editorial:v1'));
 await page.reload();await expect(page.getByRole('heading',{name:'Calendário da marca',exact:true})).toBeVisible();
 await page.getByRole('region',{name:'Projetos salvos'}).getByRole('button',{name:'Abrir',exact:true}).click();await page.getByRole('button',{name:'Abrir projeto',exact:true}).click();await expect(page.getByText('Post salvo na nuvem').first()).toBeVisible();
 await page.screenshot({path:'.work/plan-calendar.png',fullPage:true});
 await admin.goto('/admin/usuarios');await admin.getByText('Cliente Teste',{exact:true}).first().click();
 await admin.locator('select[name="planCode"]').selectOption('agency');await admin.locator('input[name="accessUntil"]').fill(new Date(Date.now()+30*86400000).toISOString().slice(0,10));await admin.locator('input[name="changeAccess"]').check();await admin.getByRole('button',{name:'Salvar alterações',exact:true}).click();
 await page.goto('/conta/pro');await expect(page.getByText('Área Agency',{exact:true})).toBeVisible();
 await page.goto('/ferramentas/planejador-de-conteudo-social-media');await page.getByLabel('Nome do projeto',{exact:true}).fill('Briefing cliente');await page.getByLabel('Cliente (opcional)',{exact:false}).fill('Cliente A');await page.getByRole('button',{name:'Salvar na conta',exact:true}).click();await expect(page.getByText('Projeto salvo na sua conta.',{exact:false})).toBeVisible();
 await page.goto('/planos');await expect(page.getByRole('heading',{name:'Ferramentas para analisar, planejar e organizar seu trabalho'})).toBeVisible();await expect(page.getByText('Até 200 calendários e briefings salvos na conta',{exact:true})).toBeVisible();
 await page.screenshot({path:'.work/plan-comparison.png',fullPage:true});
 await page.goto('/servicos/planos-kivai');await expect(page.getByRole('heading',{name:'Assinaturas Pro e Agency',exact:true})).toBeVisible();
 const cms=await context.request.get('/api/admin/site-content');expect(cms.ok()).toBeTruthy();const items=await cms.json();const plan=items.find((x:{path:string})=>x.path==='/planos');expect(plan).toBeTruthy();
 await admin.goto(`/admin/site/conteudos/${plan.id}`);await expect(admin.locator('input').filter({visible:true}).first()).toBeVisible();
 const services=await context.request.get('/api/admin/site-services');expect((await services.json()).some((item:{path:string})=>item.path==='/servicos/planos-kivai')).toBeTruthy();
 await page.setViewportSize({width:390,height:844});await page.goto('/conta');await expect(page.getByText('Plano Agency',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Calendário da marca',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Briefing cliente',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'.work/plan-agency-mobile.png',fullPage:true});
 const unauthorized=await request.get('/api/account/projects');expect(unauthorized.status()).toBe(401);
 expect(errors).toEqual([]);
});
