"use client";

import { openFilePicker } from "@/lib/browser/file-picker";
import { ChangeEvent, useRef, useState } from "react";
import { Download, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ImageToolPageShell } from "@/components/tools/image-tool-page-shell";
import { canvasBlob, downloadBlob, IMAGE_TYPES, loadImage } from "@/lib/image-tools/canvas";

export function CropImageClient() {
  const input = useRef<HTMLInputElement>(null); const [image, setImage] = useState<HTMLImageElement | null>(null); const [name, setName] = useState("imagem"); const [x, setX] = useState(0); const [y, setY] = useState(0); const [width, setWidth] = useState(0); const [height, setHeight] = useState(0); const [result, setResult] = useState<string | null>(null); const [error, setError] = useState("");
  const select = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!IMAGE_TYPES.includes(file.type)) { setError("Use PNG, JPG ou WebP."); return; } const loaded = await loadImage(file); setImage(loaded); setName(file.name.replace(/\.[^/.]+$/, "")); setX(0); setY(0); setWidth(loaded.naturalWidth); setHeight(loaded.naturalHeight); setResult(null); setError(""); };
  const crop = async () => { if (!image) return; const safeX = Math.max(0, Math.min(x, image.naturalWidth - 1)); const safeY = Math.max(0, Math.min(y, image.naturalHeight - 1)); const safeW = Math.max(1, Math.min(width, image.naturalWidth - safeX)); const safeH = Math.max(1, Math.min(height, image.naturalHeight - safeY)); const canvas = document.createElement("canvas"); canvas.width = safeW; canvas.height = safeH; canvas.getContext("2d")?.drawImage(image, safeX, safeY, safeW, safeH, 0, 0, safeW, safeH); const blob = await canvasBlob(canvas); if (result) URL.revokeObjectURL(result); setResult(URL.createObjectURL(blob)); };
  const controls: Array<{ label: string; value: number; setValue: (value: number) => void }> = [{ label: "X", value: x, setValue: setX }, { label: "Y", value: y, setValue: setY }, { label: "Largura", value: width, setValue: setWidth }, { label: "Altura", value: height, setValue: setHeight }];
  return <ImageToolPageShell title="Recortar Imagem" description="Defina a área exata da imagem que deseja manter, com processamento local."><Card className="mx-auto max-w-5xl"><CardHeader><CardTitle>Área de recorte</CardTitle><CardDescription>Envie uma imagem e informe as coordenadas e o tamanho do corte.</CardDescription></CardHeader><CardContent><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={select} />{!image ? <div className="flex min-h-80 flex-col items-center justify-center border border-dashed border-border bg-muted/20"><Upload className="size-6 text-primary"/><Button className="mt-5" onClick={() => openFilePicker(input.current)}>Selecionar imagem</Button></div> : <><div className="grid gap-5 lg:grid-cols-2"><div className="border border-border bg-background p-4"><img src={image.src} alt="Imagem original" className="max-h-96 w-full object-contain"/></div><div className="border border-border bg-muted/20 p-4"><p className="text-sm font-medium">Área de recorte</p><div className="mt-4 grid grid-cols-2 gap-3">{controls.map((control) => <label key={control.label} className="text-xs font-medium">{control.label}<input type="number" min="0" value={control.value} onChange={(event) => control.setValue(Number(event.target.value))} className="mt-1 h-10 w-full border border-input bg-background px-3 text-sm"/></label>)}</div><Button className="mt-5" onClick={crop}>Recortar imagem</Button><Button className="mt-5 ml-3" variant="outline" onClick={() => openFilePicker(input.current)}>Trocar imagem</Button></div></div>{result && <div className="mt-6 border border-border bg-background p-4"><img src={result} alt="Imagem recortada" className="mx-auto max-h-96 max-w-full object-contain"/><Button className="mt-4" onClick={async () => { const response = await fetch(result); downloadBlob(await response.blob(), `${name}-recortada.png`); }}><Download/>Baixar PNG</Button></div>}</>}{error && <p className="mt-4 text-sm text-destructive">{error}</p>}</CardContent></Card></ImageToolPageShell>;
}
