"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Download, LoaderCircle, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { createFaviconZip, generateFaviconAssets, type FaviconAsset } from "@/lib/favicon/engine";

const FORMATOS = ["image/png", "image/jpeg", "image/webp"];
type Props = { title: string; description: string; names: Record<number, string>; showAll: boolean };

export function FaviconGeneratorClient({ title, description, names, showAll }: Props) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [assets, setAssets] = useState<FaviconAsset[]>([]);
  const [ico, setIco] = useState<{ blob: Blob; url: string } | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); assets.forEach((asset) => URL.revokeObjectURL(asset.url)); if (ico) URL.revokeObjectURL(ico.url); }, [preview, assets, ico]);
  const download = (url: string, name: string) => { const link = document.createElement("a"); link.href = url; link.download = name; link.click(); };
  const select = (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0]; if (!selected) return; if (!FORMATOS.includes(selected.type)) { setError("Use uma imagem PNG, JPG ou WebP."); return; } assets.forEach((asset) => URL.revokeObjectURL(asset.url)); if (ico) URL.revokeObjectURL(ico.url); if (preview) URL.revokeObjectURL(preview); setFile(selected); setPreview(URL.createObjectURL(selected)); setAssets([]); setIco(null); setError(""); };
  const generate = async () => { if (!file) return; setLoading(true); setError(""); try { const result = await generateFaviconAssets(file, names); setAssets(result.assets); setIco({ blob: result.icoBlob, url: result.icoUrl }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível gerar os favicons."); } finally { setLoading(false); } };
  const downloadZip = async () => { if (!ico) return; const zip = await createFaviconZip(assets, ico.blob); download(URL.createObjectURL(zip), "favicons.zip"); };
  return <section className="min-h-screen bg-background px-4 pb-16 pt-24 text-foreground"><div className="mx-auto max-w-5xl"><p className="text-sm font-medium uppercase tracking-wider text-primary">Ferramenta de imagem</p><h1 className="mt-3 font-heading text-3xl font-semibold sm:text-5xl">{title}</h1><p className="mt-4 max-w-2xl text-muted-foreground">{description} Todo o processamento acontece no seu navegador.</p><div className="mt-10 border border-border bg-card p-5 sm:p-8"><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={select} />{!preview ? <div className="flex min-h-64 flex-col items-center justify-center border border-dashed border-border p-6 text-center"><Upload className="size-7 text-primary"/><h2 className="mt-4 text-lg font-medium">Envie sua imagem</h2><p className="mt-2 text-sm text-muted-foreground">PNG, JPG ou WebP</p><Button className="mt-5" onClick={() => inputRef.current?.click()}>Selecionar imagem</Button></div> : <><div className="flex flex-col gap-5 sm:flex-row"><div className="flex size-40 shrink-0 items-center justify-center border border-border bg-muted/20 p-3"><img src={preview} alt="Imagem selecionada" className="max-h-full max-w-full object-contain"/></div><div><p className="font-medium">{file?.name}</p><p className="mt-1 text-sm text-muted-foreground">{file && (file.size / 1024 / 1024).toFixed(2)} MB</p><div className="mt-4 flex gap-3"><Button onClick={generate} disabled={loading}>{loading ? <><LoaderCircle className="animate-spin"/>Gerando...</> : "Gerar favicons"}</Button><Button variant="outline" onClick={() => inputRef.current?.click()}>Trocar imagem</Button></div></div></div>{ico && <div className="mt-8 border-t border-border pt-6"><div className="flex flex-wrap gap-3"><Button onClick={() => download(ico.url, "favicon.ico")}><Download/>Baixar favicon.ico</Button><Button variant="outline" onClick={downloadZip}><Download/>Baixar ZIP</Button></div><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-7">{assets.map((asset) => <div key={asset.name} className="border border-border bg-muted/20 p-3 text-center"><div className="flex h-24 items-center justify-center bg-[linear-gradient(45deg,#222_25%,transparent_25%),linear-gradient(-45deg,#222_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#222_75%),linear-gradient(-45deg,transparent_75%,#222_75%)] bg-[length:16px_16px] p-2"><img src={asset.url} alt={`Preview ${asset.size} por ${asset.size}`} className="max-h-full max-w-full"/></div><p className="mt-2 text-xs font-medium">{asset.size}×{asset.size}</p><Button className="mt-2 w-full" size="xs" variant="outline" onClick={() => download(asset.url, asset.name)}>Baixar</Button></div>)}</div>{showAll && <p className="mt-5 text-sm text-muted-foreground">Inclui ícones para navegador, Apple Touch e Android Chrome.</p>}</div>}</>}{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}</div></div></section>;
}
