"use client";
import { useState } from "react";
import Link from "next/link";
import { Copy, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export function InstagramTextClient() {
  const [text, setText] = useState(""); const [copied, setCopied] = useState(false);
  const hashtags = text.match(/#[\p{L}\p{N}_]+/gu) ?? [];
  const copy = async () => { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto w-full max-w-6xl px-4 pb-12 pt-24 sm:px-6 lg:px-8"><div className="mb-8"><Link href="/ferramentas/social-media" className="text-sm text-muted-foreground hover:text-primary">← Voltar para ferramentas de Social Media</Link></div><header className="mb-10 max-w-3xl"><p className="text-sm font-medium uppercase tracking-wider text-primary">Social Media</p><h1 className="mt-3 font-heading text-3xl font-semibold tracking-tight sm:text-4xl lg:text-5xl">Contador de Caracteres Instagram</h1><p className="mt-4 text-base leading-7 text-muted-foreground sm:text-lg">Conte os caracteres da sua legenda antes de publicar no Instagram.</p></header><Card className="mx-auto max-w-4xl overflow-hidden"><CardHeader><CardTitle>Área de processamento</CardTitle><CardDescription>Digite ou cole seu texto. Nada é enviado para servidores.</CardDescription></CardHeader><CardContent className="space-y-5"><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Digite sua legenda aqui…" className="min-h-56 w-full rounded-lg border border-input bg-background p-4 text-sm"/><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-border p-4"><p className="text-xs uppercase text-muted-foreground">Caracteres</p><p className="mt-2 text-xl font-semibold">{text.length}</p></div><div className="rounded-lg border border-border p-4"><p className="text-xs uppercase text-muted-foreground">Palavras</p><p className="mt-2 text-xl font-semibold">{text.trim() ? text.trim().split(/\s+/).length : 0}</p></div><div className="rounded-lg border border-border p-4"><p className="text-xs uppercase text-muted-foreground">Hashtags</p><p className="mt-2 text-xl font-semibold">{hashtags.length}</p></div></div><div className="flex flex-wrap gap-3"><Button onClick={copy} disabled={!text}><Copy/>{copied ? "Copiado" : "Copiar resultado"}</Button><Button variant="outline" onClick={() => setText("")}><RotateCcw/>Limpar</Button></div></CardContent></Card></div></main>;
}
