"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Download, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ImageToolPageShell } from "@/components/tools/image-tool-page-shell";
import { mockupTemplates, type MockupTemplate } from "@/lib/mockups/templates";

const accepted = ["image/png", "image/jpeg", "image/webp"];
const W = 1600; const H = 1000;

export function MockupGeneratorClient() {
  const input = useRef<HTMLInputElement>(null); const canvas = useRef<HTMLCanvasElement>(null);
  const [source, setSource] = useState<HTMLImageElement | null>(null); const [template, setTemplate] = useState(mockupTemplates[0]); const [scale, setScale] = useState(1); const [x, setX] = useState(0); const [y, setY] = useState(0); const [error, setError] = useState("");
  const load = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!accepted.includes(file.type)) { setError("Use PNG, JPG ou WebP."); return; } const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => { setSource(image); setError(""); }; image.src = url; };
  useEffect(() => { if (canvas.current) draw(canvas.current, template, source, scale, x, y); }, [template, source, scale, x, y]);
  const download = () => { const link = document.createElement("a"); link.href = canvas.current?.toDataURL("image/png") ?? ""; link.download = `${template.id}-mockup.png`; document.body.appendChild(link); link.click(); link.remove(); };

  return <ImageToolPageShell title="Gerador de Mockups" description="Posicione sua arte em cenários prontos e exporte o resultado em alta qualidade, diretamente no navegador.">
    <Card className="mx-auto max-w-6xl"><CardHeader><CardTitle>Área de edição</CardTitle><CardDescription>Escolha um modelo, envie sua imagem e ajuste a composição.</CardDescription></CardHeader><CardContent><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={load} />
      <div className="grid gap-6 lg:grid-cols-[300px_1fr]"><aside className="border border-border bg-muted/20 p-4"><Button className="w-full" onClick={() => input.current?.click()}><Upload />{source ? "Trocar imagem" : "Enviar imagem"}</Button><h2 className="mt-6 text-sm font-medium">Modelo</h2><div className="mt-3 grid grid-cols-2 gap-2">{mockupTemplates.map((item) => <button key={item.id} onClick={() => setTemplate(item)} className={`border p-2 text-left text-xs transition-colors ${item.id === template.id ? "border-primary bg-primary/10 text-primary" : "border-border bg-background hover:bg-muted"}`}>{item.name}</button>)}</div>{source && <><label className="mt-6 block text-sm font-medium">Escala: {scale.toFixed(1)}×</label><input className="mt-2 w-full" type="range" min="0.4" max="2" step="0.05" value={scale} onChange={(event) => setScale(Number(event.target.value))} /><label className="mt-4 block text-sm font-medium">Mover horizontalmente</label><input className="mt-2 w-full" type="range" min="-100" max="100" value={x} onChange={(event) => setX(Number(event.target.value))} /><label className="mt-4 block text-sm font-medium">Mover verticalmente</label><input className="mt-2 w-full" type="range" min="-100" max="100" value={y} onChange={(event) => setY(Number(event.target.value))} /><Button className="mt-6 w-full" onClick={download}><Download />Baixar PNG</Button></>}</aside><div><p className="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">Prévia do mockup</p><div className="border border-border bg-background p-3"><canvas ref={canvas} width={W} height={H} className="w-full bg-muted/20" aria-label="Prévia do mockup" /></div></div></div>
      {error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}
    </CardContent></Card>
  </ImageToolPageShell>;
}

function draw(canvas: HTMLCanvasElement, template: MockupTemplate, image: HTMLImageElement | null, scale: number, offsetX: number, offsetY: number) { const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.fillStyle = "#0d1017"; ctx.fillRect(0, 0, W, H); const s = template.screen; drawFrame(ctx, template); ctx.save(); ctx.beginPath(); ctx.rect(s.x, s.y, s.width, s.height); ctx.clip(); if (image) { const ratio = Math.max(s.width / image.naturalWidth, s.height / image.naturalHeight) * scale; const width = image.naturalWidth * ratio; const height = image.naturalHeight * ratio; ctx.drawImage(image, s.x + (s.width - width) / 2 + offsetX * 2, s.y + (s.height - height) / 2 + offsetY * 2, width, height); } else { ctx.fillStyle = "#252a38"; ctx.fillRect(s.x, s.y, s.width, s.height); ctx.fillStyle = "#94a3b8"; ctx.font = "32px sans-serif"; ctx.textAlign = "center"; ctx.fillText("Sua imagem", s.x + s.width / 2, s.y + s.height / 2); } ctx.restore(); drawFrame(ctx, template, true); }
function drawFrame(ctx: CanvasRenderingContext2D, item: MockupTemplate, front = false) { const s = item.screen; ctx.save(); if (item.frame === "shirt") { ctx.fillStyle = "#e5e7eb"; ctx.beginPath(); ctx.moveTo(500, 170); ctx.lineTo(390, 300); ctx.lineTo(520, 390); ctx.lineTo(490, 910); ctx.lineTo(1110, 910); ctx.lineTo(1080, 390); ctx.lineTo(1210, 300); ctx.lineTo(1100, 170); ctx.closePath(); ctx.fill(); } else if (item.frame === "outdoor") { ctx.fillStyle = "#64748b"; ctx.fillRect(120, 120, 1360, 690); ctx.fillRect(300, 810, 90, 150); ctx.fillRect(1210, 810, 90, 150); } else if (item.frame === "frame") { ctx.fillStyle = "#b08968"; ctx.fillRect(350, 70, 900, 840); } else { ctx.fillStyle = item.frame === "post" ? "#ffffff" : "#64748b"; ctx.fillRect(s.x - 45, s.y - 65, s.width + 90, s.height + 130); if (item.frame === "browser") { ctx.fillStyle = "#cbd5e1"; ctx.fillRect(s.x - 45, s.y - 65, s.width + 90, 55); } } if (front) { ctx.strokeStyle = "#111827"; ctx.lineWidth = 16; ctx.strokeRect(s.x, s.y, s.width, s.height); } ctx.restore(); }
