"use client";

import { openFilePicker } from "@/lib/browser/file-picker";
import { ChangeEvent, useRef, useState } from "react";
import { Download, FlipHorizontal, RotateCw, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ImageToolPageShell } from "@/components/tools/image-tool-page-shell";
import { canvasBlob, downloadBlob, IMAGE_TYPES, loadImage } from "@/lib/image-tools/canvas";

export function TransformImageClient() {
  const input = useRef<HTMLInputElement>(null); const [image,setImage]=useState<HTMLImageElement|null>(null); const [rotation,setRotation]=useState(0); const [horizontal,setHorizontal]=useState(false); const [vertical,setVertical]=useState(false); const [result,setResult]=useState<string|null>(null);
  const select=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file||!IMAGE_TYPES.includes(file.type))return;setImage(await loadImage(file));setRotation(0);setHorizontal(false);setVertical(false);setResult(null)};
  const apply=async()=>{if(!image)return;const side=rotation%180?{w:image.naturalHeight,h:image.naturalWidth}:{w:image.naturalWidth,h:image.naturalHeight};const canvas=document.createElement("canvas");canvas.width=side.w;canvas.height=side.h;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);ctx.scale(horizontal?-1:1,vertical?-1:1);ctx.drawImage(image,-image.naturalWidth/2,-image.naturalHeight/2);const blob=await canvasBlob(canvas);if(result)URL.revokeObjectURL(result);setResult(URL.createObjectURL(blob));};
  return <ImageToolPageShell title="Espelhar e Girar Imagem" description="Gire e espelhe imagens de forma rápida, sem enviar seus arquivos para um servidor."><Card className="mx-auto max-w-5xl"><CardHeader><CardTitle>Área de transformação</CardTitle><CardDescription>Use os controles para definir a rotação e o espelhamento.</CardDescription></CardHeader><CardContent><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={select}/>{!image?<div className="flex min-h-80 items-center justify-center border border-dashed border-border bg-muted/20"><Button onClick={()=>openFilePicker(input.current)}><Upload/>Selecionar imagem</Button></div>:<><div className="grid gap-5 lg:grid-cols-2"><div className="border border-border bg-background p-4"><img src={image.src} alt="Imagem selecionada" className="max-h-96 w-full object-contain"/></div><div className="border border-border bg-muted/20 p-4"><p className="text-sm font-medium">Rotação</p><div className="mt-3 flex flex-wrap gap-2">{[0,90,180,270].map((angle)=><Button key={angle} variant={rotation===angle?"default":"outline"} onClick={()=>setRotation(angle)}><RotateCw/>{angle}°</Button>)}</div><div className="mt-5 flex gap-5"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={horizontal} onChange={(e)=>setHorizontal(e.target.checked)}/>Espelhar horizontal</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={vertical} onChange={(e)=>setVertical(e.target.checked)}/>Espelhar vertical</label></div><Button className="mt-6" onClick={apply}><FlipHorizontal/>Aplicar transformação</Button></div></div>{result&&<div className="mt-6 border border-border bg-background p-4"><img src={result} alt="Imagem transformada" className="mx-auto max-h-96 max-w-full object-contain"/><Button className="mt-4" onClick={async()=>downloadBlob(await (await fetch(result)).blob(),"imagem-transformada.png")}><Download/>Baixar PNG</Button></div>}</>}</CardContent></Card></ImageToolPageShell>;
}
