"use client";

import { ChangeEvent, useRef, useState } from "react";
import { Download, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ImageToolPageShell } from "@/components/tools/image-tool-page-shell";
import { canvasBlob, downloadBlob, IMAGE_TYPES, loadImage } from "@/lib/image-tools/canvas";

export function WatermarkClient() {
  const input = useRef<HTMLInputElement>(null); const [image, setImage] = useState<HTMLImageElement | null>(null); const [text, setText] = useState("Sua marca"); const [opacity, setOpacity] = useState(60); const [size, setSize] = useState(8); const [position, setPosition] = useState("bottom-right"); const [result, setResult] = useState<string | null>(null);
  const select = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !IMAGE_TYPES.includes(file.type)) return; setImage(await loadImage(file)); setResult(null); };
  const apply = async () => { if (!image || !text.trim()) return; const canvas = document.createElement("canvas"); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.drawImage(image, 0, 0); ctx.globalAlpha = opacity / 100; ctx.fillStyle = "white"; ctx.strokeStyle = "rgba(0,0,0,.6)"; ctx.lineWidth = Math.max(2, image.naturalWidth * .003); ctx.font = `bold ${Math.max(14, image.naturalWidth * size / 100)}px sans-serif`; const metrics = ctx.measureText(text); const pad = image.naturalWidth * .04; const horizontal = position.includes("right") ? image.naturalWidth - metrics.width - pad : position.includes("left") ? pad : (image.naturalWidth - metrics.width) / 2; const vertical = position.includes("bottom") ? image.naturalHeight - pad : position.includes("top") ? image.naturalWidth * .08 : image.naturalHeight / 2; ctx.strokeText(text, horizontal, vertical); ctx.fillText(text, horizontal, vertical); const blob = await canvasBlob(canvas); if (result) URL.revokeObjectURL(result); setResult(URL.createObjectURL(blob)); };
  return <ImageToolPageShell title="Adicionar Marca d'Água" description="Proteja suas imagens com uma marca d'água de texto, processada localmente."><Card className="mx-auto max-w-5xl"><CardHeader><CardTitle>Área de edição</CardTitle><CardDescription>Personalize texto, tamanho, opacidade e posição.</CardDescription></CardHeader><CardContent><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={select}/>{!image ? <div className="flex min-h-80 items-center justify-center border border-dashed border-border bg-muted/20"><Button onClick={() => input.current?.click()}><Upload/>Selecionar imagem</Button></div> : <><div className="grid gap-5 lg:grid-cols-2"><div className="border border-border bg-background p-4"><img src={image.src} alt="Imagem selecionada" className="max-h-96 w-full object-contain"/></div><div className="border border-border bg-muted/20 p-4"><label className="text-sm font-medium">Texto<input value={text} onChange={(event) => setText(event.target.value)} className="mt-2 h-10 w-full border border-input bg-background px-3"/></label><label className="mt-4 block text-sm font-medium">Opacidade: {opacity}%<input type="range" min="10" max="100" value={opacity} onChange={(event) => setOpacity(Number(event.target.value))} className="mt-2 w-full"/></label><label className="mt-4 block text-sm font-medium">Tamanho: {size}%<input type="range" min="2" max="20" value={size} onChange={(event) => setSize(Number(event.target.value))} className="mt-2 w-full"/></label><label className="mt-4 block text-sm font-medium">Posição<select value={position} onChange={(event) => setPosition(event.target.value)} className="mt-2 h-10 w-full border border-input bg-background px-3"><option value="top-left">Superior esquerda</option><option value="top-center">Superior central</option><option value="top-right">Superior direita</option><option value="bottom-left">Inferior esquerda</option><option value="bottom-center">Inferior central</option><option value="bottom-right">Inferior direita</option></select></label><Button className="mt-5" onClick={apply}>{"Adicionar marca d'água"}</Button></div></div>{result && <div className="mt-6 border border-border bg-background p-4"><img src={result} alt="Resultado com marca d'água" className="mx-auto max-h-96 max-w-full object-contain"/><Button className="mt-4" onClick={async () => downloadBlob(await (await fetch(result)).blob(), "imagem-com-marca-dagua.png")}><Download/>Baixar PNG</Button></div>}</>}</CardContent></Card></ImageToolPageShell>;
}
