import Link from "next/link";
import { CheckCircle2 } from "lucide-react";

import { getToolMetadata } from "@/lib/seo";
import Mp4ParaAviClient from "./mp4-para-avi-client";

export const metadata = getToolMetadata("mp4-para-avi");

const faq = [
  ["Como converter MP4 para AVI?", "Selecione um MP4 válido, confira os dados detectados, mantenha ou ajuste qualidade, resolução e FPS, clique em Converter para AVI e baixe o resultado."],
  ["O arquivo original é alterado?", "Não. O arquivo MP4 usado no envio permanece inalterado. A ferramenta gera um novo arquivo AVI para download."],
  ["MP4 e AVI são codecs?", "Não. MP4 e AVI são containers que armazenam vídeo, áudio e metadados. H.264, MPEG-4 Part 2, AAC e MP3 são exemplos de codecs internos."],
  ["O arquivo final é realmente AVI?", "Sim. O servidor gera um container AVI com assinatura RIFF/AVI, decodifica o resultado para verificar sua integridade e só então libera o download."],
  ["O áudio é mantido?", "Sim. Quando existe áudio, ele é preservado. Na recodificação padrão, a faixa é convertida para MP3, compatível com o container AVI usado pela ferramenta."],
  ["A resolução é preservada?", "Sim, por padrão. Uma resolução menor só é aplicada quando você a escolhe, e a ferramenta nunca aumenta automaticamente as dimensões."],
  ["Converter para AVI reduz a qualidade?", "A maioria dos MP4 usa H.264 e AAC e precisa ser recodificada para MPEG-4 Part 2 e MP3. Nesse caso pode haver alguma alteração visual. Streams MPEG-4 Part 2 e MP3 compatíveis podem usar remux sem recompressão."],
  ["AVI funciona em quais programas?", "A compatibilidade depende do programa e dos codecs instalados. O perfil MPEG-4 Part 2 com áudio MP3 é aceito por muitos players, editores e sistemas que trabalham com AVI."],
  ["O tamanho do arquivo pode aumentar?", "Sim. O tamanho varia conforme codec, qualidade, bitrate, resolução, FPS, áudio, duração e complexidade das cenas. AVI não é necessariamente menor que MP4."],
  ["Posso usar a ferramenta no celular?", "Sim. A interface funciona em navegadores modernos de celular, embora o AVI pronto normalmente precise ser aberto em um aplicativo compatível depois do download."],
  ["Existe limite de tamanho?", "A ferramenta aceita um arquivo MP4 por vez com até 200 MB, duração máxima de 2 horas e resolução de entrada de até 4K."],
  ["O vídeo vertical continuará vertical?", "Sim. A proporção e a orientação detectadas são mantidas. Se uma resolução menor for escolhida, largura e altura são calculadas sem distorção."],
  ["O FPS será mantido?", "O padrão mantém o FPS original. Uma opção menor só reduz a taxa quando o vídeo possui FPS superior; a ferramenta não aumenta FPS automaticamente."],
  ["Por que alguns vídeos demoram mais?", "MP4 com H.264, HEVC, AAC ou outros codecs precisa ser recodificado para o perfil AVI compatível. Duração, resolução e complexidade do vídeo também afetam o tempo."],
  ["Por que o navegador não mostra uma prévia do AVI?", "A maioria dos navegadores não oferece reprodução nativa de AVI. Isso não invalida o arquivo: o servidor verifica a estrutura e a decodificação antes do download."],
] as const;

const schema = { "@context": "https://schema.org", "@graph": [
  { "@type": "SoftwareApplication", name: "MP4 para AVI", applicationCategory: "MultimediaApplication", operatingSystem: "Qualquer sistema com navegador moderno", url: "https://www.kivai.com.br/ferramentas/mp4-para-avi", description: "Converta vídeos MP4 para AVI com vídeo MPEG-4 Part 2 e áudio MP3 quando houver recodificação.", offers: { "@type": "Offer", price: "0", priceCurrency: "BRL" } },
  { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Início", item: "https://www.kivai.com.br" }, { "@type": "ListItem", position: 2, name: "Vídeos", item: "https://www.kivai.com.br/ferramentas/videos" }, { "@type": "ListItem", position: 3, name: "MP4 para AVI", item: "https://www.kivai.com.br/ferramentas/mp4-para-avi" }] },
  { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
] };

export default function Mp4ParaAviPage() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><Mp4ParaAviClient /><section className="border-t border-border bg-muted/10 py-12 sm:py-16"><div className="mx-auto w-full max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8">
    <div className="grid gap-6 lg:grid-cols-2"><Info title="O que é MP4?"><p>MP4 é um container amplamente usado em navegadores, celulares, câmeras e plataformas. Ele pode armazenar vídeo, áudio, legendas e metadados. H.264 ou HEVC com áudio AAC são combinações comuns, mas os codecs variam entre arquivos.</p></Info><Info title="O que é AVI?"><p>AVI significa Audio Video Interleave. É um container criado para reunir vídeo e áudio e ainda utilizado por programas, equipamentos e fluxos que solicitam esse formato. A compatibilidade depende também dos codecs internos.</p></Info></div>
    <Info title="Quando converter MP4 para AVI?"><p>A conversão é útil quando um programa, sistema antigo, dispositivo ou fluxo de produção aceita AVI, mas não importa o MP4 disponível. A ferramenta prepara um arquivo compatível sem alterar o original.</p><ul className="mt-4 grid gap-2 sm:grid-cols-2"><li className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />Importação em programas que solicitam AVI.</li><li className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />Uso em equipamentos e sistemas legados.</li><li className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />Entrega no formato especificado por um projeto.</li><li className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />Integração com fluxos de vídeo já padronizados.</li></ul></Info>
    <div className="grid gap-6 lg:grid-cols-2"><Info title="MP4 para AVI perde qualidade?"><p>MP4 e AVI são containers, mas os codecs comuns em cada fluxo podem ser diferentes. Um MP4 com H.264 e AAC é recodificado para vídeo MPEG-4 Part 2 e áudio MP3, o que pode causar alguma diferença visual ou sonora.</p><p className="mt-3">Se o MP4 já contém MPEG-4 Part 2 e MP3 e nenhuma transformação foi solicitada, os streams podem ser copiados por remux sem recompressão.</p></Info><Info title="O tamanho do AVI muda?"><p>Pode aumentar ou diminuir. O tamanho final depende de codec, qualidade, bitrate, resolução, FPS, duração, áudio e complexidade das cenas. Trocar apenas o container por remux costuma produzir uma diferença pequena; recodificar pode gerar variação maior.</p></Info></div>
    <div className="grid gap-6 lg:grid-cols-2"><Info title="Qual perfil é utilizado?"><p>Quando a recodificação é necessária, o mesmo FFmpeg usado pelo Hub Vídeos gera MPEG-4 Part 2 com identificação XVID e pixel format YUV 4:2:0. Quando há áudio, ele é convertido para MP3. Essa combinação prioriza compatibilidade com programas que trabalham com AVI.</p></Info><Info title="Limitações reais do AVI"><p>AVI é um formato antigo e não oferece as mesmas características de containers modernos em todos os cenários. Navegadores normalmente não o reproduzem, e recursos avançados de HDR, Dolby Vision, capítulos, legendas ou metadados específicos podem não ser preservados.</p></Info></div>
    <Info title="Como converter MP4 para AVI"><p>Imagine que você recebeu um vídeo em MP4, mas o programa onde precisa utilizá-lo aceita AVI. Selecione o arquivo, confira os dados detectados e converta diretamente sem instalar outro aplicativo.</p><ol className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Selecione o arquivo MP4.", "Confira duração, resolução e codecs.", "Mantenha ou ajuste qualidade, resolução e FPS.", "Clique em Converter para AVI.", "Aguarde a geração e a verificação.", "Baixe o arquivo AVI válido."].map((step, index) => <li key={step} className="rounded-lg border border-border p-4 text-sm"><span className="mb-3 flex size-7 items-center justify-center rounded-full bg-primary/10 font-semibold text-primary">{index + 1}</span>{step}</li>)}</ol></Info>
    <Info title="Recursos e limites"><ul className="grid gap-2 sm:grid-cols-2">{["Entrada validada: container MP4", "Saída real em container AVI", "Um arquivo por vez, até 200 MB", "Duração máxima de 2 horas", "Resolução máxima de entrada 4K", "Resolução e FPS nunca aumentados", "MPEG-4 Part 2 e MP3 na recodificação", "Remux para streams já compatíveis", "Vídeo vertical e proporção preservados", "Arquivo AVI decodificado para verificação", "Cancelamento durante a conversão", "Temporários removidos após o processamento"].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" />{item}</li>)}</ul></Info>
    <article className="rounded-xl border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Perguntas frequentes</h2><div className="mt-5 space-y-3">{faq.map(([question, answer]) => <details key={question} className="rounded-lg border border-border p-4"><summary className="cursor-pointer font-medium">{question}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{answer}</p></details>)}</div></article>
    <nav aria-label="Ferramentas relacionadas" className="rounded-xl border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Ferramentas relacionadas</h2><div className="mt-4 flex flex-wrap gap-3"><Related href="/ferramentas/mp4-para-mov">MP4 para MOV</Related><Related href="/ferramentas/mov-para-mp4">MOV para MP4</Related><Related href="/ferramentas/hevc-para-mp4">HEVC para MP4</Related><Related href="/ferramentas/compressor-de-videos">Compressor de Vídeos</Related><Related href="/ferramentas/video-para-audio">Vídeo para Áudio</Related><Related href="/ferramentas/redimensionar-video">Redimensionar Vídeo</Related><Related href="/ferramentas/dividir-video">Dividir Vídeo</Related><Related href="/ferramentas/capturar-frame-video">Capturar Frame</Related></div></nav>
  </div></section></>;
}

function Info({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">{title}</h2><div className="mt-4 leading-7 text-muted-foreground">{children}</div></article>; }
function Related({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="rounded-lg border border-border px-4 py-2 text-sm font-medium transition-colors hover:border-primary hover:text-primary">{children}</Link>; }
