"use client";
import { FormEvent, useRef, useState } from "react";
import { Check, Copy, Loader2, RotateCcw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ToolPageShell } from "@/components/tools/tool-page-shell";
type RegistroData = { status_code?: number; status?: string; fqdn?: string; fqdnace?: string; hosts?: string[]; ["publication-status"]?: string; ["expires-at"]?: string; suggestions?: string[] };
const display=(v?:string|number|null)=>v===undefined||v===null||v===""?"Não informado":String(v);
const date=(v?:string)=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short"}).format(new Date(v)):"Não informado";
export default function VerificadorDominioBrClient(){
 const [domain,setDomain]=useState(""),[result,setResult]=useState<RegistroData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[copied,setCopied]=useState(false);
 const ref=useRef<HTMLDivElement>(null);
 async function submit(e:FormEvent){e.preventDefault();setError("");setResult(null);setCopied(false);const value=domain.trim();if(!/\.br$/i.test(value)){setError("Informe um domínio .br, como kivai.com.br.");return}setLoading(true);try{const r=await fetch("/api/verificador-dominio-br",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({domain:value})});const p=await r.json().catch(()=>null) as RegistroData|{error?:string}|null;if(!r.ok){setError(p&&"error"in p&&p.error?p.error:"Não foi possível realizar a consulta.");return}setResult(p as RegistroData);setTimeout(()=>ref.current?.scrollIntoView({behavior:"smooth",block:"start"}),0)}catch{setError("Não foi possível conectar ao serviço de consulta. Tente novamente.")}finally{setLoading(false)}}
 async function copy(){if(!result)return;try{await navigator.clipboard.writeText(["Domínio: "+display(result.fqdn),"Status: "+display(result.status),"Status de publicação: "+display(result["publication-status"]),"Expira em: "+date(result["expires-at"]),"Hosts: "+(result.hosts?.join(", ")||"Não informado")].join("\n"));setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setError("Não foi possível copiar os dados.")}}
 function reset(){setDomain("");setResult(null);setError("");setCopied(false)}
 return <ToolPageShell title="Verificador de Domínio .BR" description="Consulte o status e outras informações públicas de um domínio .br." categoryName="Empresarial" categoryHref="/ferramentas" processingMode="server" privacyMessage="O domínio informado é enviado à BrasilAPI para consulta. O Kivai não salva o resultado da consulta.">
 <Card><CardHeader><CardTitle>Verificar domínio</CardTitle><CardDescription>Digite um domínio .br para consultar o status e as informações disponíveis.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="flex flex-col gap-4 sm:flex-row"><div className="min-w-0 flex-1"><label htmlFor="domain-br" className="text-sm font-medium">Domínio .BR</label><input id="domain-br" value={domain} onChange={e=>{setDomain(e.target.value);setResult(null);setError("")}} autoComplete="off" placeholder="kivai.com.br" className="mt-2 h-11 w-full border border-border bg-background px-3 text-sm outline-none focus:border-primary"/><p className="mt-2 text-xs leading-5 text-muted-foreground">Exemplo: kivai.com.br. Não é necessário informar https://.</p></div><div className="flex items-end gap-2 sm:shrink-0"><Button type="submit" size="lg" disabled={loading||!domain.trim()}>{loading?<Loader2 className="size-4 animate-spin"/>:<Search className="size-4"/>}{loading?"Consultando...":"Verificar domínio"}</Button><Button type="button" variant="outline" size="lg" onClick={reset} disabled={loading}><RotateCcw className="size-4"/>Limpar</Button></div></form>{error&&<div role="alert" className="mt-5 border border-destructive/30 bg-destructive/5 p-4 text-sm leading-6 text-destructive">{error}</div>}</CardContent></Card>
 {result&&<div ref={ref} className="mt-6 space-y-6"><Card><CardHeader><CardDescription>Domínio consultado</CardDescription><CardTitle className="text-2xl sm:text-3xl break-all">{display(result.fqdn)}</CardTitle><p className="mt-2 text-sm leading-6 text-muted-foreground">Status: <strong>{display(result.status)}</strong></p></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2"><div className="border border-border bg-muted/10 p-4"><dt className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Status</dt><dd className="mt-1 text-sm font-medium">{display(result.status)}</dd></div><div className="border border-border bg-muted/10 p-4"><dt className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Status de publicação</dt><dd className="mt-1 text-sm font-medium">{display(result["publication-status"])}</dd></div><div className="border border-border bg-muted/10 p-4"><dt className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Expiração</dt><dd className="mt-1 text-sm font-medium">{date(result["expires-at"])}</dd></div><div className="border border-border bg-muted/10 p-4"><dt className="text-xs font-medium uppercase tracking-wider text-muted-foreground">FQDN</dt><dd className="mt-1 break-all text-sm font-medium">{display(result.fqdn)}</dd></div></dl><div className="mt-5"><p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Servidores DNS</p><div className="mt-2 space-y-2">{result.hosts?.length?result.hosts.map(h=><div key={h} className="border border-border bg-muted/10 p-3 text-sm">{h}</div>):<p className="mt-2 text-sm">Não informado</p>}</div></div><div className="mt-5"><Button type="button" variant="outline" onClick={copy}>{copied?<Check className="size-4"/>:<Copy className="size-4"/>}{copied?"Dados copiados":"Copiar dados"}</Button></div></CardContent></Card>
 {result.suggestions?.length?<Card><CardHeader><CardTitle>Extensões sugeridas</CardTitle><CardDescription>Outras extensões .br relacionadas ao nome consultado.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2">{result.suggestions.map(s=><span key={s} className="border border-border px-3 py-2 text-sm">{s}</span>)}</div></CardContent></Card>:null}</div>}
 </ToolPageShell>
}