import { z } from "zod";
const text = z.string().max(10000);
const publication = z.object({ id: z.string().max(100), date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), title: text, network: text, format: text, objective: text, status: text, caption: text, cta: text, hashtags: text, observations: text, createdAt: text, updatedAt: text });
const briefing = z.object({ theme: text, objective: text, audience: text, networks: z.array(text).max(20), message: text, pillar: text, format: text, approach: text, hook: text, topics: z.array(text).max(200), ctaType: text, cta: text, tone: text, status: text });
const common = { id: z.uuid().nullable().optional(), title: z.string().trim().min(1).max(120), clientName: z.string().trim().max(100).default(""), revision: z.number().int().min(1).optional() };
export const projectInput = z.discriminatedUnion("kind", [
  z.object({ ...common, kind: z.literal("calendar"), payload: z.array(publication).max(1000) }),
  z.object({ ...common, kind: z.literal("briefing"), payload: briefing }),
  z.object({ ...common, kind: z.literal("qr_code"), payload: z.object({ tipo: z.string().max(30), url: text, texto: text, whatsappNumero: text, whatsappMensagem: text, telefone: text, emailDestino: text, emailAssunto: text, emailMensagem: text, wifiNome: text, wifiSenha: text, wifiSeguranca: z.string().max(20), wifiOculta: z.boolean(), corQr: z.string().max(20), corFundo: z.string().max(20), tamanho: z.number(), margem: z.number(), nivelCorrecao: z.string().max(10), modeloVisual: z.string().max(30), chamada: text, nomeMarca: text, logoDataUrl: z.string().max(300000) }) }),
  z.object({ ...common, kind: z.literal("watermark"), payload: z.object({ text, type: z.enum(["text", "logo"]), opacity: z.number().min(10).max(100), placement: z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1), scale: z.number().min(0).max(1) }), logoDataUrl: z.string().max(300000) }) }),
  z.object({ ...common, kind: z.literal("social_report"), payload: z.object({ id: text, reportName: text, client: text, profileName: text, username: text, network: text, responsible: text, startDate: text, endDate: text, compare: z.boolean(), previousStartDate: text, previousEndDate: text, engagementMethod: z.enum(["followers", "reach", "impressions"]), metrics: z.record(z.string(), text), previous: z.record(z.string(), text), notes: text, nextSteps: text, highlights: z.array(z.object({ id: text, title: text, format: text, reach: text, interactions: text, clicks: text, link: text })).max(6), rankBy: z.enum(["reach", "interactions", "rate", "clicks"]) }) }),
]);
export type SavedProject = { id: string; kind: "calendar" | "briefing" | "qr_code" | "watermark" | "social_report"; title: string; client_name: string; payload: unknown; revision: number; updated_at: string };
