"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowUp, Check, Clipboard, Download, Plus, Printer, RotateCcw, Trash2 } from "lucide-react";
import { ToolPageShell } from "@/components/tools/tool-page-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

const STORAGE_KEY = "kivai:planejador-conteudo-social-media:v1";
const objectives = ["Engajamento", "Alcance", "Autoridade", "Educação", "Relacionamento", "Entretenimento", "Tráfego", "Geração de leads", "Conversão", "Vendas", "Divulgação", "Institucional", "Lançamento", "Outro"];
const networks = ["Instagram", "Facebook", "TikTok", "YouTube", "LinkedIn", "X", "Threads", "Pinterest", "Outra"];
const pillars = ["Educacional", "Informativo", "Entretenimento", "Inspiracional", "Autoridade", "Relacionamento", "Institucional", "Promocional", "Bastidores", "Prova social", "Notícia/Atualidade", "Produto/Serviço", "Outro"];
const formats = ["Imagem", "Post estático", "Carrossel", "Reels", "Stories", "Vídeo", "Shorts", "Texto", "Artigo", "Live", "Enquete", "Infográfico", "Tutorial", "Antes e depois", "Depoimento", "Bastidores", "Outro"];
const approaches = ["Lista", "Passo a passo", "Tutorial", "Pergunta e resposta", "Erro comum", "Mito ou verdade", "Dica rápida", "Comparação", "Checklist", "Problema e solução", "História", "Bastidores", "Opinião", "Curiosidade", "Estudo de caso", "FAQ", "Outra"];
const ctaTypes = ["Nenhum CTA", "Comentar", "Compartilhar", "Salvar", "Seguir o perfil", "Visitar site", "Acessar link", "Enviar mensagem", "Entrar em contato", "Solicitar orçamento", "Conhecer produto", "Conhecer serviço", "Comprar", "Inscrever-se", "Assistir outro conteúdo", "Outro"];
const tones = ["Profissional", "Educativo", "Informativo", "Descontraído", "Conversacional", "Persuasivo", "Inspirador", "Direto", "Institucional", "Técnico", "Jornalístico", "Outro"];
const statuses = ["Ideia", "Planejado", "Em produção", "Em revisão", "Aguardando aprovação", "Aprovado", "Pronto para publicar", "Publicado"];
const hookSuggestions: Record<string, string> = { Lista: "5 pontos para considerar antes de…", "Passo a passo": "Veja as etapas para…", Tutorial: "Aprenda como…", "Pergunta e resposta": "Você já se perguntou…", "Erro comum": "Um erro comum ao…", "Mito ou verdade": "Mito ou verdade: …", "Dica rápida": "Uma dica prática para…", Comparação: "Qual é a diferença entre…", Checklist: "Confira o que observar antes de…", "Problema e solução": "Se você enfrenta…, considere…" };

type Plan = { objective: string; networks: string[]; audience: string; theme: string; message: string; pillar: string; format: string; approach: string; hook: string; topics: string[]; ctaType: string; cta: string; tone: string; status: string };
const emptyPlan: Plan = { objective: "", networks: [], audience: "", theme: "", message: "", pillar: "", format: "", approach: "", hook: "", topics: [""], ctaType: "Nenhum CTA", cta: "", tone: "", status: "Ideia" };

function isPlan(value: unknown): value is Plan { return !!value && typeof value === "object" && typeof (value as Plan).theme === "string" && Array.isArray((value as Plan).networks) && Array.isArray((value as Plan).topics); }
function planText(plan: Plan, briefing = false) {
  const topics = plan.topics.filter(Boolean).map((topic, index) => `${index + 1}. ${topic}`).join("\n") || "Não informado";
  return `${briefing ? "BRIEFING DE CONTEÚDO" : "PLANO DE CONTEÚDO"}\n\nTema: ${plan.theme || "Não informado"}\nObjetivo: ${plan.objective || "Não informado"}\nPúblico: ${plan.audience || "Não informado"}\nRede social: ${plan.networks.join(", ") || "Não informada"}\nMensagem principal: ${plan.message || "Não informada"}\nPilar: ${plan.pillar || "Não informado"}\nFormato: ${plan.format || "Não informado"}\nAbordagem: ${plan.approach || "Não informada"}\nGancho: ${plan.hook || "Não informado"}\n\nPontos principais:\n${topics}\n\nCTA: ${plan.cta || plan.ctaType || "Nenhum CTA"}\nTom de comunicação: ${plan.tone || "Não informado"}\nStatus: ${plan.status || "Não informado"}`;
}

export default function PlanejadorClient() {
  const [plan, setPlan] = useState<Plan>(emptyPlan); const [ready, setReady] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({});
  const [generated, setGenerated] = useState(false); const [feedback, setFeedback] = useState(""); const [confirmClear, setConfirmClear] = useState(false);
  const resultRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "null");
      if (isPlan(saved)) {
        // Browser-only persistence is intentionally restored after hydration.
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setPlan(saved);
        setGenerated(Boolean(saved.theme));
      }
    } catch { localStorage.removeItem(STORAGE_KEY); }
    setReady(true);
  }, []);
  useEffect(() => { if (ready) localStorage.setItem(STORAGE_KEY, JSON.stringify(plan)); }, [plan, ready]);
  const update = <K extends keyof Plan>(key: K, value: Plan[K]) => { setPlan((current) => ({ ...current, [key]: value })); if (errors[key]) setErrors((current) => ({ ...current, [key]: "" })); };
  const validTopics = useMemo(() => plan.topics.filter((topic) => topic.trim()), [plan.topics]);
  function generate() { const next: Record<string, string> = {}; if (!plan.theme.trim()) next.theme = "Informe o tema do conteúdo."; if (!plan.objective) next.objective = "Escolha um objetivo."; if (!plan.networks.length) next.networks = "Selecione ao menos uma rede social."; if (!plan.audience.trim()) next.audience = "Informe o público do conteúdo."; setErrors(next); if (!Object.keys(next).length) { setGenerated(true); window.setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); } }
  function topic(index: number, value: string) { update("topics", plan.topics.map((item, itemIndex) => itemIndex === index ? value : item)); }
  function moveTopic(index: number, offset: number) { const target = index + offset; if (target < 0 || target >= plan.topics.length) return; const next = [...plan.topics]; [next[index], next[target]] = [next[target], next[index]]; update("topics", next); }
  async function copy(briefing = false) { try { await navigator.clipboard.writeText(planText(plan, briefing)); setFeedback(briefing ? "Briefing copiado." : "Planejamento copiado."); window.setTimeout(() => setFeedback(""), 2500); } catch { setFeedback("Não foi possível copiar. Selecione o texto e tente novamente."); } }
  function download() { const blob = new Blob([planText(plan, true)], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "briefing-conteudo-social-media.txt"; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }
  function clear() { setPlan(emptyPlan); setGenerated(false); setErrors({}); setConfirmClear(false); localStorage.removeItem(STORAGE_KEY); }

  return <ToolPageShell title="Planejador de Conteúdo Social Media" description="Transforme uma ideia em um plano estruturado com objetivo, público, mensagem, formato, abordagem e briefing para produção." categoryName="Social Media" categoryHref="/ferramentas/social-media" breadcrumbRootName="Início" breadcrumbRootHref="/" privacyMessage="Seu planejamento fica salvo somente neste navegador. Nenhuma informação é enviada ao Kivai.">
    <style>{`@media print { body > header, body > footer, nav, [data-print-hide], [data-ad-slot] { display:none !important } main { background:white !important; color:black !important } [data-print-plan] { display:block !important; border:0 !important; box-shadow:none !important } [data-print-plan] * { color:black !important } }`}</style>
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(300px,.75fr)]">
      <Card data-print-hide><CardHeader><CardTitle className="text-base">Estruture seu conteúdo</CardTitle><CardDescription>Preencha o essencial primeiro. Os demais campos ajudam a deixar o briefing mais claro para produção.</CardDescription></CardHeader><CardContent className="space-y-7">
        <Section number="1" title="Estratégia"><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Objetivo principal" value={plan.objective} options={objectives} onChange={(value) => update("objective", value)} error={errors.objective} /><TextField label="Público" value={plan.audience} onChange={(value) => update("audience", value)} placeholder="Ex.: donos de pequenas empresas" error={errors.audience} /></div><fieldset className="mt-4"><legend className="text-sm font-medium">Onde será publicado?</legend><div className="mt-2 flex flex-wrap gap-2">{networks.map((network) => <label key={network} className={cn("cursor-pointer border px-3 py-2 text-xs", plan.networks.includes(network) ? "border-primary bg-primary/10 text-primary" : "border-border")}><input type="checkbox" className="sr-only" checked={plan.networks.includes(network)} onChange={(event) => update("networks", event.target.checked ? [...plan.networks, network] : plan.networks.filter((item) => item !== network))} />{network}</label>)}</div>{errors.networks && <p className="mt-1 text-xs text-destructive">{errors.networks}</p>}<p className="mt-2 text-xs text-muted-foreground">Cada plataforma pode exigir adaptações de formato, duração e linguagem.</p></fieldset></Section>
        <Section number="2" title="Conteúdo"><TextField label="Tema do conteúdo" value={plan.theme} onChange={(value) => update("theme", value)} placeholder="Ex.: como escolher uma clínica odontológica" error={errors.theme} /><label className="mt-4 grid gap-1.5 text-sm font-medium">Mensagem principal<span className="text-xs font-normal text-muted-foreground">O que a pessoa deve entender depois de consumir o conteúdo?</span><textarea rows={3} value={plan.message} onChange={(event) => update("message", event.target.value)} className="border border-border bg-background p-3" /></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><SelectField label="Pilar de conteúdo" value={plan.pillar} options={pillars} onChange={(value) => update("pillar", value)} /><SelectField label="Formato" value={plan.format} options={formats} onChange={(value) => update("format", value)} /></div>{plan.pillar === "Educacional" && <p className="mt-2 text-xs text-muted-foreground">Conteúdo criado para ensinar ou explicar um assunto.</p>}{plan.pillar === "Prova social" && <p className="mt-2 text-xs text-muted-foreground">Use avaliações, experiências e resultados reais, sem prometer resultados futuros.</p>}</Section>
        <Section number="3" title="Estrutura"><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Abordagem" value={plan.approach} options={approaches} onChange={(value) => update("approach", value)} /><TextField label="Gancho ou abertura" value={plan.hook} onChange={(value) => update("hook", value)} placeholder={hookSuggestions[plan.approach] || "Apresente o assunto de forma clara"} /></div>{hookSuggestions[plan.approach] && !plan.hook && <button type="button" className="mt-2 text-xs text-primary hover:underline" onClick={() => update("hook", hookSuggestions[plan.approach])}>Usar sugestão: “{hookSuggestions[plan.approach]}”</button>}<div className="mt-5"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-medium">Pontos principais</h3><Button size="sm" variant="outline" onClick={() => update("topics", [...plan.topics, ""])}><Plus />Adicionar tópico</Button></div><div className="mt-3 space-y-2">{plan.topics.map((item, index) => <div key={index} className="flex min-w-0 items-center gap-2"><span className="w-5 shrink-0 text-center text-xs text-muted-foreground">{index + 1}</span><input aria-label={`Tópico ${index + 1}`} value={item} onChange={(event) => topic(index, event.target.value)} className="min-h-10 min-w-0 flex-1 border border-border bg-background px-3" placeholder={`Ponto ${index + 1}`} /><Button type="button" size="icon-sm" variant="ghost" aria-label={`Mover tópico ${index + 1} para cima`} disabled={index === 0} onClick={() => moveTopic(index, -1)}><ArrowUp /></Button><Button type="button" size="icon-sm" variant="ghost" aria-label={`Mover tópico ${index + 1} para baixo`} disabled={index === plan.topics.length - 1} onClick={() => moveTopic(index, 1)}><ArrowDown /></Button><Button type="button" size="icon-sm" variant="destructive" aria-label={`Excluir tópico ${index + 1}`} disabled={plan.topics.length === 1} onClick={() => update("topics", plan.topics.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></Button></div>)}</div></div></Section>
        <Section number="4" title="Publicação"><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Ação desejada" value={plan.ctaType} options={ctaTypes} onChange={(value) => update("ctaType", value)} /><TextField label="CTA final" value={plan.cta} onChange={(value) => update("cta", value)} placeholder="Ex.: saiba mais em nosso site" /><SelectField label="Tom de comunicação" value={plan.tone} options={tones} onChange={(value) => update("tone", value)} /><SelectField label="Status" value={plan.status} options={statuses} onChange={(value) => update("status", value)} /></div></Section>
        <div className="flex flex-wrap gap-2"><Button size="lg" onClick={generate}><Check />Gerar plano de conteúdo</Button><Button size="lg" variant="outline" onClick={() => setConfirmClear(true)}><RotateCcw />Novo planejamento</Button></div>
      </CardContent></Card>
      <aside className="hidden lg:sticky lg:top-24 lg:block"><PlanResult plan={plan} topics={validTopics} compact /></aside>
    </div>
    {generated && <div ref={resultRef} className="scroll-mt-24"><PlanResult plan={plan} topics={validTopics} actions onCopy={copy} onDownload={download} feedback={feedback} /></div>}
    <section data-print-hide className="border border-primary/20 bg-primary/5 p-5"><h2 className="text-lg font-semibold">Organize também suas datas de publicação</h2><p className="mt-2 text-sm text-muted-foreground">Depois de estruturar cada pauta, distribua os conteúdos no mês e acompanhe a produção.</p><Button asChild variant="outline" className="mt-4"><Link href="/ferramentas/calendario-editorial-redes-sociais">Abrir Calendário Editorial</Link></Button></section>
    {confirmClear && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/65 p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setConfirmClear(false); }}><div role="dialog" aria-modal="true" aria-labelledby="clear-title" className="w-full max-w-md border border-border bg-background p-6"><h2 id="clear-title" className="text-xl font-semibold">Começar novo planejamento?</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Os dados preenchidos atualmente serão apagados deste navegador.</p><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => setConfirmClear(false)}>Cancelar</Button><Button variant="destructive" onClick={clear}>Limpar planejamento</Button></div></div></div>}
  </ToolPageShell>;
}

function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <fieldset className="border-t border-border pt-5"><legend className="mb-4 flex items-center gap-2 pr-3 text-base font-semibold"><span className="flex size-6 items-center justify-center bg-primary text-xs text-primary-foreground">{number}</span>{title}</legend>{children}</fieldset>; }
function SelectField({ label, value, options, onChange, error }: { label: string; value: string; options: string[]; onChange: (value: string) => void; error?: string }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<select value={value} onChange={(event) => onChange(event.target.value)} aria-invalid={!!error} className="min-h-10 min-w-0 border border-border bg-background px-3"><option value="">Selecione</option>{options.map((option) => <option key={option}>{option}</option>)}</select>{error && <span className="text-xs text-destructive">{error}</span>}</label>; }
function TextField({ label, value, onChange, placeholder, error }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; error?: string }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} aria-invalid={!!error} className="min-h-10 min-w-0 border border-border bg-background px-3" />{error && <span className="text-xs text-destructive">{error}</span>}</label>; }
function PlanResult({ plan, topics, compact = false, actions = false, onCopy, onDownload, feedback }: { plan: Plan; topics: string[]; compact?: boolean; actions?: boolean; onCopy?: (briefing?: boolean) => void; onDownload?: () => void; feedback?: string }) { const rows = [["Tema", plan.theme], ["Objetivo", plan.objective], ["Público", plan.audience], ["Rede social", plan.networks.join(", ")], ["Mensagem principal", plan.message], ["Pilar", plan.pillar], ["Formato", plan.format], ["Abordagem", plan.approach], ["Gancho", plan.hook], ["CTA", plan.cta || plan.ctaType], ["Tom", plan.tone], ["Status", plan.status]]; return <Card data-print-plan className={cn(compact && "max-h-[calc(100vh-7rem)] overflow-y-auto")}><CardHeader><CardTitle className="text-base">{actions ? "Plano de conteúdo e briefing" : "Prévia do plano"}</CardTitle><CardDescription>{compact ? "Atualizada enquanto você preenche." : "Revise as informações antes de enviar para produção."}</CardDescription></CardHeader><CardContent><dl className="grid gap-3 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className={cn("border-b border-border pb-2", ["Tema", "Público", "Mensagem principal", "Gancho"].includes(label) && "sm:col-span-2")}><dt className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{value || "Não informado"}</dd></div>)}</dl><div className="mt-4"><h3 className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Pontos principais</h3>{topics.length ? <ol className="mt-2 list-decimal space-y-1 pl-5 text-sm">{topics.map((topic, index) => <li key={`${topic}-${index}`}>{topic}</li>)}</ol> : <p className="mt-1 text-sm">Não informado</p>}</div>{actions && <div data-print-hide className="mt-6 flex flex-wrap gap-2"><Button onClick={() => onCopy?.(false)}><Clipboard />Copiar planejamento</Button><Button variant="outline" onClick={() => onCopy?.(true)}><Clipboard />Copiar briefing</Button><Button variant="outline" onClick={onDownload}><Download />Exportar TXT</Button><Button variant="outline" onClick={() => window.print()}><Printer />Imprimir</Button>{feedback && <p role="status" className="w-full text-sm text-primary">{feedback}</p>}</div>}</CardContent></Card>; }
