"use client";

import { openFilePicker } from "@/lib/browser/file-picker";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { Download, FileText, RefreshCw, RotateCcw, Scaling, Trash2, Upload } from "lucide-react";

import { ToolActionBar } from "@/components/tools/tool-action-bar";
import { ToolErrorMessage } from "@/components/tools/tool-error-message";
import { ToolPageShell } from "@/components/tools/tool-page-shell";
import { ToolProcessingStatus, type ToolStatus } from "@/components/tools/tool-processing-status";
import { ToolResultCard } from "@/components/tools/tool-result-card";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { formatFileSize } from "@/lib/tool-files";
import { PDF_PAGE_SIZES, RESIZE_PDF_MAX_FILE_SIZE, RESIZE_PDF_MAX_FILE_SIZE_LABEL, type BackgroundMode, type MarginPreset, type PageApplication, type PageMargins, type PdfTargetSize, type PreviewMode, type ResizeMode, type ResizeOrientation } from "./config";
import { calculatePlacement, disposeResizeInspection, inspectResizePdf, parsePageRange, resizePdf, type ResizePdfInspection, type ResizePageInfo } from "./resize-pdf-engine";

type Result = { name: string; size: number; pages: number; format: PdfTargetSize; blob: Blob };
const PRESET_MARGINS: Record<Exclude<MarginPreset, "custom">, PageMargins> = { none: { top: 0, right: 0, bottom: 0, left: 0 }, small: { top: 5, right: 5, bottom: 5, left: 5 }, normal: { top: 10, right: 10, bottom: 10, left: 10 }, large: { top: 20, right: 20, bottom: 20, left: 20 } };

function friendlyError(error: unknown) { const code = error instanceof Error ? error.message : ""; if (code === "invalid-pdf") return "Selecione um arquivo no formato PDF."; if (code === "too-many-pages") return "Este PDF ultrapassa o limite de 100 páginas."; if (code === "protected-pdf") return "Este PDF possui proteção e não pôde ser redimensionado."; if (code === "corrupt-pdf" || code === "invalid-dimensions") return "Não foi possível abrir este PDF. Verifique o arquivo e tente novamente."; if (code === "no-pages") return "Selecione pelo menos uma página para redimensionar."; if (code === "invalid-margins") return "As margens escolhidas são grandes demais para o tamanho da página."; if (code === "invalid-range") return "Informe páginas válidas, como 1-5 ou 1,3,7."; if (code === "out-of-memory") return "Este documento exige mais memória do que o dispositivo pode disponibilizar."; return "Não foi possível gerar o PDF redimensionado. Revise as configurações e tente novamente."; }
function outputName(name: string, size: PdfTargetSize) { return `${name.replace(/\.pdf$/i, "").replace(/[<>:\"/\\|?*\u0000-\u001f]/g, "-").trim() || "documento"}-${size.toLowerCase()}.pdf`; }

export default function RedimensionarPdfClient() {
  const inputRef = useRef<HTMLInputElement>(null); const replaceRef = useRef<HTMLInputElement>(null); const inspectionRef = useRef<ResizePdfInspection | null>(null); const resultUrlRef = useRef<string | null>(null);
  const [file, setFile] = useState<File | null>(null); const [pages, setPages] = useState<ResizePageInfo[]>([]); const [configured, setConfigured] = useState(false); const [targetSize, setTargetSize] = useState<PdfTargetSize>("A4"); const [orientation, setOrientation] = useState<ResizeOrientation>("original"); const [mode, setMode] = useState<ResizeMode>("fit"); const [marginPreset, setMarginPreset] = useState<MarginPreset>("normal"); const [customMargins, setCustomMargins] = useState<PageMargins>({ top: 10, right: 10, bottom: 10, left: 10 }); const [background, setBackground] = useState<BackgroundMode>("white"); const [customColor, setCustomColor] = useState("#ffffff"); const [application, setApplication] = useState<PageApplication>("all"); const [range, setRange] = useState(""); const [previewMode, setPreviewMode] = useState<PreviewMode>("compare"); const [activePage, setActivePage] = useState(1);
  const [status, setStatus] = useState<ToolStatus>("idle"); const [stage, setStage] = useState("Lendo o PDF"); const [error, setError] = useState<string | null>(null); const [rangeError, setRangeError] = useState<string | null>(null); const [dragging, setDragging] = useState(false); const [result, setResult] = useState<Result | null>(null); const [resultUrl, setResultUrl] = useState<string | null>(null);
  useEffect(() => { resultUrlRef.current = resultUrl; }, [resultUrl]); useEffect(() => () => { disposeResizeInspection(inspectionRef.current); if (resultUrlRef.current) URL.revokeObjectURL(resultUrlRef.current); }, []);
  const margins = marginPreset === "custom" ? customMargins : PRESET_MARGINS[marginPreset]; const selectedPages = pages.filter((page) => page.selected); const page = pages.find((item) => item.pageNumber === activePage) ?? pages[0];
  const mixedSizes = pages.length > 1 && pages.some((item) => Math.abs(item.widthPt - pages[0].widthPt) > 1 || Math.abs(item.heightPt - pages[0].heightPt) > 1);
  let placement = null; let cutRisk = false; try { if (page) { placement = calculatePlacement(page, { targetSize, orientation, mode, margins, background, customColor }); cutRisk = placement.cropped; } } catch { placement = null; }
  function clearResult() { if (resultUrlRef.current) URL.revokeObjectURL(resultUrlRef.current); resultUrlRef.current = null; setResult(null); setResultUrl(null); }
  function reset() { disposeResizeInspection(inspectionRef.current); inspectionRef.current = null; clearResult(); setFile(null); setPages([]); setConfigured(false); setError(null); setRangeError(null); setStatus("idle"); }
  async function selectFile(files: File[]) { const selected = files[0]; if (!selected || status === "processing") return; setError(null); const ext = selected.name.split(".").pop()?.toLowerCase(); if (ext !== "pdf" || !["application/pdf", "application/octet-stream", ""].includes(selected.type) || !selected.size) { setError(friendlyError(new Error("invalid-pdf"))); setStatus("error"); return; } if (selected.size > RESIZE_PDF_MAX_FILE_SIZE) { setError(`O arquivo ultrapassa o limite permitido de ${RESIZE_PDF_MAX_FILE_SIZE_LABEL}.`); setStatus("error"); return; } disposeResizeInspection(inspectionRef.current); clearResult(); setFile(null); setPages([]); setConfigured(false); setStatus("processing"); setStage("Lendo o PDF"); try { const inspection = await inspectResizePdf(selected, setStage); inspectionRef.current = inspection; setFile(selected); setPages(inspection.pages); setActivePage(1); const firstFormat = inspection.pages[0].format; if (firstFormat !== "personalizado" && firstFormat in PDF_PAGE_SIZES) setTargetSize(firstFormat as PdfTargetSize); setStatus("ready"); } catch (reason) { setError(friendlyError(reason)); setStatus("error"); } }
  function applyRange() { if (!pages.length) return; try { const parsed = parsePageRange(range, pages.length); if (!parsed) { setRangeError(null); return; } setPages((current) => current.map((item) => ({ ...item, selected: parsed.includes(item.pageNumber) }))); setRangeError(null); } catch (reason) { setRangeError(friendlyError(reason)); } }
  async function convert() { if (!inspectionRef.current || status === "processing") return; setError(null); let pageNumbers: number[]; try { pageNumbers = application === "all" ? pages.map((item) => item.pageNumber) : application === "selected" ? selectedPages.map((item) => item.pageNumber) : parsePageRange(range, pages.length) ?? []; if (!pageNumbers.length) throw new Error("no-pages"); calculatePlacement(page ?? pages[0], { targetSize, orientation, mode, margins, background, customColor }); } catch (reason) { setError(friendlyError(reason)); setStatus("error"); return; } setStatus("processing"); setStage("Aplicando o novo tamanho"); try { const blob = await resizePdf(inspectionRef.current.bytes, pages, { targetSize, orientation, mode, margins, background, customColor, pageNumbers }, setStage); clearResult(); const url = URL.createObjectURL(blob); setResult({ name: outputName(file?.name ?? "documento.pdf", targetSize), size: blob.size, pages: pageNumbers.length, format: targetSize, blob }); setResultUrl(url); setStatus("success"); } catch (reason) { setError(friendlyError(reason)); setStatus("error"); } }

  return <ToolPageShell title="Redimensionar PDF" description="Altere o tamanho das páginas do seu PDF para A6, A5, A4, A3, A2 ou A1." categoryName="PDF" categoryHref="/ferramentas/pdfs" breadcrumbRootName="Início" breadcrumbRootHref="/" privacyMessage="Use somente documentos que você tem autorização para processar."><Card className="mx-auto max-w-6xl"><CardHeader><CardTitle>Redimensionar PDF</CardTitle><CardDescription>Altere o tamanho das páginas do seu PDF para A6, A5, A4, A3, A2 ou A1.</CardDescription></CardHeader><CardContent className="space-y-6">
    {!file && status !== "processing" && <><input ref={inputRef} type="file" accept="application/pdf,.pdf" className="sr-only" onChange={(event) => { void selectFile(Array.from(event.target.files ?? [])); event.target.value = ""; }} /><div onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setDragging(false); }} onDrop={(event) => { event.preventDefault(); setDragging(false); void selectFile(Array.from(event.dataTransfer.files)); }} className={`flex min-h-64 flex-col items-center justify-center border border-dashed p-6 text-center sm:p-10 ${dragging ? "border-primary bg-primary/5" : "border-border bg-muted/20"}`}><span className="flex size-14 items-center justify-center border border-border bg-background"><Upload className="size-5" /></span><p className="mt-5 font-heading text-lg font-medium">Arraste seu PDF aqui</p><p className="mt-2 text-sm text-muted-foreground">ou clique para selecionar</p><p className="mt-2 text-xs text-muted-foreground">Formato aceito: PDF</p><Button className="mt-5" onClick={() => openFilePicker(inputRef.current)}><FileText className="size-4" />Selecionar PDF</Button></div><ToolErrorMessage message={error} /></>}
    <ToolProcessingStatus status={status} message={stage} />
    {file && status !== "success" && <><section aria-label="PDF selecionado" className="flex flex-col gap-4 rounded-lg border border-border p-4 sm:flex-row sm:items-center"><div className="relative aspect-[3/4] w-20 shrink-0 overflow-hidden border bg-white">{pages[0] && <Image src={pages[0].thumbnailUrl} alt="Miniatura da primeira página" fill unoptimized className="object-contain" />}</div><div className="min-w-0 flex-1"><p className="truncate font-medium">{file.name}</p><p className="mt-1 text-sm text-muted-foreground">PDF · {formatFileSize(file.size)} · {pages.length} {pages.length === 1 ? "página" : "páginas"}</p>{pages[0] && <p className="mt-1 text-xs text-muted-foreground">Tamanho atual: {Math.round(pages[0].widthMm)} × {Math.round(pages[0].heightMm)} mm, {pages[0].format} · {pages.filter((item) => item.orientation === "landscape").length > pages.length / 2 ? "paisagem" : "retrato"}</p>}</div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={reset}><Trash2 className="size-4" />Remover</Button><input ref={replaceRef} type="file" accept="application/pdf,.pdf" className="sr-only" onChange={(event) => { void selectFile(Array.from(event.target.files ?? [])); event.target.value = ""; }} /><Button variant="outline" size="sm" onClick={() => openFilePicker(replaceRef.current)}><RefreshCw className="size-4" />Substituir</Button></div></section>{mixedSizes && <Notice>Este PDF possui páginas com tamanhos diferentes.</Notice>}{!configured && <ToolActionBar><Button size="lg" onClick={() => setConfigured(true)}><Scaling className="size-4" />Configurar tamanho</Button></ToolActionBar>}</>}
    {file && configured && status !== "success" && <><section aria-labelledby="formatos-pdf"><h2 id="formatos-pdf" className="font-heading text-lg font-medium">Novo tamanho</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(PDF_PAGE_SIZES).map(([name, size]) => <button key={name} type="button" aria-pressed={targetSize === name} onClick={() => setTargetSize(name as PdfTargetSize)} className={`rounded-lg border p-3 text-left transition-colors ${targetSize === name ? "border-primary bg-primary/5 ring-1 ring-primary/30" : "border-border hover:border-primary/60"}`}><span className="font-heading text-lg font-semibold">{name}</span><span className="mt-1 block text-xs text-muted-foreground">{size.widthMm} × {size.heightMm} mm</span><span className="mx-auto mt-3 block border border-primary/40 bg-primary/5" style={{ width: 30 * size.widthMm / size.heightMm, height: 42 }} /><span className="mt-3 block text-[11px] leading-4 text-muted-foreground">{size.use}</span>{name === "A4" && <span className="mt-2 inline-block rounded bg-primary/10 px-2 py-0.5 text-[10px] text-primary">Mais comum</span>}</button>)}</div></section>
      <fieldset className="grid gap-5 rounded-lg border border-border p-4 sm:grid-cols-2 lg:grid-cols-3"><legend className="px-2 font-heading font-medium">Configurações</legend><Select label="Orientação" value={orientation} onChange={(value) => setOrientation(value as ResizeOrientation)} options={[["original", "Manter orientação original"], ["portrait", "Retrato"], ["landscape", "Paisagem"]]} /><Select label="Modo de ajuste" value={mode} onChange={(value) => setMode(value as ResizeMode)} options={[["fit", "Ajustar página inteira"], ["fill", "Preencher a página"], ["stretch", "Esticar para preencher"], ["original", "Manter tamanho original"]]} /><Select label="Margens" value={marginPreset} onChange={(value) => setMarginPreset(value as MarginPreset)} options={[["none", "Sem margem"], ["small", "Pequena (5 mm)"], ["normal", "Normal (10 mm)"], ["large", "Grande (20 mm)"], ["custom", "Personalizada"]]} /><Select label="Cor de fundo" value={background} onChange={(value) => setBackground(value as BackgroundMode)} options={[["white", "Branco"], ["transparent", "Sem preenchimento"], ["black", "Preto"], ["custom", "Cor personalizada"]]} />{background === "custom" && <label className="grid gap-2 text-sm font-medium">Cor personalizada<input type="color" value={customColor} onChange={(event) => setCustomColor(event.target.value)} className="h-11 w-full" /></label>}{marginPreset === "custom" && <div className="grid grid-cols-2 gap-2">{(["top", "right", "bottom", "left"] as const).map((side) => <label key={side} className="grid gap-1 text-xs capitalize">{({ top: "Superior", right: "Direita", bottom: "Inferior", left: "Esquerda" })[side]}<input type="number" min="0" value={customMargins[side]} onChange={(event) => setCustomMargins((current) => ({ ...current, [side]: Math.max(0, Number(event.target.value)) }))} className="min-h-9 rounded-md border border-input bg-background px-2" /></label>)}</div>}</fieldset>
      {(mode === "fill" || mode === "original" || cutRisk) && <Notice>Parte do conteúdo ficará fora da página com esta configuração.</Notice>}{mode === "fill" && <Notice>Este modo pode cortar partes das bordas do documento.</Notice>}{mode === "stretch" && <Notice>Este modo pode distorcer o conteúdo.</Notice>}
      <section aria-labelledby="paginas-redimensionar"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="paginas-redimensionar" className="font-heading text-lg font-medium">Páginas</h2><p className="mt-1 text-sm text-muted-foreground">{selectedPages.length} de {pages.length} selecionadas</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => setPages((current) => current.map((item) => ({ ...item, selected: true })))}>Selecionar todas</Button><Button variant="outline" size="sm" onClick={() => setPages((current) => current.map((item) => ({ ...item, selected: false })))}>Desmarcar todas</Button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{pages.map((item) => <label key={item.pageNumber} className={`cursor-pointer rounded-lg border p-2 ${item.pageNumber === activePage ? "border-primary" : "border-border"}`} onClick={() => setActivePage(item.pageNumber)}><span className="relative block aspect-[3/4] overflow-hidden bg-white"><Image src={item.thumbnailUrl} alt={`Miniatura da página ${item.pageNumber}`} fill unoptimized className="object-contain" /></span><span className="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={item.selected} onChange={(event) => setPages((current) => current.map((pageItem) => pageItem.pageNumber === item.pageNumber ? { ...pageItem, selected: event.target.checked } : pageItem))} />Página {item.pageNumber}</span><span className="mt-1 block text-[10px] text-muted-foreground">{Math.round(item.widthMm)} × {Math.round(item.heightMm)} mm · {item.orientation === "landscape" ? "Paisagem" : "Retrato"}</span></label>)}</div></section>
      <section aria-labelledby="aplicar-redimensionamento"><h2 id="aplicar-redimensionamento" className="font-heading text-lg font-medium">Aplicar configurações</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{[["all", "Todas as páginas"], ["selected", "Somente páginas selecionadas"], ["range", "Intervalo de páginas"]].map(([value, label]) => <label key={value} className="flex items-center gap-2 rounded-lg border border-border p-3 text-sm"><input type="radio" name="application" value={value} checked={application === value} onChange={() => setApplication(value as PageApplication)} />{label}</label>)}</div>{application === "range" && <div className="mt-3 flex flex-col gap-2 sm:flex-row"><label className="grid flex-1 gap-1 text-sm">Páginas<input value={range} onChange={(event) => setRange(event.target.value)} onBlur={applyRange} placeholder="Ex.: 1-5 ou 1,3,7" className="min-h-11 rounded-md border border-input bg-background px-3" /></label><Button variant="outline" className="sm:self-end" onClick={applyRange}>Aplicar intervalo</Button></div>}<ToolErrorMessage message={rangeError} /></section>
      {page && placement && <section aria-labelledby="previa-redimensionar"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="previa-redimensionar" className="font-heading text-lg font-medium">Pré-visualização</h2><p className="mt-1 text-sm text-muted-foreground">Página {page.pageNumber} · {targetSize} · {orientation === "original" ? page.orientation === "landscape" ? "Paisagem" : "Retrato" : orientation === "landscape" ? "Paisagem" : "Retrato"}</p></div><Select label="Visualização" value={previewMode} onChange={(value) => setPreviewMode(value as PreviewMode)} options={[["before", "Antes"], ["after", "Depois"], ["compare", "Comparar lado a lado"]]} /></div><div className={`mt-4 grid gap-5 ${previewMode === "compare" ? "sm:grid-cols-2" : "max-w-lg"}`}>{previewMode !== "after" && <PreviewOriginal page={page} />}{previewMode !== "before" && <PreviewAfter page={page} placement={placement} background={background} customColor={customColor} cropped={placement.cropped} />}</div></section>}
      <ToolErrorMessage message={error} /><ToolActionBar><Button size="lg" onClick={() => void convert()} disabled={status === "processing" || (application === "selected" && !selectedPages.length)}><Scaling className="size-4" />Redimensionar PDF</Button></ToolActionBar>
    </>}
    {result && status === "success" && <ToolResultCard title="PDF redimensionado" description={`${result.name} · ${result.format} · ${result.pages} ${result.pages === 1 ? "página alterada" : "páginas alteradas"} · ${formatFileSize(result.size)}`} actions={<><Button asChild><a href={resultUrl ?? undefined} download={result.name}><Download className="size-4" />Baixar PDF redimensionado</a></Button><Button variant="outline" onClick={() => { setResult(null); setStatus("ready"); }}><RefreshCw className="size-4" />Alterar configurações</Button><Button variant="outline" onClick={reset}><RotateCcw className="size-4" />Redimensionar outro PDF</Button></>} />}
  </CardContent></Card></ToolPageShell>;
}

function Notice({ children }: { children: React.ReactNode }) { return <div role="status" className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-4 text-sm text-amber-700 dark:text-amber-300">{children}</div>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][] }) { return <label className="grid gap-2 text-sm font-medium">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 rounded-md border border-input bg-background px-3 outline-none focus-visible:ring-2 focus-visible:ring-primary/30">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function PreviewOriginal({ page }: { page: ResizePageInfo }) { const scale = Math.min(0.48, 280 / page.widthPt); return <figure className="rounded-lg border border-border bg-muted/30 p-4"><div className="mx-auto relative overflow-hidden bg-white shadow" style={{ width: page.widthPt * scale, height: page.heightPt * scale }}><Image src={page.thumbnailUrl} alt="Página original" fill unoptimized className="object-fill" /></div><figcaption className="mt-3 text-center text-xs text-muted-foreground">Antes · {Math.round(page.widthMm)} × {Math.round(page.heightMm)} mm</figcaption></figure>; }
function PreviewAfter({ page, placement, background, customColor, cropped }: { page: ResizePageInfo; placement: NonNullable<ReturnType<typeof calculatePlacement>>; background: BackgroundMode; customColor: string; cropped: boolean }) { const scale = Math.min(0.48, 280 / placement.pageWidth); const bg = background === "black" ? "#000" : background === "custom" ? customColor : background === "transparent" ? "repeating-conic-gradient(#ddd 0 25%, #fff 0 50%) 0/12px 12px" : "#fff"; return <figure className="rounded-lg border border-border bg-muted/30 p-4"><div className="relative mx-auto overflow-hidden shadow" style={{ width: placement.pageWidth * scale, height: placement.pageHeight * scale, background: bg }}><div className="absolute overflow-hidden" style={{ left: placement.x * scale, bottom: placement.y * scale, width: placement.width * scale, height: placement.height * scale }}><Image src={page.thumbnailUrl} alt="Página redimensionada" fill unoptimized className="object-fill" /></div>{cropped && <div className="pointer-events-none absolute inset-0 border-4 border-red-500/70" />}</div><figcaption className="mt-3 text-center text-xs text-muted-foreground">Depois · {Math.round(placement.pageWidth / 72 * 25.4)} × {Math.round(placement.pageHeight / 72 * 25.4)} mm{cropped ? " · área de corte sinalizada" : ""}</figcaption></figure>; }
