import type { PDFDocumentProxy } from "pdfjs-dist";
import { degrees, rgb } from "pdf-lib";

import { PDF_PAGE_SIZES, RESIZE_PDF_MAX_PAGES, mmToPoints, pointsToMm, type BackgroundMode, type PageMargins, type PdfTargetSize, type ResizeMode, type ResizeOrientation } from "./config";

export type ResizePageInfo = { pageNumber: number; widthPt: number; heightPt: number; widthMm: number; heightMm: number; rotation: number; orientation: "portrait" | "landscape"; format: string; thumbnailUrl: string; selected: boolean };
export type ResizePdfInspection = { document: PDFDocumentProxy; bytes: Uint8Array; pages: ResizePageInfo[]; mixedSizes: boolean };
export type ResizeOptions = { targetSize: PdfTargetSize; orientation: ResizeOrientation; mode: ResizeMode; margins: PageMargins; background: BackgroundMode; customColor: string; pageNumbers: number[] };
export type Placement = { pageWidth: number; pageHeight: number; sourceWidth: number; sourceHeight: number; x: number; y: number; width: number; height: number; cropped: boolean };

function resizeError(code: string) { return new Error(code); }
function formatName(widthMm: number, heightMm: number) { const tolerance = 2; for (const [name, size] of Object.entries(PDF_PAGE_SIZES)) if ((Math.abs(widthMm - size.widthMm) <= tolerance && Math.abs(heightMm - size.heightMm) <= tolerance) || (Math.abs(widthMm - size.heightMm) <= tolerance && Math.abs(heightMm - size.widthMm) <= tolerance)) return name; return "personalizado"; }
async function toBlob(canvas: HTMLCanvasElement) { return new Promise<Blob>((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(resizeError("render-failed")), "image/jpeg", 0.76)); }

export async function inspectResizePdf(file: File, onStage: (stage: string) => void): Promise<ResizePdfInspection> {
  if (new TextDecoder("ascii").decode(await file.slice(0, 5).arrayBuffer()) !== "%PDF-") throw resizeError("invalid-pdf");
  const bytes = new Uint8Array(await file.arrayBuffer()); const pdfjs = await import("pdfjs-dist"); pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.min.mjs", import.meta.url).toString(); let document: PDFDocumentProxy;
  try { document = await pdfjs.getDocument({ data: bytes.slice(), enableXfa: false }).promise; } catch (error) { if (error instanceof Error && /password/i.test(`${error.name} ${error.message}`)) throw resizeError("protected-pdf"); throw resizeError("corrupt-pdf"); }
  if (document.numPages > RESIZE_PDF_MAX_PAGES) { await document.cleanup(); throw resizeError("too-many-pages"); }
  onStage("Analisando as páginas"); const pages: ResizePageInfo[] = [];
  for (let index = 1; index <= document.numPages; index++) { const page = await document.getPage(index); const natural = page.getViewport({ scale: 1 }); if (!natural.width || !natural.height) throw resizeError("invalid-dimensions"); const widthMm = pointsToMm(natural.width); const heightMm = pointsToMm(natural.height); const thumb = page.getViewport({ scale: Math.min(0.35, 220 / natural.width) }); const canvas = window.document.createElement("canvas"); canvas.width = Math.ceil(thumb.width); canvas.height = Math.ceil(thumb.height); const context = canvas.getContext("2d", { alpha: false }); if (!context) throw resizeError("render-failed"); await page.render({ canvas, canvasContext: context, viewport: thumb, background: "white" }).promise; const blob = await toBlob(canvas); pages.push({ pageNumber: index, widthPt: natural.width, heightPt: natural.height, widthMm, heightMm, rotation: natural.rotation, orientation: natural.width >= natural.height ? "landscape" : "portrait", format: formatName(widthMm, heightMm), thumbnailUrl: URL.createObjectURL(blob), selected: true }); canvas.width = 1; canvas.height = 1; page.cleanup(); }
  const first = pages[0]; const mixedSizes = pages.some((page) => Math.abs(page.widthPt - first.widthPt) > 1 || Math.abs(page.heightPt - first.heightPt) > 1); return { document, bytes, pages, mixedSizes };
}
export function disposeResizeInspection(inspection: ResizePdfInspection | null) { inspection?.pages.forEach((page) => URL.revokeObjectURL(page.thumbnailUrl)); void inspection?.document.cleanup(); }

export function calculatePlacement(page: ResizePageInfo, options: Omit<ResizeOptions, "pageNumbers">): Placement {
  const size = PDF_PAGE_SIZES[options.targetSize]; const keepLandscape = options.orientation === "original" ? page.orientation === "landscape" : options.orientation === "landscape"; const pageWidth = mmToPoints(keepLandscape ? size.heightMm : size.widthMm); const pageHeight = mmToPoints(keepLandscape ? size.widthMm : size.heightMm); const availableWidth = pageWidth - mmToPoints(options.margins.left + options.margins.right); const availableHeight = pageHeight - mmToPoints(options.margins.top + options.margins.bottom); if (availableWidth <= 5 || availableHeight <= 5) throw resizeError("invalid-margins");
  const sourceWidth = page.widthPt; const sourceHeight = page.heightPt; let width = sourceWidth; let height = sourceHeight;
  if (options.mode === "fit") { const scale = Math.min(availableWidth / sourceWidth, availableHeight / sourceHeight); width *= scale; height *= scale; }
  if (options.mode === "fill") { const scale = Math.max(availableWidth / sourceWidth, availableHeight / sourceHeight); width *= scale; height *= scale; }
  if (options.mode === "stretch") { width = availableWidth; height = availableHeight; }
  const x = mmToPoints(options.margins.left) + (availableWidth - width) / 2; const y = mmToPoints(options.margins.bottom) + (availableHeight - height) / 2; return { pageWidth, pageHeight, sourceWidth, sourceHeight, x, y, width, height, cropped: x < mmToPoints(options.margins.left) - 0.1 || y < mmToPoints(options.margins.bottom) - 0.1 || x + width > pageWidth - mmToPoints(options.margins.right) + 0.1 || y + height > pageHeight - mmToPoints(options.margins.top) + 0.1 };
}

function hex(value: string) { const safe = /^#[0-9a-f]{6}$/i.test(value) ? value.slice(1) : "ffffff"; return rgb(parseInt(safe.slice(0, 2), 16) / 255, parseInt(safe.slice(2, 4), 16) / 255, parseInt(safe.slice(4, 6), 16) / 255); }

export async function resizePdf(bytes: Uint8Array, pagesInfo: ResizePageInfo[], options: ResizeOptions, onStage: (stage: string) => void) {
  const { PDFDocument } = await import("pdf-lib"); let source; try { source = await PDFDocument.load(bytes.slice(), { ignoreEncryption: false, updateMetadata: false }); } catch { throw resizeError("protected-pdf"); } const output = await PDFDocument.create(); output.setProducer("Kivai"); onStage("Aplicando o novo tamanho");
  for (let index = 0; index < pagesInfo.length; index++) { const info = pagesInfo[index]; if (!options.pageNumbers.includes(info.pageNumber)) { const [copied] = await output.copyPages(source, [index]); output.addPage(copied); continue; } const placement = calculatePlacement(info, options); const page = output.addPage([placement.pageWidth, placement.pageHeight]); if (options.background !== "transparent") page.drawRectangle({ x: 0, y: 0, width: placement.pageWidth, height: placement.pageHeight, color: options.background === "black" ? rgb(0, 0, 0) : options.background === "custom" ? hex(options.customColor) : rgb(1, 1, 1) }); const embedded = await output.embedPage(source.getPage(index)); onStage(`Processando página ${index + 1} de ${pagesInfo.length}`); const rotation = ((info.rotation % 360) + 360) % 360; if (rotation === 90) page.drawPage(embedded, { x: placement.x + placement.width, y: placement.y, width: placement.height, height: placement.width, rotate: degrees(90) }); else if (rotation === 180) page.drawPage(embedded, { x: placement.x + placement.width, y: placement.y + placement.height, width: placement.width, height: placement.height, rotate: degrees(180) }); else if (rotation === 270) page.drawPage(embedded, { x: placement.x, y: placement.y + placement.height, width: placement.height, height: placement.width, rotate: degrees(270) }); else page.drawPage(embedded, { x: placement.x, y: placement.y, width: placement.width, height: placement.height }); }
  onStage("Gerando o PDF"); const result = await output.save({ useObjectStreams: true, addDefaultPage: false }); onStage("Finalizando o arquivo"); return new Blob([result as BlobPart], { type: "application/pdf" });
}

export function parsePageRange(value: string, count: number) { const normalized = value.trim(); if (!normalized) return null; const pages = new Set<number>(); for (const part of normalized.split(",")) { const match = /^(\d+)(?:-(\d+))?$/.exec(part.trim()); if (!match) throw resizeError("invalid-range"); const start = Number(match[1]); const end = Number(match[2] ?? match[1]); if (start < 1 || end < start || end > count) throw resizeError("invalid-range"); for (let page = start; page <= end; page++) pages.add(page); } return [...pages].sort((a, b) => a - b); }
