export const adicionarMarcaDaguaEditorial = {
  overview: [
    "A ferramenta Adicionar Marca d'Água cria uma nova versão da imagem com um texto ou uma logo sobreposta. A marca pode ser movida diretamente na prévia, redimensionada pela alça de ajuste e configurada com diferentes níveis de opacidade antes do download.",
    "A imagem principal e a logo podem ser arquivos PNG, JPG ou WebP. A composição final mantém a largura e a altura da imagem principal e é exportada em PNG. O arquivo original não é substituído pela ferramenta.",
    "No modo Texto, a frase digitada é renderizada em branco, em negrito e com contorno escuro para aumentar a leitura sobre diferentes fundos. Nesta versão não há escolha de fonte, cor do texto ou repetição automática da marca por toda a imagem.",
    "Uma marca d'água visível pode identificar autoria, marca, origem ou contexto de uso, mas não impede cópias, capturas de tela, recortes ou edições posteriores. Ela deve ser tratada como elemento visual de identificação, não como mecanismo de proteção técnica do arquivo.",
  ],
  useCases: [
    { title: "Identificação de fotografias", description: "Inclua um nome, assinatura ou marca visual em imagens antes de publicá-las ou compartilhá-las." },
    { title: "Produtos e catálogos", description: "Acrescente a logo de uma loja ou negócio sobre fotografias usadas em vitrines, catálogos e materiais comerciais." },
    { title: "Prévia de materiais", description: "Marque imagens de demonstração, aprovação ou apresentação com um texto visível antes de enviar ao cliente ou equipe." },
    { title: "Conteúdo para redes sociais", description: "Posicione uma identificação discreta em fotos e artes mantendo controle visual sobre tamanho, posição e opacidade." },
  ],
  steps: [
    "Selecione uma imagem principal em PNG, JPG ou WebP.",
    "Escolha Texto ou Logo como tipo de marca d'água. No modo Texto, edite a frase; no modo Logo, selecione uma imagem PNG, JPG ou WebP.",
    "Ajuste a opacidade entre 10% e 100%.",
    "Arraste a marca sobre a prévia para mudar a posição e use a alça inferior direita para redimensionar. Também é possível movimentá-la com as setas do teclado.",
    "Confira a composição e baixe a nova imagem em PNG.",
  ],
  specifications: [
    { label: "Imagem principal", value: "PNG, JPG ou WebP." },
    { label: "Marca", value: "Texto digitado pelo usuário ou logo em PNG, JPG ou WebP." },
    { label: "Posicionamento", value: "Livre sobre a área da imagem, por arraste; também aceita movimentação pelas setas do teclado." },
    { label: "Tamanho", value: "Ajustável manualmente pela alça de redimensionamento." },
    { label: "Opacidade", value: "Ajustável de 10% a 100%." },
    { label: "Texto", value: "Renderizado em branco, negrito e com contorno escuro; não há seletor de fonte ou cor nesta versão." },
    { label: "Dimensões finais", value: "Mantém a largura e a altura da imagem principal." },
    { label: "Saída", value: "Arquivo PNG chamado imagem-com-marca-dagua.png." },
  ],
  privacy: "A imagem principal, a logo e a composição são manipuladas no navegador. A ferramenta cria a nova imagem no dispositivo e o arquivo só é salvo quando o usuário aciona o download. O original permanece separado e não é substituído pela cópia gerada.",
  limitations: [
    "A marca d'água é visual e não impede que outra pessoa recorte, cubra, edite ou capture a imagem.",
    "A saída é sempre PNG; não há opção de exportar diretamente em JPG ou WebP nesta ferramenta.",
    "O texto usa aparência fixa em branco com contorno escuro. Não existem controles de fonte, cor, alinhamento avançado ou efeitos adicionais.",
    "A ferramenta adiciona uma única marca por composição e não oferece repetição automática em padrão ou mosaico.",
    "No modo Logo, a qualidade visual depende do arquivo utilizado. Ampliar muito uma logo pequena pode deixá-la pixelada ou pouco nítida.",
    "Metadados e outras informações incorporadas ao arquivo original podem não permanecer na nova imagem PNG gerada pelo navegador.",
  ],
  faqs: [
    { question: "Posso usar texto ou uma logo?", answer: "Sim. A ferramenta possui dois modos: Texto e Logo. A logo precisa estar em PNG, JPG ou WebP." },
    { question: "Posso escolher a cor ou a fonte do texto?", answer: "Não nesta versão. O texto é gerado em branco, em negrito e com contorno escuro para manter contraste sobre a imagem." },
    { question: "Posso colocar a marca em qualquer lugar?", answer: "Sim, dentro dos limites da imagem. Arraste a marca na prévia ou use as setas do teclado para ajustar a posição." },
    { question: "É possível alterar o tamanho da marca?", answer: "Sim. Use a alça no canto inferior direito da marca selecionada para aumentar ou reduzir seu tamanho." },
    { question: "A marca d'água impede que copiem minha imagem?", answer: "Não. Ela funciona como identificação visual, mas não bloqueia capturas, recortes ou edições posteriores." },
    { question: "Qual formato é baixado?", answer: "A composição final é baixada em PNG e mantém as dimensões em pixels da imagem principal." },
    { question: "A imagem original é modificada?", answer: "Não. A ferramenta gera uma nova cópia para download e não substitui o arquivo original selecionado." },
  ],
  related: [
    { href: "/ferramentas/redimensionar-imagem", label: "Redimensionar imagem" },
    { href: "/ferramentas/recortar-imagem", label: "Recortar imagem" },
    { href: "/ferramentas/compressor-de-imagens", label: "Comprimir imagens" },
  ],
} as const;
