import type { BusinessServiceConfig } from "@/components/marketing/business-service-page";

const standardProcess = [
  {
    title: "Diagnóstico",
    description: "Entendimento do cenário atual, dos objetivos, das ferramentas disponíveis e das principais limitações.",
  },
  {
    title: "Definição do escopo",
    description: "Priorização das entregas, responsabilidades, acessos necessários e critérios de validação.",
  },
  {
    title: "Implementação",
    description: "Configuração ou construção da solução aprovada, com testes progressivos e documentação essencial.",
  },
  {
    title: "Validação e evolução",
    description: "Revisão conjunta, correções previstas no escopo e orientação para uso, acompanhamento ou próximos passos.",
  },
];

export const automationService: BusinessServiceConfig = {
  name: "Automação de Processos",
  pathname: "/servicos/automacao-de-processos",
  serviceType: "Automação de processos empresariais",
  audience: "Pequenas empresas, profissionais e equipes com tarefas operacionais repetitivas",
  badge: "Automação para pequenas empresas",
  headline: "Automação de processos para reduzir tarefas repetitivas e",
  headlineHighlight: "organizar sua operação.",
  introduction:
    "Planejamento e implementação de automações entre formulários, planilhas, CRM, WhatsApp e outras plataformas para simplificar rotinas, movimentar informações e apoiar decisões.",
  highlights: ["Integração entre ferramentas", "Fluxos sob medida", "Análise de viabilidade"],
  whatsappMessage: "Quero mais informações sobre o serviço de Automação de Processos.",
  deliverables: {
    eyebrow: "O que pode ser automatizado",
    title: "Fluxos mais organizados, com menos",
    titleHighlight: "trabalho manual.",
    description:
      "O escopo é definido a partir do processo real, dos acessos disponíveis e das integrações oferecidas por cada plataforma.",
    items: [
      { title: "Integração entre sistemas", description: "Conexão de ferramentas compatíveis para transportar dados e acionar etapas de um fluxo." },
      { title: "Automação de tarefas", description: "Rotinas para reduzir cópias manuais, atualizações repetitivas e esquecimentos operacionais." },
      { title: "Relatórios automáticos", description: "Consolidação e distribuição recorrente de informações relevantes para acompanhamento." },
      { title: "Notificações e alertas", description: "Avisos relacionados a novos registros, alterações, prazos ou condições definidas no projeto." },
      { title: "Organização de dados", description: "Padronização, transferência e centralização de informações entre fontes compatíveis." },
      { title: "Fluxos conectados", description: "Formulários, planilhas, CRM, WhatsApp, APIs e ferramentas no-code combinados conforme a viabilidade." },
    ],
  },
  experience: {
    eyebrow: "Aplicação prática e visão de negócio",
    title: "Tecnologia orientada ao processo, não apenas à",
    titleHighlight: "ferramenta.",
    paragraphs: [
      "A experiência com marketing, e-commerce, análise de dados, Google Sheets e operação digital ajuda a identificar gargalos que afetam tempo, organização e qualidade da informação.",
      "Automações, APIs e integrações fazem parte de uma frente técnica em desenvolvimento e aplicação prática no Kivai e em projetos atuais, com escopo compatível com a solução que pode ser validada e entregue.",
    ],
    points: [
      "Leitura do processo antes da escolha da ferramenta.",
      "Experiência prática com planilhas, dados, marketing e e-commerce.",
      "Uso de Make, APIs, inteligência artificial e recursos no-code quando adequados.",
    ],
    note: "Integrações dependem dos recursos, APIs, planos e permissões de cada plataforma. Projetos envolvendo WhatsApp são avaliados conforme as opções oficiais disponíveis para a conta.",
  },
  process: standardProcess,
  seo: {
    eyebrow: "Serviço de automação de processos",
    title: "Automação empresarial para conectar informações e simplificar rotinas.",
    description: "O serviço transforma etapas manuais em fluxos estruturados, considerando a realidade operacional, as ferramentas já utilizadas e o retorno esperado para o negócio.",
    items: [
      { title: "Para quem é indicado", description: "Pequenas empresas, profissionais e equipes que repetem tarefas, mantêm dados dispersos ou perdem tempo transferindo informações entre ferramentas." },
      { title: "Entregas possíveis", description: "Mapeamento do fluxo, configuração da automação, integrações viáveis, testes, documentação essencial e orientação de uso." },
      { title: "Problemas que ajuda a resolver", description: "Retrabalho, falhas de atualização, avisos esquecidos, dados descentralizados e processos que dependem de muitas intervenções manuais." },
    ],
  },
  faqs: [
    { question: "Quais processos podem ser automatizados?", answer: "Tarefas repetitivas e baseadas em regras, como receber dados de formulários, atualizar planilhas ou CRM, emitir alertas e consolidar relatórios. A possibilidade depende das integrações de cada ferramenta." },
    { question: "É possível integrar planilhas, CRM e WhatsApp?", answer: "Sim, quando as plataformas, contas e APIs utilizadas oferecem os acessos necessários. O diagnóstico inicial confirma a viabilidade e o formato mais adequado." },
    { question: "Preciso trocar as ferramentas que já uso?", answer: "Nem sempre. A prioridade é avaliar o processo e aproveitar a estrutura existente quando ela é compatível. Caso haja uma limitação, as alternativas são apresentadas antes da implementação." },
    { question: "A automação elimina totalmente o trabalho manual?", answer: "Não necessariamente. Alguns fluxos ainda precisam de conferência, decisão humana ou tratamento de exceções. O objetivo é reduzir tarefas repetitivas e tornar o processo mais confiável." },
    { question: "Como é definido o orçamento?", answer: "O orçamento considera número de etapas, plataformas envolvidas, disponibilidade de APIs, volume de testes, documentação e necessidade de acompanhamento." },
  ],
  cta: {
    eyebrow: "Análise inicial do fluxo",
    title: "Tem uma rotina repetitiva que poderia ser",
    titleHighlight: "mais simples?",
    description: "Conte como o processo funciona hoje e quais ferramentas estão envolvidas para avaliarmos a viabilidade da automação.",
  },
};

export const googleLocalPresenceService: BusinessServiceConfig = {
  name: "Presença Local no Google",
  pathname: "/servicos/presenca-local-no-google",
  serviceType: "Criação e otimização do Perfil da Empresa no Google",
  audience: "Empresas locais, lojas, clínicas, prestadores de serviços e profissionais",
  badge: "Perfil da Empresa no Google",
  headline: "Presença local no Google para sua empresa ser",
  headlineHighlight: "encontrada e escolhida.",
  introduction: "Criação, organização e otimização do Perfil da Empresa no Google com informações, categorias, serviços, produtos, fotos, publicações e acompanhamento de desempenho.",
  highlights: ["Perfil organizado", "Informações consistentes", "Acompanhamento de desempenho"],
  whatsappMessage: "Quero mais informações sobre o serviço de Presença Local no Google.",
  deliverables: {
    eyebrow: "Perfil completo e confiável",
    title: "Informações que ajudam clientes a",
    titleHighlight: "encontrar seu negócio.",
    description: "O trabalho organiza os elementos que influenciam a apresentação da empresa nas buscas e no Google Maps.",
    items: [
      { title: "Criação ou revisão do perfil", description: "Configuração inicial ou diagnóstico de um perfil existente, conforme as regras e a elegibilidade do Google." },
      { title: "Categorias e informações", description: "Definição de categorias, descrição, contatos, horários e demais dados relevantes do estabelecimento." },
      { title: "Serviços e produtos", description: "Organização das soluções oferecidas para melhorar a compreensão do público sobre o negócio." },
      { title: "Fotos e conteúdo", description: "Orientação sobre imagens e planejamento de publicações úteis para manter o perfil atualizado." },
      { title: "Avaliações e reputação", description: "Boas práticas para solicitar, acompanhar e responder avaliações com consistência." },
      { title: "Desempenho do perfil", description: "Acompanhamento dos dados disponibilizados pelo Google para identificar buscas e interações." },
    ],
  },
  experience: {
    eyebrow: "Marketing aplicado ao negócio local",
    title: "Uma presença coerente com a jornada de quem",
    titleHighlight: "pesquisa perto de você.",
    paragraphs: [
      "A experiência em marketing digital, Google Ads e atendimento a clínicas e empresas locais contribui para organizar o perfil com foco nas dúvidas e ações reais do cliente.",
      "A estrutura combina clareza comercial, consistência de informações e leitura dos dados disponíveis, sem promessas artificiais de posição ou volume de contatos.",
    ],
    points: ["Experiência com campanhas locais e negócios de serviços.", "Textos e categorias alinhados ao que a empresa realmente oferece.", "Acompanhamento baseado nos dados fornecidos pelo Google."],
    note: "A aprovação, verificação, exibição e posição do perfil são controladas pelo Google. O serviço aplica boas práticas, mas não pode garantir primeira posição ou quantidade específica de contatos.",
  },
  process: standardProcess,
  seo: {
    eyebrow: "Otimização do Perfil da Empresa no Google",
    title: "Uma presença local completa para aparecer com mais clareza nas buscas.",
    description: "O serviço de presença local reúne organização do perfil, conteúdo, reputação e acompanhamento para fortalecer a forma como a empresa é apresentada no Google e no Maps.",
    items: [
      { title: "Para quem é indicado", description: "Lojas, clínicas, restaurantes, escritórios, prestadores de serviços e empresas que atendem uma cidade ou região específica." },
      { title: "Entregas do serviço", description: "Revisão do perfil, categorias, descrição, contatos, serviços, produtos, imagens, publicações, avaliações e análise de desempenho." },
      { title: "Problemas que ajuda a resolver", description: "Perfil incompleto, dados divergentes, categorias inadequadas, poucas informações sobre os serviços e ausência de rotina para reputação e conteúdo." },
    ],
  },
  faqs: [
    { question: "O que é o Perfil da Empresa no Google?", answer: "É a presença que pode exibir informações do negócio na Pesquisa Google e no Maps, como endereço ou área atendida, horário, telefone, serviços, fotos e avaliações." },
    { question: "O serviço serve para empresas sem loja física?", answer: "Pode servir para negócios que atendem no local do cliente, desde que sejam elegíveis conforme as diretrizes do Google. A configuração deve respeitar o modelo real de atendimento." },
    { question: "Vocês garantem a primeira posição no Google Maps?", answer: "Não. Nenhum prestador controla a posição orgânica. O trabalho melhora estrutura, consistência e manutenção do perfil, enquanto o resultado também depende de relevância, distância, concorrência e critérios do Google." },
    { question: "As avaliações podem ser gerenciadas?", answer: "O serviço pode incluir estratégia de solicitação e orientação de respostas. Avaliações não são compradas nem manipuladas; elas devem refletir experiências reais dos clientes." },
    { question: "É possível acompanhar os resultados?", answer: "Sim. Os dados disponibilizados pelo próprio Google podem ser acompanhados para observar buscas, visualizações e interações, respeitando as métricas disponíveis na plataforma." },
  ],
  cta: { eyebrow: "Fortaleça sua presença local", title: "Sua empresa está bem apresentada para quem pesquisa no", titleHighlight: "Google e no Maps?", description: "Solicite uma análise do perfil atual ou converse sobre a criação de uma presença local para o seu negócio." },
};

export const ecommerceConsultingService: BusinessServiceConfig = {
  name: "Consultoria para E-commerce",
  pathname: "/servicos/consultoria-para-e-commerce",
  serviceType: "Consultoria de gestão e marketing para e-commerce",
  audience: "Lojas virtuais, operações de marketplace e pequenos negócios digitais",
  badge: "Estratégia e operação de loja virtual",
  headline: "Consultoria para e-commerce com visão de operação, marketing e",
  headlineHighlight: "rentabilidade.",
  introduction: "Análise de catálogo, precificação, margem, conversão, marketplaces, estoque, marketing e indicadores para organizar decisões e identificar prioridades na loja virtual.",
  highlights: ["Visão comercial e operacional", "Decisões orientadas por dados", "Plano de prioridades"],
  whatsappMessage: "Quero mais informações sobre o serviço de Consultoria para E-commerce.",
  deliverables: {
    eyebrow: "Diagnóstico do comércio eletrônico",
    title: "Uma leitura integrada da loja para encontrar",
    titleHighlight: "gargalos e oportunidades.",
    description: "A consultoria parte dos dados e processos disponíveis para priorizar ações compatíveis com o momento do negócio.",
    items: [
      { title: "Operação e catálogo", description: "Revisão da organização de produtos, informações, rotinas e pontos que afetam a experiência de compra." },
      { title: "Precificação e margem", description: "Análise dos componentes de preço, custos, taxas e margem para apoiar decisões mais sustentáveis." },
      { title: "Conversão", description: "Avaliação de páginas, ofertas e jornada de compra para localizar possíveis obstáculos à decisão." },
      { title: "Marketplaces", description: "Leitura de presença, anúncios, custos e oportunidades nos canais em que a empresa atua ou pretende atuar." },
      { title: "Estoque e operação", description: "Organização dos dados e rotinas que conectam disponibilidade, pedidos e desempenho comercial." },
      { title: "Marketing e indicadores", description: "Análise de tráfego, campanhas e métricas essenciais para definir prioridades e acompanhar evolução." },
    ],
  },
  experience: {
    eyebrow: "Experiência real em e-commerce",
    title: "Decisões conectadas ao dia a dia de uma",
    titleHighlight: "operação digital.",
    paragraphs: [
      "A experiência inclui atuação como analista de e-commerce e a operação do Sou Ofertas Online, envolvendo catálogo, marketplaces, custos, margem, conversão, estoque, anúncios e acompanhamento de resultados.",
      "Essa vivência é combinada com marketing digital, Google Ads, Analytics, planilhas e planejamento para transformar dados dispersos em prioridades mais claras para o negócio.",
    ],
    points: ["Visão prática de catálogo, estoque e marketplaces.", "Análise de custos, margem, conversão e campanhas.", "Experiência com operação própria e tomada de decisão cotidiana."],
  },
  process: standardProcess,
  seo: {
    eyebrow: "Consultoria de e-commerce",
    title: "Estratégia para organizar a operação e melhorar a qualidade das decisões.",
    description: "A consultoria conecta gestão da loja virtual, desempenho comercial e marketing para identificar o que merece atenção primeiro e estruturar um plano viável.",
    items: [
      { title: "Para quem é indicada", description: "Lojas virtuais em implantação ou operação, pequenos e-commerces e vendedores de marketplaces que precisam organizar processos, números e prioridades." },
      { title: "Entregas da consultoria", description: "Diagnóstico, análise dos dados disponíveis, identificação de gargalos, recomendações priorizadas e direcionamento para acompanhamento." },
      { title: "Problemas que ajuda a resolver", description: "Margem pouco clara, catálogo desorganizado, baixa conversão, estoque sem leitura integrada, campanhas sem análise e decisões tomadas sem indicadores." },
    ],
  },
  faqs: [
    { question: "O que é analisado em uma consultoria para e-commerce?", answer: "Conforme o escopo, podem ser avaliados catálogo, operação, precificação, margem, estoque, marketplaces, tráfego, conversão, campanhas e indicadores." },
    { question: "A consultoria serve para uma loja que está começando?", answer: "Sim. Nesse caso, o foco pode estar na estrutura inicial, definição de prioridades, catálogo, canais, custos e indicadores que precisam ser acompanhados desde o início." },
    { question: "Vocês implementam as recomendações?", answer: "A consultoria pode ser contratada apenas para diagnóstico e plano de ação ou combinada com serviços de implantação, marketing, loja virtual, dashboards e automações, conforme o orçamento aprovado." },
    { question: "Quais dados preciso disponibilizar?", answer: "A lista depende do objetivo, mas pode incluir vendas, produtos, custos, estoque, campanhas, Analytics e relatórios de marketplaces. A análise respeita o acesso e a qualidade dos dados disponíveis." },
    { question: "Existe garantia de aumento nas vendas?", answer: "Não. A consultoria melhora a qualidade da análise e das decisões, mas vendas dependem de mercado, oferta, preço, execução, concorrência, investimento e outros fatores fora do controle do serviço." },
  ],
  cta: { eyebrow: "Diagnóstico para sua loja", title: "Quer entender onde estão os principais gargalos do seu", titleHighlight: "e-commerce?", description: "Apresente o momento da sua operação e receba uma proposta de análise compatível com seus objetivos e dados disponíveis." },
};

export const virtualStoreService: BusinessServiceConfig = {
  name: "Criação de Loja Virtual",
  pathname: "/servicos/criacao-de-loja-virtual",
  serviceType: "Criação e configuração de loja virtual",
  audience: "Empresas, marcas e profissionais que desejam vender pela internet",
  badge: "Implantação de e-commerce",
  headline: "Criação de loja virtual com estrutura para vender, medir e",
  headlineHighlight: "evoluir.",
  introduction: "Implantação e configuração de e-commerce com catálogo, pagamentos, integrações, Analytics, pixels e Google Merchant Center conforme a plataforma e as necessidades do projeto.",
  highlights: ["Configuração orientada ao negócio", "Métricas essenciais", "Integrações viáveis"],
  whatsappMessage: "Quero mais informações sobre o serviço de Criação de Loja Virtual.",
  deliverables: {
    eyebrow: "Estrutura da loja virtual",
    title: "Os componentes essenciais para começar a vender com",
    titleHighlight: "mais organização.",
    description: "A implantação é planejada de acordo com produtos, operação, plataforma escolhida, meios de pagamento e capacidade de manutenção da empresa.",
    items: [
      { title: "Implantação e configuração", description: "Estrutura inicial da plataforma, identidade básica, navegação e configurações compatíveis com o projeto." },
      { title: "Catálogo de produtos", description: "Organização de categorias, produtos, variações e informações fornecidas pela empresa dentro do escopo." },
      { title: "Pagamentos e entrega", description: "Configuração dos recursos suportados pela plataforma e pelos provedores contratados pelo cliente." },
      { title: "Integrações", description: "Conexão com ferramentas disponíveis para a plataforma, após análise de compatibilidade e acessos." },
      { title: "Analytics e pixels", description: "Configuração das medições acordadas para acompanhar acesso, comportamento e ações relevantes." },
      { title: "Google Merchant Center", description: "Apoio na configuração do catálogo para o Google, sujeito às políticas, aprovações e requisitos da plataforma." },
    ],
  },
  experience: {
    eyebrow: "Loja pensada por quem conhece a operação",
    title: "Além da página: catálogo, dados e rotina de",
    titleHighlight: "vendas online.",
    paragraphs: [
      "A experiência como analista de e-commerce e na gestão do Sou Ofertas Online acrescenta uma visão prática sobre catálogo, marketplaces, estoque, custos, conversão e campanhas.",
      "O projeto também considera a experiência em marketing digital, landing pages, Google Analytics e planejamento, conectando a implantação técnica às necessidades comerciais da loja.",
    ],
    points: ["Estrutura pensada para a operação que virá depois do lançamento.", "Configuração de medição para apoiar decisões futuras.", "Escopo adequado ao catálogo, à plataforma e à equipe disponível."],
    note: "Contas, assinaturas, taxas de plataforma, meios de pagamento, domínio, aplicativos e aprovações de terceiros não estão incluídos automaticamente e são definidos na proposta.",
  },
  process: standardProcess,
  seo: {
    eyebrow: "Desenvolvimento de loja virtual",
    title: "Um e-commerce configurado para apresentar produtos e acompanhar resultados.",
    description: "O serviço reúne planejamento, implantação, catálogo, pagamentos, integrações e dados em uma estrutura adequada ao estágio e à operação da empresa.",
    items: [
      { title: "Para quem é indicado", description: "Empresas, marcas e profissionais que desejam lançar uma loja virtual ou reorganizar uma estrutura existente em plataforma compatível." },
      { title: "Entregas possíveis", description: "Configuração da loja, páginas essenciais, catálogo acordado, pagamentos, entrega, integrações, Analytics, pixels e Merchant Center." },
      { title: "Problemas que ajuda a resolver", description: "Venda online sem estrutura própria, catálogo confuso, ausência de medição e dificuldade para conectar elementos essenciais da operação digital." },
    ],
  },
  faqs: [
    { question: "Qual plataforma é usada para criar a loja virtual?", answer: "A escolha depende do catálogo, orçamento, integrações, operação e facilidade de manutenção. A recomendação é feita depois do diagnóstico, sem impor uma única plataforma para todos os projetos." },
    { question: "O cadastro de produtos está incluído?", answer: "Pode ser incluído até a quantidade definida na proposta. A empresa precisa fornecer textos, preços, imagens, estoque, dimensões e demais informações necessárias." },
    { question: "A loja terá meios de pagamento e cálculo de frete?", answer: "Esses recursos podem ser configurados quando compatíveis com a plataforma e com os provedores escolhidos. Contratos, taxas e aprovações pertencem às respectivas empresas." },
    { question: "Analytics, pixels e Merchant Center estão incluídos?", answer: "Podem fazer parte do projeto conforme o escopo e a viabilidade técnica. A aprovação de produtos e contas no Merchant Center depende das políticas e análises do Google." },
    { question: "A criação da loja inclui marketing e gestão contínua?", answer: "Não automaticamente. Tráfego pago, SEO, Social Media, consultoria e manutenção podem ser contratados separadamente ou combinados em uma proposta." },
  ],
  cta: { eyebrow: "Planeje sua loja virtual", title: "Vamos estruturar um e-commerce compatível com o seu", titleHighlight: "momento de negócio?", description: "Conte o que você vende, o tamanho do catálogo e como funciona sua operação para receber uma proposta adequada." },
};

export const localSeoService: BusinessServiceConfig = {
  name: "SEO Local",
  pathname: "/servicos/seo-local",
  serviceType: "Otimização de sites para buscas locais",
  audience: "Empresas e profissionais que atendem cidades, bairros ou regiões específicas",
  badge: "Otimização para buscas locais",
  headline: "SEO local para fortalecer sua presença nas buscas da",
  headlineHighlight: "sua região.",
  introduction: "Estratégia de otimização para empresas locais com estrutura de páginas, palavras-chave geográficas, presença no Google, reputação, avaliações e acompanhamento de posicionamento.",
  highlights: ["Páginas locais", "Palavras-chave relevantes", "Monitoramento de evolução"],
  whatsappMessage: "Quero mais informações sobre o serviço de SEO Local.",
  deliverables: {
    eyebrow: "Estratégia de busca local",
    title: "Site, conteúdo e reputação trabalhando para uma presença",
    titleHighlight: "mais relevante.",
    description: "As ações são priorizadas conforme serviços, localidades atendidas, concorrência e estrutura digital existente.",
    items: [
      { title: "Pesquisa de buscas locais", description: "Mapeamento de termos relacionados aos serviços, cidades, bairros e intenção comercial do público." },
      { title: "Estrutura de páginas", description: "Planejamento ou revisão de páginas relevantes para os serviços e regiões realmente atendidas." },
      { title: "Otimização de conteúdo", description: "Ajustes em títulos, textos, headings, links internos e informações que ajudam mecanismos e pessoas." },
      { title: "Presença no Google", description: "Alinhamento entre site, dados da empresa e Perfil da Empresa no Google quando aplicável." },
      { title: "Reputação e avaliações", description: "Orientação para fortalecer sinais legítimos de confiança e uma rotina ética de avaliações." },
      { title: "Acompanhamento", description: "Monitoramento de consultas, páginas, posicionamento e oportunidades com as ferramentas disponíveis." },
    ],
  },
  experience: {
    eyebrow: "SEO aplicado em projeto real",
    title: "Estrutura técnica e conteúdo conectados à",
    titleHighlight: "intenção de busca.",
    paragraphs: [
      "A experiência prática inclui a estruturação de SEO do próprio Kivai, com títulos, conteúdos, links internos, sitemap, dados estruturados, Google Search Console e Google Analytics.",
      "O histórico em Google Ads, marketing digital e atendimento a negócios locais ajuda a interpretar a intenção comercial por trás das buscas e a transformar termos em páginas úteis, sem conteúdo artificial ou localidades que a empresa não atende.",
    ],
    points: ["Experiência com Search Console, Analytics e arquitetura de conteúdo.", "Visão integrada entre busca orgânica, anúncios e jornada comercial.", "Otimizações sustentadas por boas práticas, sem promessas de posição garantida."],
    note: "SEO é um trabalho progressivo. Indexação, posição e tráfego dependem dos mecanismos de busca, da concorrência, da autoridade do domínio e da execução contínua.",
  },
  process: standardProcess,
  seo: {
    eyebrow: "Serviço de SEO local",
    title: "Otimização para empresas que precisam ser encontradas em uma cidade ou região.",
    description: "O SEO local organiza a presença digital para responder a buscas geográficas e comerciais com páginas úteis, informações consistentes e acompanhamento técnico.",
    items: [
      { title: "Para quem é indicado", description: "Clínicas, lojas, escritórios, prestadores de serviços e empresas que atendem públicos de localidades específicas." },
      { title: "Entregas do serviço", description: "Diagnóstico, palavras-chave locais, estrutura de páginas, otimizações on-page, links internos, dados estruturados aplicáveis e monitoramento." },
      { title: "Problemas que ajuda a resolver", description: "Site sem foco geográfico, páginas genéricas, serviços difíceis de encontrar, informações inconsistentes e ausência de acompanhamento de buscas orgânicas." },
    ],
  },
  faqs: [
    { question: "Qual é a diferença entre SEO local e presença no Google?", answer: "SEO local trabalha principalmente site, conteúdo, estrutura e sinais relacionados à região. A presença no Google foca o Perfil da Empresa. As duas frentes podem ser usadas em conjunto." },
    { question: "SEO local serve apenas para empresas com endereço físico?", answer: "Não. Prestadores que atendem em uma área específica também podem se beneficiar, desde que as páginas e informações representem localidades realmente atendidas e sigam as políticas aplicáveis." },
    { question: "Em quanto tempo aparecem os resultados?", answer: "Não há prazo fixo. Rastreamento, indexação e posicionamento dependem do Google, da concorrência, da situação do site e da consistência do trabalho. O acompanhamento permite observar a evolução ao longo do tempo." },
    { question: "É possível garantir a primeira posição?", answer: "Não. A posição é definida pelos mecanismos de busca e muda conforme diversos fatores. O serviço aplica boas práticas e melhora a qualidade da presença, mas não promete posições específicas." },
    { question: "O serviço inclui criação de páginas?", answer: "Pode incluir planejamento, conteúdo e implementação de páginas, dependendo da plataforma do site e do escopo contratado. A necessidade é definida no diagnóstico." },
  ],
  cta: { eyebrow: "Diagnóstico de busca local", title: "Sua empresa aparece para quem procura seus serviços na", titleHighlight: "região certa?", description: "Solicite uma análise da estrutura atual e das oportunidades de busca local para o seu negócio." },
};

export const dashboardsService: BusinessServiceConfig = {
  name: "Dashboards e Relatórios",
  pathname: "/servicos/dashboards-e-relatorios",
  serviceType: "Criação de dashboards e relatórios empresariais",
  audience: "Empresas e equipes de marketing, vendas, finanças e operação",
  badge: "Indicadores para decisões",
  headline: "Dashboards e relatórios para transformar dados em",
  headlineHighlight: "visão de negócio.",
  introduction: "Criação de painéis e relatórios para marketing, vendas, financeiro e operação, com indicadores personalizados, integração de fontes e atualização automatizada quando tecnicamente viável.",
  highlights: ["Indicadores personalizados", "Fontes integradas", "Leitura clara dos resultados"],
  whatsappMessage: "Quero mais informações sobre o serviço de Dashboards e Relatórios.",
  deliverables: {
    eyebrow: "Dados mais acessíveis",
    title: "Indicadores organizados para acompanhar o que realmente",
    titleHighlight: "importa.",
    description: "Cada painel é estruturado a partir das decisões que precisa apoiar, não apenas da quantidade de gráficos disponíveis.",
    items: [
      { title: "Marketing", description: "Campanhas, investimento, aquisição, comportamento e conversões conforme as fontes disponíveis." },
      { title: "Vendas", description: "Receita, pedidos, ticket, produtos, canais, metas e evolução comercial." },
      { title: "Financeiro", description: "Custos, margem, receitas e outros indicadores definidos com a empresa e baseados nos dados fornecidos." },
      { title: "Operação", description: "Estoque, pedidos, prazos, volume de atividades e métricas operacionais relevantes." },
      { title: "Fontes integradas", description: "Consolidação de planilhas, plataformas e APIs compatíveis em uma visão mais organizada." },
      { title: "Atualização automatizada", description: "Rotinas de atualização quando a fonte, a ferramenta e os acessos permitem uma integração confiável." },
    ],
  },
  experience: {
    eyebrow: "Análise antes da visualização",
    title: "Números organizados para responder perguntas",
    titleHighlight: "reais do negócio.",
    paragraphs: [
      "A experiência em e-commerce, marketing digital e Google Ads envolve análise recorrente de custos, margem, conversão, vendas, campanhas, estoque e desempenho de canais.",
      "O trabalho com Google Sheets, Analytics, Search Console e relatórios operacionais ajuda a definir indicadores úteis e uma apresentação que facilite acompanhamento, comparação e priorização.",
    ],
    points: ["Indicadores definidos a partir das decisões da empresa.", "Experiência prática com dados de marketing e e-commerce.", "Visão crítica sobre qualidade, origem e limitações dos dados."],
    note: "A precisão do painel depende da qualidade e consistência das fontes. Integrações e atualizações automáticas são confirmadas após análise técnica de acessos, APIs e limites das plataformas.",
  },
  process: standardProcess,
  seo: {
    eyebrow: "Criação de dashboards empresariais",
    title: "Painéis personalizados para acompanhar marketing, vendas, finanças e operação.",
    description: "O serviço organiza fontes e indicadores em dashboards e relatórios construídos para facilitar a leitura do desempenho e apoiar decisões recorrentes.",
    items: [
      { title: "Para quem é indicado", description: "Empresas e equipes que dependem de planilhas ou plataformas separadas e precisam acompanhar indicadores com mais clareza." },
      { title: "Entregas possíveis", description: "Mapeamento de métricas, preparação de dados, painel personalizado, integração viável, documentação e orientação de uso." },
      { title: "Problemas que ajuda a resolver", description: "Relatórios manuais, números divergentes, excesso de planilhas, dificuldade para comparar períodos e falta de visão integrada do negócio." },
    ],
  },
  faqs: [
    { question: "Quais áreas podem ter dashboards?", answer: "Marketing, vendas, financeiro, e-commerce, estoque e operação são exemplos. Os indicadores são definidos conforme as decisões e os dados disponíveis em cada negócio." },
    { question: "Quais fontes de dados podem ser integradas?", answer: "Planilhas, plataformas de anúncios, Analytics, sistemas e APIs podem ser considerados. A integração depende dos acessos, formatos e recursos oferecidos por cada fonte." },
    { question: "O dashboard atualiza automaticamente?", answer: "Pode atualizar quando as ferramentas e fontes permitem uma conexão estável. Quando isso não é possível, pode ser criada uma rotina de importação ou atualização orientada." },
    { question: "Vocês ajudam a escolher os indicadores?", answer: "Sim. O diagnóstico identifica perguntas, metas e decisões importantes para evitar um painel cheio de métricas que não geram ação." },
    { question: "É preciso organizar os dados antes?", answer: "Muitas vezes, sim. O projeto pode incluir etapas de padronização e preparação, mas inconsistências relevantes e reconstruções de histórico são avaliadas separadamente." },
  ],
  cta: { eyebrow: "Dados com contexto", title: "Quer acompanhar seus resultados sem depender de relatórios", titleHighlight: "dispersos e manuais?", description: "Conte quais números você acompanha e onde os dados estão para avaliarmos a melhor estrutura de dashboard." },
};

export const customSystemsService: BusinessServiceConfig = {
  name: "Sistemas e Automações Personalizadas",
  pathname: "/servicos/sistemas-e-automacoes-personalizadas",
  serviceType: "Desenvolvimento de sistemas web e automações personalizadas",
  audience: "Pequenas empresas e profissionais com processos que não se encaixam em ferramentas prontas",
  badge: "Soluções web sob medida",
  headline: "Sistemas e automações personalizadas para organizar processos",
  headlineHighlight: "do seu jeito.",
  introduction: "Planejamento e desenvolvimento de ferramentas web para controles internos, CRM simples, estoque, pedidos, leads, orçamentos, agendas e painéis administrativos, com escopo definido após análise técnica.",
  highlights: ["Solução orientada ao processo", "Escopo validado", "Evolução por etapas"],
  whatsappMessage: "Quero mais informações sobre o serviço de Sistemas e Automações Personalizadas.",
  deliverables: {
    eyebrow: "Ferramentas para sua rotina",
    title: "Uma solução específica quando o processo não cabe em um sistema",
    titleHighlight: "genérico.",
    description: "Os módulos são priorizados conforme impacto, complexidade, segurança, integrações e orçamento disponível.",
    items: [
      { title: "Sistemas internos", description: "Ferramentas web para centralizar dados, atividades e regras específicas da operação." },
      { title: "CRM simples", description: "Cadastro e acompanhamento de contatos, oportunidades e etapas comerciais essenciais." },
      { title: "Estoque e pedidos", description: "Controles adaptados à rotina para registrar movimentações, status e informações importantes." },
      { title: "Leads e orçamentos", description: "Fluxos para receber demandas, organizar contatos e acompanhar propostas comerciais." },
      { title: "Agendas e rotinas", description: "Recursos para registrar compromissos, solicitações, responsáveis e andamento de atividades." },
      { title: "Painéis administrativos", description: "Interfaces de gestão, consultas, filtros, permissões e indicadores definidos no projeto." },
    ],
  },
  experience: {
    eyebrow: "Produto digital em construção contínua",
    title: "Visão de negócio combinada com desenvolvimento",
    titleHighlight: "prático e responsável.",
    paragraphs: [
      "O Kivai é o principal projeto prático de produto e arquitetura digital, reunindo desenvolvimento web, organização de funcionalidades, testes, SEO, dados e evolução contínua da plataforma.",
      "A frente de programação, sistemas, banco de dados, APIs e integrações está em desenvolvimento profissional. Por isso, cada demanda passa por análise de viabilidade, definição clara de escopo e entrega progressiva, sem prometer uma solução que ainda não foi validada.",
    ],
    points: ["Compreensão de processos de marketing, vendas e e-commerce.", "Construção progressiva com validação antes da expansão.", "Possibilidade de combinar sistema, dashboard e automação no mesmo planejamento."],
    note: "Projetos críticos, integrações complexas, requisitos regulatórios, alta disponibilidade ou segurança avançada podem exigir especialistas adicionais. Essa necessidade é informada durante a análise, antes da contratação.",
  },
  process: standardProcess,
  seo: {
    eyebrow: "Desenvolvimento de sistema personalizado",
    title: "Ferramentas web sob medida para controles, dados e fluxos internos.",
    description: "O serviço parte do processo real da empresa para definir um sistema enxuto, evolutivo e compatível com as necessidades que ferramentas genéricas não atendem bem.",
    items: [
      { title: "Para quem é indicado", description: "Pequenas empresas e profissionais com controles dispersos, planilhas limitadas ou rotinas específicas que precisam de uma ferramenta própria." },
      { title: "Entregas possíveis", description: "Descoberta do processo, protótipo ou definição funcional, desenvolvimento dos módulos aprovados, testes, publicação e documentação essencial." },
      { title: "Problemas que ajuda a resolver", description: "Informações espalhadas, controles manuais, falta de histórico, dificuldade para acompanhar etapas e ferramentas prontas que não refletem a operação." },
    ],
  },
  faqs: [
    { question: "Que tipo de sistema personalizado pode ser criado?", answer: "Sistemas internos, CRM simples, controle de estoque ou pedidos, gestão de leads, orçamentos, agendas e painéis administrativos são possibilidades. A viabilidade depende dos requisitos e integrações." },
    { question: "Como o projeto começa?", answer: "Começa com uma conversa para mapear usuários, dados, regras, riscos e funcionalidades prioritárias. Depois é apresentado um escopo inicial, normalmente organizado em etapas." },
    { question: "É possível integrar o sistema a outras plataformas?", answer: "Sim, quando os serviços externos oferecem APIs ou mecanismos de integração adequados. Custos, permissões e limitações de terceiros são avaliados antes da implementação." },
    { question: "O sistema já inclui hospedagem e manutenção?", answer: "Esses itens são definidos na proposta. Hospedagem, domínio, serviços externos, suporte e evolução contínua podem ter custos recorrentes separados do desenvolvimento inicial." },
    { question: "Como são tratados segurança e acesso aos dados?", answer: "Os requisitos de autenticação, permissões, backup e proteção são definidos conforme o projeto. Demandas com dados sensíveis ou exigências avançadas podem precisar de infraestrutura ou especialistas adicionais." },
  ],
  cta: { eyebrow: "Análise de viabilidade", title: "Sua empresa precisa de uma ferramenta que ainda não encontrou", titleHighlight: "pronta no mercado?", description: "Explique o processo, os usuários e os controles necessários para avaliarmos uma solução possível e um primeiro escopo." },
};

export const businessServices = [
  automationService,
  googleLocalPresenceService,
  ecommerceConsultingService,
  virtualStoreService,
  localSeoService,
  dashboardsService,
  customSystemsService,
];
