export const imageToolEditorialOverrides = {
  "compressor-de-imagens": {
    overview: [
      "O Compressor de Imagens reduz o peso de arquivos JPG, PNG e WebP sem alterar suas dimensões. Em JPG e WebP, é possível escolher entre diferentes níveis de compressão; em PNG, a redução depende da estrutura do arquivo e mantém a transparência quando ela estiver presente.",
      "A ferramenta compara o arquivo original com o resultado e só utiliza a nova versão quando ela realmente ocupa menos espaço. Se o processamento não conseguir gerar uma versão menor, o Kivai mantém o arquivo original em vez de entregar uma cópia maior.",
    ],
    useCases: [
      { title: "Desempenho de páginas", description: "Reduza imagens de banners, artigos e vitrines para diminuir o volume transferido durante o carregamento." },
      { title: "Envio por e-mail", description: "Prepare anexos menores quando o provedor impõe limite de tamanho ou a conexão do destinatário é lenta." },
      { title: "Lojas e catálogos", description: "Otimize fotografias de produtos sem alterar o fluxo de publicação ou instalar um programa de edição." },
      { title: "WhatsApp e compartilhamento", description: "Reduza o peso de fotografias antes de enviar por aplicativos, formulários ou plataformas com limite de arquivo." },
    ],
    steps: [
      "Selecione uma imagem PNG, JPG ou WebP com até 5 MB.",
      "Escolha entre compressão Leve, Equilibrada ou Máxima.",
      "Clique em “Comprimir imagem” e compare o tamanho original com o resultado.",
      "Confira a prévia e faça o download da versão menor. Se não houver redução, a ferramenta mantém o arquivo original.",
    ],
    specifications: [
      { label: "Entrada", value: "PNG, JPG e WebP, com limite de 5 MB por arquivo." },
      { label: "Saída", value: "Imagem no mesmo formato do arquivo original: JPG, PNG ou WebP." },
      { label: "Dimensões", value: "Largura e altura originais são preservadas." },
      { label: "Controle principal", value: "Perfis Leve, Equilibrada e Máxima para JPG e WebP; em PNG, a redução funciona de forma diferente por usar compressão sem perdas." },
      { label: "Medição", value: "Comparação do tamanho original, tamanho final e percentual economizado." },
    ],
    privacy: "O navegador decodifica e recomprime a imagem localmente. O arquivo não é enviado para um serviço de compressão externo. A prévia utiliza um endereço temporário criado no dispositivo e deixa de existir quando a página é fechada ou quando outra imagem é selecionada.",
    limitations: [
      "Nos formatos JPG e WebP, níveis maiores de compressão podem reduzir nitidez, especialmente em textos pequenos, degradês e contornos.",
      "Em PNG, os níveis de qualidade não atuam da mesma forma porque o formato utiliza compressão sem perdas; a redução depende da estrutura do arquivo original.",
      "Uma imagem que já foi fortemente comprimida pode apresentar pouca economia adicional.",
      "Metadados incorporados podem não permanecer na cópia gerada; preserve o original quando essas informações forem importantes.",
      "Para sites, dimensões adequadas e carregamento responsivo são tão importantes quanto o peso final do arquivo.",
    ],
    faqs: [
      { question: "A compressão altera a largura e a altura?", answer: "Não. A ferramenta mantém as dimensões originais da imagem. Para mudar largura ou altura, use a ferramenta específica de redimensionamento." },
      { question: "Qual perfil devo escolher?", answer: "Para JPG e WebP, comece pela opção Equilibrada e confira a prévia. Use Leve quando quiser priorizar qualidade e Máxima quando o tamanho do arquivo for mais importante. Em PNG, a redução funciona de forma diferente porque o formato utiliza compressão sem perdas." },
      { question: "O que acontece se a imagem comprimida ficar maior?", answer: "A ferramenta compara o resultado com o arquivo original. Se não houver redução real, ela mantém o original em vez de entregar uma cópia maior." },
      { question: "É possível recuperar a qualidade perdida?", answer: "Não integralmente nos formatos que usam compressão com perdas. Por isso, mantenha o arquivo original quando ele for importante para edição, impressão ou arquivamento." },
      { question: "Os arquivos são enviados ao servidor?", answer: "Não. A leitura e a criação da nova imagem acontecem no navegador do usuário." },
      { question: "Comprimir melhora automaticamente o SEO?", answer: "Arquivos menores podem ajudar o carregamento, mas SEO também depende de conteúdo, dimensões adequadas, texto alternativo, estabilidade visual e outros fatores." },
    ],
    related: [
      { href: "/ferramentas/redimensionar-imagem", label: "Redimensionar imagem" },
      { href: "/ferramentas/conversor-de-imagens", label: "Converter imagens" },
      { href: "/ferramentas/gerador-de-placeholder", label: "Gerar placeholder" },
    ],
  },
  "conversor-de-imagens": {
    overview: [
      "O Conversor de Imagens transforma arquivos entre PNG, JPG e WebP mantendo a largura e a altura da imagem. Ele é útil quando um site, aplicativo, marketplace ou sistema exige um formato diferente daquele em que o arquivo foi criado.",
      "A conversão muda a forma como a imagem é armazenada, mas não tem como objetivo garantir um arquivo menor. Dependendo do conteúdo, do formato escolhido e da qualidade configurada, o resultado pode ficar menor, semelhante ou maior que o original. A própria ferramenta mostra essa variação depois da conversão.",
      "JPG e WebP permitem ajustar a qualidade de saída de 10% a 100%. PNG não exibe esse controle. Quando uma imagem com transparência é convertida para JPG, as áreas transparentes recebem fundo branco porque o formato JPG não suporta transparência.",
    ],
    useCases: [
      { title: "Compatibilidade com plataformas", description: "Converta a imagem quando um formulário, marketplace, editor ou sistema aceita apenas determinados formatos de arquivo." },
      { title: "Fotos para JPG", description: "Crie uma cópia em JPG para serviços e aplicações que não aceitam PNG ou WebP, com controle de qualidade da saída." },
      { title: "Imagens para WebP", description: "Gere uma versão WebP quando esse formato for adequado ao site, aplicação ou fluxo de publicação que você utiliza." },
      { title: "Preservação de transparência", description: "Escolha PNG quando a imagem precisa manter áreas transparentes, como logotipos, recortes e elementos gráficos." },
    ],
    steps: [
      "Selecione uma imagem PNG, JPG ou WebP com até 5 MB.",
      "Escolha PNG, JPG ou WebP como formato de saída.",
      "Se a saída for JPG ou WebP, ajuste a qualidade entre 10% e 100% conforme a sua necessidade.",
      "Clique em “Converter imagem”, confira a prévia, o tamanho final, as dimensões e a variação em relação ao arquivo original.",
      "Baixe a nova cópia no formato escolhido. O arquivo original permanece no dispositivo sem ser substituído.",
    ],
    specifications: [
      { label: "Entrada", value: "PNG, JPG/JPEG e WebP com até 5 MB." },
      { label: "Saída", value: "PNG, JPG ou WebP, conforme a escolha do usuário." },
      { label: "Dimensões", value: "A largura e a altura da imagem original são mantidas na conversão." },
      { label: "Qualidade", value: "Ajustável de 10% a 100% para saídas JPG e WebP; o controle não é exibido para PNG." },
      { label: "Transparência", value: "PNG pode preservar áreas transparentes. Ao gerar JPG, áreas transparentes são preenchidas com branco." },
      { label: "Comparação", value: "A ferramenta mostra tamanho original, tamanho convertido, dimensões e variação percentual do arquivo." },
    ],
    privacy: "A imagem é lida, convertida e preparada para download no próprio navegador. O arquivo original não é substituído pela ferramenta e a nova versão só é salva no dispositivo quando o usuário escolhe fazer o download.",
    limitations: [
      "Converter uma imagem não garante redução de tamanho. O arquivo final pode ficar menor, semelhante ou maior que o original.",
      "JPG não suporta transparência; ao converter uma imagem transparente para JPG, essas áreas recebem fundo branco.",
      "Ajustes menores de qualidade em JPG e WebP podem reduzir detalhes visuais, principalmente em textos pequenos, linhas finas e degradês.",
      "Converter para PNG não recupera transparência, nitidez ou informações que já não existem no arquivo de origem.",
      "Metadados, perfis de cor e outras informações incorporadas ao arquivo original podem não permanecer na nova cópia gerada pelo navegador.",
    ],
    faqs: [
      { question: "A conversão reduz o tamanho da imagem?", answer: "Não necessariamente. O tamanho final depende do conteúdo, do formato escolhido e, em JPG e WebP, da qualidade selecionada. A ferramenta mostra a variação depois do processamento." },
      { question: "A largura e a altura mudam?", answer: "Não. A conversão mantém as dimensões em pixels do arquivo de origem. Para alterar largura ou altura, use a ferramenta de redimensionamento." },
      { question: "O que acontece com a transparência ao converter para JPG?", answer: "JPG não suporta transparência. Por isso, as áreas transparentes recebem fundo branco na cópia convertida." },
      { question: "Qualidade 100% significa que o arquivo ficará idêntico ao original?", answer: "Não. O valor controla a codificação das saídas JPG e WebP, mas uma conversão continua recriando o arquivo em outro formato. O resultado pode ter tamanho, compressão e características diferentes do original." },
      { question: "Posso converter JPG para PNG e recuperar qualidade?", answer: "Não. A conversão muda o formato do arquivo, mas não recria detalhes que foram perdidos anteriormente no JPG." },
      { question: "O arquivo original é alterado?", answer: "Não. A ferramenta gera uma nova cópia para download e mantém o arquivo selecionado sem substituí-lo." },
    ],
    related: [
      { href: "/ferramentas/compressor-de-imagens", label: "Comprimir imagens" },
      { href: "/ferramentas/redimensionar-imagem", label: "Redimensionar imagem" },
      { href: "/ferramentas/conversor-heic", label: "Converter HEIC" },
    ],
  },
  "conversor-heic": {
    overview: [
      "O Conversor HEIC para JPG transforma arquivos HEIC e HEIF em uma nova imagem JPG. Ele é útil quando uma foto está em um formato que determinado site, editor, formulário ou aplicativo não consegue abrir ou aceitar diretamente.",
      "Nesta ferramenta, a saída é sempre JPG e a conversão usa qualidade fixa de 95%. Não há seletor de qualidade nem escolha de outro formato de saída. Depois do processamento, o Kivai mostra a imagem convertida, o tamanho do arquivo original, o tamanho do JPG e as dimensões da nova cópia.",
      "A conversão cria um novo arquivo e não substitui o HEIC ou HEIF selecionado. Como o resultado é JPG, características específicas do arquivo de origem podem não permanecer na nova cópia, e o tamanho final pode ser maior ou menor que o original.",
    ],
    useCases: [
      { title: "Sites e formulários", description: "Crie uma cópia em JPG quando uma plataforma não aceita arquivos HEIC ou HEIF." },
      { title: "Compartilhamento", description: "Converta a foto para JPG antes de enviar a alguém ou usar em um serviço que trabalha melhor com esse formato." },
      { title: "Edição em programas compatíveis com JPG", description: "Gere uma versão que possa ser aberta em editores ou sistemas que não oferecem suporte ao arquivo HEIC original." },
      { title: "Publicação na web", description: "Prepare uma cópia JPG para fluxos de publicação que exigem esse formato de imagem." },
    ],
    steps: [
      "Selecione um arquivo HEIC ou HEIF com até 20 MB.",
      "Confira o nome e o tamanho do arquivo selecionado. A prévia do HEIC pode não aparecer antes da conversão.",
      "Clique em “Converter para JPG” e aguarde o processamento.",
      "Confira a prévia do JPG, o tamanho do arquivo convertido e as dimensões exibidas pela ferramenta.",
      "Baixe a nova cópia em JPG. O arquivo HEIC ou HEIF original não é substituído.",
    ],
    specifications: [
      { label: "Entrada", value: "Arquivos HEIC ou HEIF com até 20 MB." },
      { label: "Saída", value: "Arquivo JPG." },
      { label: "Qualidade", value: "Conversão para JPEG com qualidade fixa de 95%." },
      { label: "Prévia", value: "Exibida depois da conversão em JPG; o arquivo HEIC pode não ter visualização nativa antes do processamento." },
      { label: "Informações exibidas", value: "Tamanho do arquivo original, tamanho do JPG convertido e dimensões da imagem resultante." },
    ],
    privacy: "A conversão é executada no navegador com os recursos carregados pela própria página. O arquivo selecionado é usado para gerar a nova cópia JPG e só é salvo no dispositivo quando o usuário aciona o download.",
    limitations: [
      "A ferramenta gera somente JPG; não há opção de saída em PNG, WebP ou outro formato.",
      "A qualidade da saída é fixa em 95% e não pode ser ajustada nesta versão.",
      "A conversão não garante redução de tamanho. O JPG pode ficar menor ou maior que o HEIC ou HEIF original.",
      "Recursos adicionais presentes em alguns arquivos HEIC ou HEIF, como sequências ou informações específicas do contêiner, podem não ser reproduzidos na cópia JPG.",
      "Metadados e outras informações incorporadas ao arquivo original podem não permanecer no JPG convertido.",
    ],
    faqs: [
      { question: "Posso escolher outro formato além de JPG?", answer: "Não nesta ferramenta. A saída atual é sempre JPG." },
      { question: "Posso alterar a qualidade da conversão?", answer: "Não. A ferramenta usa qualidade fixa de 95% para gerar o JPG." },
      { question: "Por que não aparece uma prévia antes de converter?", answer: "Arquivos HEIC e HEIF podem não ter visualização nativa no navegador. A prévia é exibida depois que a ferramenta gera a versão JPG." },
      { question: "O JPG ficará menor que o arquivo original?", answer: "Não é possível garantir. O tamanho final depende das características da imagem e da forma como o arquivo original foi codificado." },
      { question: "O arquivo original é apagado ou substituído?", answer: "Não. A ferramenta cria uma nova cópia em JPG para download e não substitui o arquivo selecionado." },
      { question: "A ferramenta aceita mais de uma imagem por vez?", answer: "Não. O fluxo atual trabalha com um arquivo HEIC ou HEIF por conversão." },
    ],
    related: [
      { href: "/ferramentas/conversor-de-imagens", label: "Converter imagens" },
      { href: "/ferramentas/compressor-de-imagens", label: "Comprimir imagens" },
      { href: "/ferramentas/redimensionar-imagem", label: "Redimensionar imagem" },
    ],
  },
  "gerador-de-qr-code": {
    overview: [
      "O Gerador de QR Code cria códigos para URL, texto, WhatsApp, telefone, e-mail e redes Wi-Fi. A pré-visualização é atualizada automaticamente conforme os dados e as configurações mudam, permitindo revisar o conteúdo antes do download.",
      "Para telefone e WhatsApp, o campo trabalha com números brasileiros de 10 ou 11 dígitos e acrescenta o código +55 ao destino. No WhatsApp, uma mensagem inicial opcional pode ser incorporada ao link; no e-mail, também é possível informar assunto e mensagem; no Wi-Fi, a ferramenta aceita WPA/WPA2/WPA3, WEP, rede sem senha e a indicação de rede oculta.",
      "Além do QR Code padrão, a ferramenta oferece as composições Chamada superior, Etiqueta lateral, Cartão de marca e Selo promocional. É possível alterar as cores, o tamanho do QR, a margem, o nível de correção de erro e o texto exibido na arte. O nome da marca pode ser usado nos modelos que possuem essa área, e uma logo opcional aparece especificamente no modelo Cartão de marca, fora da área ocupada pelo código.",
      "Os arquivos podem ser baixados em PNG ou SVG. Na exportação SVG atual, a composição é gravada em um contêiner SVG, mas o QR Code é incorporado como uma imagem rasterizada; por isso, não é correto tratá-lo como um QR totalmente vetorial ou garantir ampliação ilimitada sem perda.",
    ],
    useCases: [
      { title: "Links e páginas", description: "Transforme um endereço da web em QR Code para materiais impressos, apresentações, embalagens ou pontos de atendimento." },
      { title: "Atendimento por WhatsApp", description: "Crie um QR Code com número brasileiro e, se desejar, uma mensagem inicial pronta para abrir a conversa." },
      { title: "Contato e e-mail", description: "Gere atalhos para ligação telefônica ou composição de e-mail com destinatário, assunto e mensagem inicial." },
      { title: "Acesso a Wi-Fi", description: "Crie um código com nome da rede, tipo de segurança, senha quando aplicável e indicação de rede oculta." },
      { title: "Peças de divulgação", description: "Use as composições visuais para acrescentar chamada, marca e, no Cartão de marca, uma logo sem cobrir o QR Code." },
    ],
    steps: [
      "Escolha URL, Texto, WhatsApp, Telefone, E-mail ou Wi-Fi.",
      "Preencha os dados do tipo escolhido. Em Telefone e WhatsApp, informe o número brasileiro com DDD; o +55 é acrescentado automaticamente ao destino.",
      "Ajuste cor do QR Code, cor de fundo, tamanho entre 200 e 1.000 px, margem e nível de correção de erro.",
      "Se quiser uma peça visual, escolha entre Padrão, Chamada superior, Etiqueta lateral, Cartão de marca ou Selo promocional e edite o texto exibido. O nome da marca e a logo são usados apenas onde o modelo possui espaço para esses elementos.",
      "Teste a leitura na prévia e baixe a arte em PNG ou SVG. Também é possível copiar o conteúdo codificado para a área de transferência.",
    ],
    specifications: [
      { label: "Conteúdos", value: "URL, texto, WhatsApp, telefone, e-mail e Wi-Fi." },
      { label: "Telefone e WhatsApp", value: "Números brasileiros com DDD e 10 ou 11 dígitos; o código 55 é acrescentado automaticamente ao destino." },
      { label: "WhatsApp", value: "Mensagem inicial opcional incorporada ao link wa.me." },
      { label: "E-mail", value: "Destinatário obrigatório, com assunto e mensagem opcionais." },
      { label: "Wi-Fi", value: "WPA/WPA2/WPA3, WEP ou rede sem senha, com opção para indicar rede oculta." },
      { label: "Composições", value: "Padrão, Chamada superior, Etiqueta lateral, Cartão de marca e Selo promocional." },
      { label: "Logo", value: "Arquivo de imagem opcional exibido no modelo Cartão de marca, fora da área do QR Code." },
      { label: "Personalização", value: "Cor do código, cor de fundo, tamanho de 200 a 1.000 px, margem de 0 a 10 e níveis de correção L, M, Q e H." },
      { label: "Saídas", value: "PNG ou SVG. O SVG atual contém a composição em SVG com o QR Code incorporado como imagem rasterizada." },
      { label: "Prévia", value: "Gerada automaticamente quando há conteúdo válido para o tipo selecionado." },
    ],
    privacy: "A geração do QR Code acontece no navegador. Os dados informados são usados para montar o conteúdo e a imagem durante a sessão. Como qualquer QR Code pode expor o que foi codificado a quem o escanear, evite publicar senhas, mensagens privadas ou dados sensíveis em materiais de acesso público.",
    limitations: [
      "Telefone e WhatsApp estão configurados para números brasileiros; o +55 é acrescentado automaticamente e o campo aceita 10 ou 11 dígitos nacionais.",
      "O QR Code é estático. Se o endereço, número, mensagem, e-mail ou dados da rede mudarem, é necessário gerar um novo código.",
      "A ferramenta não verifica se URL, e-mail, telefone, conta de WhatsApp, rede Wi-Fi ou senha informados realmente existem ou estão corretos.",
      "Cores com pouco contraste, margem pequena, impressão reduzida ou alterações posteriores na arte podem dificultar ou impedir a leitura.",
      "A logo não é inserida no centro do QR Code. Na implementação atual, ela aparece somente no modelo Cartão de marca e fica fora da área do código.",
      "O arquivo SVG não transforma o QR Code em módulos vetoriais; o código permanece incorporado como imagem rasterizada dentro da composição SVG.",
    ],
    faqs: [
      { question: "Preciso digitar +55 no telefone ou WhatsApp?", answer: "Não. Informe o DDD e o número brasileiro. A ferramenta acrescenta 55 ao destino automaticamente e também remove o 55 inicial se ele tiver sido digitado junto com um número nacional válido." },
      { question: "Posso criar QR Code de Wi-Fi sem senha?", answer: "Sim. Selecione a opção Sem senha. Também é possível indicar que a rede é oculta." },
      { question: "A logo fica dentro do QR Code?", answer: "Não. A logo é exibida somente na composição Cartão de marca e fica fora da área ocupada pelo QR Code." },
      { question: "Os modelos mudam o conteúdo do QR Code?", answer: "Não. As composições alteram a apresentação visual ao redor do código. O conteúdo codificado continua sendo definido pelos dados do tipo selecionado." },
      { question: "O SVG é totalmente vetorial?", answer: "Não na implementação atual. A arte usa um contêiner SVG, mas o QR Code é incorporado como imagem rasterizada. Por isso, não há garantia de ampliação ilimitada sem perda." },
      { question: "O QR Code expira?", answer: "O código em si não possui prazo configurado pela ferramenta. Ele pode deixar de funcionar como esperado se o destino codificado for alterado, removido ou ficar indisponível." },
      { question: "Posso alterar o conteúdo depois de baixar?", answer: "Não. Como o QR Code é estático, qualquer mudança no destino exige gerar uma nova versão." },
      { question: "O que faz a correção de erro?", answer: "Ela ajusta a tolerância do QR Code a pequenas perdas ou interferências. A ferramenta oferece os níveis L, M, Q e H, mas ainda é importante manter contraste, margem e tamanho adequados e testar a leitura antes de publicar." },
    ],
    related: [
      { href: "/ferramentas/gerador-de-favicon", label: "Gerar favicon" },
      { href: "/ferramentas/conversor-svg-png", label: "Converter SVG e PNG" },
      { href: "/ferramentas/redimensionar-imagem", label: "Redimensionar imagem" },
    ],
  },
};
