import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Calculator,
  Combine,
  FileImage,
  ImagePlus,
  FileText,
  ImageIcon,
  Video,
  Maximize2,
  Minimize2,
  Percent,
  QrCode,
  RotateCw,
  Scissors,
  Tags,
  TrendingUp,
  Type,
  WandSparkles,
  Box,
  Crop,
  Stamp,
  FlipHorizontal,
  FileAudio,
  Gauge,
  Volume2,
} from "lucide-react";

export type ToolCategory =
  | "imagens"
  | "pdf"
  | "calculadoras"
  | "texto"
  | "social"
  | "video"
  | "audio"
  | "documentos"
  | "desenvolvimento"
  | "marketing"
  | "ecommerce"
  | "seo"
  | "ia"
  | "utilitarios";

export interface ToolCategoryDefinition {
  slug: ToolCategory;
  name: string;
  description: string;
  href: string;
  icon: LucideIcon;
}

export const toolCategories: ToolCategoryDefinition[] = [
  {
    slug: "imagens",
    name: "Imagens",
    description:
      "Remova fundo, converta formatos, comprima arquivos e use outras ferramentas para edição de imagens.",
    href: "/ferramentas/imagens",
    icon: ImageIcon,
  },
  {
    slug: "pdf",
    name: "PDFs",
    description:
      "Converta, organize, extraia imagens e use diversas ferramentas para arquivos PDF.",
    href: "/ferramentas/pdfs",
    icon: FileText,
  },
  {
    slug: "calculadoras",
    name: "Calculadoras",
    description:
      "Ferramentas para ROAS, ROI, margem, markup, desconto, porcentagem e muito mais.",
    href: "/ferramentas/calculadoras",
    icon: Calculator,
  },
  {
    slug: "texto",
    name: "Texto",
    description:
      "Conte palavras, caracteres, tempo de leitura e use outras ferramentas para textos.",
    href: "/ferramentas/texto",
    icon: Type,
  },
  { slug: "social", name: "Social Media", description: "Ferramentas para criar, revisar e otimizar conteúdos para redes sociais.", href: "/ferramentas/social-media", icon: Type },
  {
    slug: "video",
    name: "Vídeos",
    description:
      "Converta, edite e otimize vídeos diretamente no navegador com ferramentas rápidas, gratuitas e fáceis de usar.",
    href: "/ferramentas/videos",
    icon: Video,
  },
];

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  hubFilter: string;
  badge: string;
  icon: LucideIcon;
  featured?: boolean;
  available: boolean;
  index?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  keywords?: string[];
}

const socialMediaToolDefinitions: Tool[] = [
  ["baixar-thumbnail-youtube", "Baixar Thumbnail do YouTube", "YouTube", "Obtenha a thumbnail pública de um vídeo do YouTube.", ImageIcon],
  ["extrair-thumbnail-shorts", "Extrair Thumbnail de Shorts", "YouTube", "Encontre a thumbnail pública de um YouTube Short.", ImageIcon],
  ["simulador-de-bio-instagram", "Simulador de Bio Instagram", "Instagram", "Visualize uma bio de Instagram antes de publicar.", Type],
  ["gerador-de-link-na-bio-instagram", "Gerador de Link na Bio Instagram", "Instagram", "Crie links clicáveis para a bio e campanhas do Instagram.", QrCode],
  ["gerador-de-hashtags-instagram", "Gerador de Hashtags Instagram", "Instagram", "Monte uma lista de hashtags por categoria e objetivo.", Tags],
  ["gerador-de-hashtags-tiktok", "Gerador de Hashtags TikTok", "TikTok", "Gere hashtags TikTok com templates de conteúdo.", Tags],
  ["gerador-de-titulos-tiktok", "Gerador de Títulos TikTok", "TikTok", "Crie títulos curtos para vídeos TikTok com templates.", WandSparkles],
  ["contador-de-caracteres-facebook", "Contador de Caracteres Facebook", "Facebook", "Conte caracteres, palavras e linhas para posts do Facebook.", Type],
  ["gerador-de-descricao-facebook", "Gerador de Descrição Facebook", "Facebook", "Crie descrições para Facebook usando templates prontos.", WandSparkles],
  ["gerador-de-headline-linkedin", "Gerador de Headline LinkedIn", "LinkedIn", "Monte headlines profissionais para o LinkedIn.", WandSparkles],
  ["gerador-de-resumo-profissional-linkedin", "Gerador de Resumo Profissional LinkedIn", "LinkedIn", "Estruture um resumo profissional para seu perfil LinkedIn.", FileText],
  ["gerador-de-titulo-pinterest", "Gerador de Título Pinterest", "Pinterest", "Gere títulos claros e pesquisáveis para Pins.", WandSparkles],
  ["gerador-de-descricao-pinterest", "Gerador de Descrição Pinterest", "Pinterest", "Crie descrições para Pins a partir de templates.", WandSparkles],
  ["gerador-de-alt-text-pinterest", "Gerador de Alt Text Pinterest", "Pinterest", "Escreva textos alternativos descritivos para Pins.", Type],
  ["contador-de-caracteres-twitter", "Contador de Caracteres Twitter (X)", "Twitter (X)", "Acompanhe o limite de caracteres do seu post no X.", Type],
  ["gerador-de-mensagens-whatsapp", "Gerador de Mensagens WhatsApp", "WhatsApp", "Crie mensagens de WhatsApp com modelos prontos.", Type],
  ["gerador-de-convites-whatsapp", "Gerador de Convites WhatsApp", "WhatsApp", "Gere convites de WhatsApp para eventos e grupos.", Type],
  ["gerador-de-cta-whatsapp", "Gerador de CTA WhatsApp", "WhatsApp", "Crie chamadas para ação direcionadas ao WhatsApp.", Type],
  ["gerador-de-prompts", "Gerador de Prompts", "Conteúdo", "Monte prompts estruturados a partir de objetivo e contexto.", WandSparkles],
  ["gerador-de-emojis", "Gerador de Emojis", "Conteúdo", "Encontre combinações de emojis por tema e intenção.", WandSparkles],
  ["gerador-de-cta", "Gerador de CTA", "Conteúdo", "Crie chamadas para ação com templates por objetivo.", WandSparkles],
  ["gerador-de-titulos", "Gerador de Títulos", "Conteúdo", "Gere ideias de títulos usando modelos estáticos.", WandSparkles],
  ["gerador-de-descricoes", "Gerador de Descrições", "Conteúdo", "Crie descrições objetivas com templates de conteúdo.", WandSparkles],
  ["gerador-de-resumos", "Gerador de Resumos", "Conteúdo", "Estruture resumos curtos a partir de um texto no navegador.", FileText],
  ["gerador-de-palavras-chave", "Gerador de Palavras-chave", "Conteúdo", "Crie listas de palavras-chave por tema e intenção.", Tags],
  ["banco-de-datas-comemorativas", "Banco de Datas Comemorativas", "Conteúdo", "Consulte datas comemorativas para planejar seu conteúdo.", FileText],
  ["conversor-de-texto", "Conversor de Texto", "Texto", "Transforme, limpe e formate textos em poucos cliques.", Type],
  ["contador-de-tempo-de-leitura", "Contador de Tempo de Leitura", "Texto", "Estime o tempo de leitura de qualquer texto.", Type],
  ["contador-de-tempo-de-fala", "Contador de Tempo de Fala", "Texto", "Estime quanto tempo leva para falar um texto.", Type],
  ["calculadora-de-engajamento", "Calculadora de Engajamento", "Calculadoras", "Calcule a taxa de engajamento das suas publicações.", BarChart3],
  ["calculadora-de-cpm", "Calculadora de CPM", "Calculadoras", "Calcule o custo por mil impressões de uma campanha.", Calculator],
  ["calculadora-de-roi-influenciadores", "Calculadora de ROI para Influenciadores", "Calculadoras", "Estime o retorno sobre investimento em influenciadores.", Calculator],
  ["calculadora-de-alcance-estimado", "Calculadora de Alcance Estimado", "Calculadoras", "Estime o alcance a partir de seguidores e taxa de alcance.", BarChart3],
].map(([slug, name, hubFilter, description, icon]) => ({
  slug: String(slug), name: String(name), hubFilter: String(hubFilter), description: String(description), icon: icon as LucideIcon,
  category: "social" as const, badge: String(hubFilter), available: true, index: true,
  seoTitle: `${name} Online Grátis | Kivai`, seoDescription: String(description),
  keywords: [String(name).toLowerCase(), "ferramentas social media", "kivai"],
}));

export const tools: Tool[] = [
  { slug: "quebra-de-linha-instagram", name: "Quebra de Linha para Instagram", description: "Prepare legendas com quebras de linha prontas para copiar.", category: "social", hubFilter: "Instagram", badge: "Instagram", icon: Type, available: true, index: true, seoTitle: "Quebra de Linha para Instagram Online Grátis | Kivai", seoDescription: "Crie quebras de linha para legendas do Instagram e copie o texto pronto.", keywords: ["quebra de linha instagram", "legenda instagram", "formatar legenda"] },
  { slug: "contador-de-caracteres-instagram", name: "Contador de Caracteres Instagram", description: "Conte caracteres e acompanhe o limite da sua legenda.", category: "social", hubFilter: "Instagram", badge: "Instagram", icon: Type, available: true, index: true, seoTitle: "Contador de Caracteres Instagram Online Grátis | Kivai", seoDescription: "Conte caracteres de legendas do Instagram diretamente no navegador.", keywords: ["contador caracteres instagram", "limite legenda instagram"] },
  { slug: "contador-de-hashtags-instagram", name: "Contador de Hashtags Instagram", description: "Conte hashtags, palavras e caracteres da sua legenda.", category: "social", hubFilter: "Instagram", badge: "Instagram", icon: Tags, available: true, index: true, seoTitle: "Contador de Hashtags Instagram Online Grátis | Kivai", seoDescription: "Conte hashtags de uma legenda do Instagram e revise seu texto antes de publicar.", keywords: ["contador hashtags instagram", "hashtags instagram"] },
  {
    slug: "remover-audio-video",
    name: "Remover áudio",
    description: "Exporte uma versão silenciosa do vídeo em WebM.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Video,
    available: true,
    index: true,
    seoTitle: "Remover Áudio de Vídeo Online Grátis | Kivai",
    seoDescription: "Remova o áudio de vídeos diretamente no navegador e baixe a versão silenciosa em WebM.",
    keywords: ["remover áudio de vídeo", "silenciar vídeo", "tirar som do vídeo"],
  },
  {
    slug: "girar-video",
    name: "Girar vídeo",
    description: "Gire vídeos em 90°, 180° ou 270° e exporte em WebM.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: RotateCw,
    available: true,
    index: true,
    seoTitle: "Girar Vídeo Online Grátis | Kivai",
    seoDescription: "Gire vídeos diretamente no navegador e baixe o resultado em WebM.",
    keywords: ["girar vídeo", "rotacionar vídeo", "virar vídeo"],
  },
  {
    slug: "espelhar-video",
    name: "Espelhar vídeo",
    description: "Espelhe vídeos horizontalmente ou verticalmente e exporte em WebM.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: FlipHorizontal,
    available: true,
    index: true,
    seoTitle: "Espelhar Vídeo Online Grátis | Kivai",
    seoDescription: "Inverta vídeos horizontalmente ou verticalmente direto no navegador.",
    keywords: ["espelhar vídeo", "inverter vídeo", "flip vídeo"],
  },
  {
    slug: "recortar-video",
    name: "Recortar vídeo (Crop)",
    description: "Recorte a área visível de vídeos e exporte em WebM.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Crop,
    available: true,
    index: true,
    seoTitle: "Recortar Vídeo Online Grátis | Kivai",
    seoDescription:
      "Recorte vídeos online diretamente no navegador, ajuste a área da imagem e baixe o resultado em WebM.",
    keywords: ["recortar vídeo", "crop vídeo", "cortar área do vídeo"],
  },
  {
    slug: "capturar-frame-video",
    name: "Gerador de Thumbnail",
    description: "Crie thumbnails a partir de qualquer frame do vídeo.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: ImageIcon,
    available: true,
    index: true,
    seoTitle: "Gerador de Thumbnail para Vídeo Online Grátis | Kivai",
    seoDescription:
      "Capture frames de vídeos diretamente no navegador e baixe a imagem em PNG ou JPG sem enviar arquivos para servidores.",
    keywords: ["capturar frame de vídeo", "extrair imagem do vídeo", "frame para png"],
  },
  {
    slug: "alterar-volume-video",
    name: "Alterar volume do vídeo",
    description: "Aumente, reduza ou remova o áudio e exporte em WebM.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Volume2,
    available: true,
    index: true,
    seoTitle: "Alterar Volume do Vídeo Online Grátis | Kivai",
    seoDescription: "Ajuste o volume de um vídeo localmente no navegador e baixe a nova versão em WebM.",
    keywords: ["alterar volume vídeo", "aumentar som vídeo", "diminuir áudio vídeo"],
  },
  {
    slug: "ajustar-velocidade-video",
    name: "Ajustar velocidade do vídeo",
    description: "Acelere ou desacelere vídeos e exporte em WebM.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Gauge,
    available: true,
    index: true,
    seoTitle: "Ajustar Velocidade do Vídeo Online Grátis | Kivai",
    seoDescription: "Ajuste a velocidade de vídeos diretamente no navegador e baixe o resultado em WebM.",
    keywords: ["acelerar vídeo", "desacelerar vídeo", "velocidade vídeo"],
  },
  {
    slug: "video-para-audio",
    name: "Vídeo para áudio",
    description: "Extraia o áudio de um vídeo no formato WebM.",
    category: "video",
    hubFilter: "Converter",
    badge: "Áudio",
    icon: FileAudio,
    available: true,
    index: true,
    seoTitle: "Vídeo para Áudio Online Grátis | Kivai",
    seoDescription: "Extraia a trilha de áudio de vídeos localmente no navegador em WebM.",
    keywords: ["vídeo para áudio", "extrair áudio de vídeo", "converter vídeo áudio"],
  },
  {
    slug: "dividir-video",
    name: "Dividir vídeo",
    description: "Divida um vídeo em duas partes no ponto escolhido.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Scissors,
    available: true,
    index: true,
    seoTitle: "Dividir Vídeo Online Grátis | Kivai",
    seoDescription: "Divida vídeos em duas partes localmente no navegador e baixe cada trecho em WebM.",
    keywords: ["dividir vídeo", "cortar vídeo em partes", "separar vídeo"],
  },
  {
    slug: "redimensionar-video",
    name: "Redimensionar vídeo",
    description: "Altere a resolução sem distorcer, cortar ou preencher conforme preferir.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Maximize2,
    available: true,
    index: true,
    seoTitle: "Redimensionar Vídeo Online Grátis | Kivai",
    seoDescription: "Redimensione vídeos localmente com modos de ajustar, preencher ou esticar e exporte em WebM.",
    keywords: ["redimensionar vídeo", "alterar resolução vídeo", "dimensões vídeo"],
  },
  {
    slug: "removedor-de-fundo",
    name: "Removedor de Fundo",
    description: "Remova fundos de imagens para produtos, anúncios e projetos.",
    category: "imagens",
    hubFilter: "Otimizar",
    badge: "Imagem",
    icon: ImageIcon,
    featured: true,
    available: true,
    index: true,
    seoTitle: "Removedor de Fundo Online Grátis",
    seoDescription:
      "Remova o fundo de imagens automaticamente em segundos. Ferramenta online gratuita, rápida e sem necessidade de instalar programas.",
    keywords: [
      "removedor de fundo",
      "remover fundo de imagem",
      "apagar fundo de foto",
      "background remover",
      "remover fundo online",
    ],
  },
  {
    slug: "compressor-de-imagens",
    name: "Compressor de Imagens",
    description:
      "Reduza o tamanho de imagens JPG, PNG e WebP para sites, lojas e compartilhamento.",
    category: "imagens",
    hubFilter: "Otimizar",
    badge: "Imagem",
    icon: WandSparkles,
    featured: true,
    available: true,
    index: true,
  },
  {
    slug: "conversor-de-imagens",
    name: "Conversor de Imagens",
    description:
      "Converta arquivos entre PNG, JPG e WebP com controle de qualidade.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagem",
    icon: FileImage,
    featured: true,
    available: true,
    index: true,
  },
  {
    slug: "conversor-heic",
    name: "Conversor HEIC",
    description: "Converta fotos HEIC e HEIF do iPhone para JPG gratuitamente.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagem",
    icon: FileImage,
    available: true,
    index: true,
  },
  {
    slug: "redimensionar-imagem",
    name: "Redimensionar Imagem",
    description:
      "Altere largura e altura de imagens mantendo a qualidade e a proporção.",
    category: "imagens",
    hubFilter: "Otimizar",
    badge: "Imagem",
    icon: Maximize2,
    available: true,
    index: true,
  },
  {
    slug: "gerador-de-qr-code",
    name: "Gerador de QR Code",
    description:
      "Crie QR Codes para links, textos, WhatsApp, e-mail, telefone e Wi-Fi.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Utilidades",
    icon: QrCode,
    featured: true,
    available: true,
    index: true,
  },
  {
    slug: "gerador-de-favicon",
    name: "Gerador de Favicon",
    description:
      "Crie favicons para sites em tamanhos prontos para navegadores e dispositivos.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagem",
    icon: ImagePlus,
    available: true,
    index: true,
    seoTitle: "Gerador de Favicon Online Grátis | Kivai",
    seoDescription: "Crie favicon.ico e ícones PNG para seu site diretamente no navegador.",
    keywords: ["gerador de favicon", "favicon ico", "criar favicon"],
  },
  {
    slug: "imagem-para-favicon",
    name: "Imagem → Favicon",
    description:
      "Transforme uma imagem em favicon para usar no seu site.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagem",
    icon: ImageIcon,
    available: true,
    index: true,
    seoTitle: "Imagem para Favicon Online Grátis | Kivai",
    seoDescription: "Converta PNG, JPG e WebP em um pacote de favicons para navegador, Apple e Android.",
    keywords: ["imagem para favicon", "converter imagem favicon", "favicon png"],
  },
  {
    slug: "gerador-de-mockups",
    name: "Gerador de Mockups",
    description:
      "Apresente artes e marcas em mockups prontos para compartilhar.",
    category: "imagens",
    hubFilter: "Editar",
    badge: "Imagem",
    icon: Box,
    available: true,
    index: true,
    seoTitle: "Gerador de Mockups Online Grátis | Kivai",
    seoDescription: "Crie mockups de produtos, dispositivos e redes sociais diretamente no navegador.",
    keywords: ["gerador de mockups", "mockup online", "criar mockup"],
  },
  {
    slug: "recortar-imagem",
    name: "Recortar Imagem",
    description: "Recorte imagens com precisão diretamente no navegador.",
    category: "imagens",
    hubFilter: "Editar",
    badge: "Imagem",
    icon: Crop,
    available: true,
    index: true,
    seoTitle: "Recortar Imagem Online Grátis | Kivai",
    seoDescription: "Recorte imagens PNG, JPG e WebP online, sem enviar arquivos para servidores.",
    keywords: ["recortar imagem", "cortar foto", "crop imagem"],
  },
  {
    slug: "adicionar-marca-dagua",
    name: "Adicionar Marca d'Água",
    description: "Adicione texto como marca d'água às suas imagens.",
    category: "imagens",
    hubFilter: "Editar",
    badge: "Imagem",
    icon: Stamp,
    available: true,
    index: true,
    seoTitle: "Adicionar Marca d'Água Online Grátis | Kivai",
    seoDescription: "Adicione marcas d'água de texto às imagens diretamente no navegador.",
    keywords: ["marca d água", "marca dagua imagem", "proteger foto"],
  },
  {
    slug: "espelhar-e-girar-imagem",
    name: "Espelhar e Girar Imagem",
    description: "Gire e espelhe imagens em poucos cliques.",
    category: "imagens",
    hubFilter: "Editar",
    badge: "Imagem",
    icon: FlipHorizontal,
    available: true,
    index: true,
    seoTitle: "Espelhar e Girar Imagem Online Grátis | Kivai",
    seoDescription: "Gire e espelhe arquivos PNG, JPG e WebP diretamente no navegador.",
    keywords: ["girar imagem", "espelhar imagem", "rotacionar foto"],
  },
  {
    slug: "conversor-svg-png",
    name: "Conversor SVG ↔ PNG",
    description: "Converta SVG para PNG ou encapsule imagens em SVG.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagem",
    icon: FileImage,
    available: true,
    index: true,
    seoTitle: "Conversor SVG para PNG Online Grátis | Kivai",
    seoDescription: "Converta SVG para PNG e imagens para SVG diretamente no navegador.",
    keywords: ["converter svg png", "svg para png", "png para svg"],
  },
  {
    slug: "gerador-de-placeholder",
    name: "Gerador de Placeholder (LQIP)",
    description: "Crie placeholders leves para imagens e páginas mais rápidas.",
    category: "imagens",
    hubFilter: "Otimizar",
    badge: "Imagem",
    icon: WandSparkles,
    available: true,
    index: true,
    seoTitle: "Gerador de Placeholder LQIP Online Grátis | Kivai",
    seoDescription: "Gere placeholders leves e Data URLs para otimizar o carregamento de imagens.",
    keywords: ["lqip", "placeholder imagem", "imagem baixa qualidade"],
  },
  {
    slug: "pdf-para-imagens",
    name: "PDF para Imagens",
    description:
      "Extraia todas as páginas de um arquivo PDF em formato PNG ou JPG.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileText,
    featured: true,
    available: true,
    index: true,
  },
  {
    slug: "imagens-para-pdf",
    name: "Imagens para PDF",
    description: "Transforme arquivos JPG, PNG e WebP em um único documento PDF.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileImage,
    available: true,
    index: true,
  },
  {
    slug: "unir-pdfs",
    name: "Unir PDFs",
    description: "Combine vários arquivos PDF em um único documento.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: Combine,
    available: true,
    index: true,
  },
  {
    slug: "dividir-pdf",
    name: "Dividir PDF",
    description: "Separe cada página de um documento PDF em arquivos individuais.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: Scissors,
    available: true,
    index: true,
  },
  {
    slug: "girar-pdf",
    name: "Girar PDF",
    description: "Gire todas as páginas de um arquivo PDF em 90°, 180° ou 270°.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: RotateCw,
    available: true,
    index: true,
  },
  {
    slug: "compactar-pdf",
    name: "Compactar PDF",
    description:
      "Reduza o tamanho de arquivos PDF mantendo a melhor qualidade possível.",
    category: "pdf",
    hubFilter: "Otimizar",
    badge: "PDF",
    icon: Minimize2,
    available: true,
    index: true,
  },
  {
    slug: "calculadora-de-roas",
    name: "Calculadora de ROAS",
    description:
      "Calcule o retorno dos anúncios e estime o ROAS de equilíbrio da operação.",
    category: "calculadoras",
    hubFilter: "Marketing",
    badge: "Marketing",
    icon: BarChart3,
    available: true,
    index: true,
  },
  {
    slug: "calculadora-de-roi",
    name: "Calculadora de ROI",
    description:
      "Calcule a rentabilidade e descubra o ganho ou perda do seu investimento.",
    category: "calculadoras",
    hubFilter: "Financeiro",
    badge: "Negócios",
    icon: TrendingUp,
    available: true,
    index: true,
  },
  {
    slug: "calculadora-de-markup",
    name: "Calculadora de Markup",
    description:
      "Calcule o preço de venda, o lucro bruto e a margem resultante.",
    category: "calculadoras",
    hubFilter: "Vendas",
    badge: "Precificação",
    icon: Tags,
    available: true,
    index: true,
  },
  {
    slug: "calculadora-de-margem",
    name: "Calculadora de Margem",
    description: "Calcule a margem percentual e analise o lucro ou prejuízo por venda.",
    category: "calculadoras",
    hubFilter: "Vendas",
    badge: "Vendas",
    icon: Percent,
    available: true,
    index: true,
  },
  {
    slug: "calculadora-de-desconto",
    name: "Calculadora de Desconto",
    description: "Calcule o valor economizado e descubra o preço final.",
    category: "calculadoras",
    hubFilter: "Vendas",
    badge: "Vendas",
    icon: Percent,
    available: true,
    index: true,
  },
  {
    slug: "calculadora-de-porcentagem",
    name: "Calculadora de Porcentagem",
    description: "Resolva cálculos percentuais de forma simples e rápida.",
    category: "calculadoras",
    hubFilter: "Financeiro",
    badge: "Matemática",
    icon: Calculator,
    available: true,
    index: true,
    seoTitle: "Calculadora de Porcentagem Online Grátis | Kivai",
    seoDescription: "Calcule porcentagem, aumento, redução, desconto, acréscimo e descubra o valor original. Calculadora de porcentagem online, gratuita e fácil de usar.",
    keywords: ["calculadora de porcentagem", "calcular porcentagem", "aumento percentual", "desconto percentual"],
  },
  {
    slug: "contador-de-palavras",
    name: "Contador de Palavras",
    description:
      "Analise palavras, caracteres, frases, limites e tempo de leitura em tempo real.",
    category: "texto",
    hubFilter: "Analisar",
    badge: "Texto",
    icon: Type,
    available: true,
    index: true,
  },
  ...socialMediaToolDefinitions,
];

export function getToolHref(slug: string) {
  return `/ferramentas/${slug}`;
}

export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory) {
  return tools.filter((tool) => tool.category === category);
}
