import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Building2,
  Calculator,
  Combine,
  FileImage,
  FileBarChart,
  FilePenLine,
  FileSpreadsheet,
  ImagePlus,
  FileText,
  ImageIcon,
  LayoutGrid,
  Maximize2,
  Minimize2,
  Percent,
  QrCode,
  Radar,
  RotateCw,
  Scaling,
  Scissors,
  Tags,
  TrendingUp,
  Type,
  WandSparkles,
  CalendarDays,
  Code2,
  Download,
  Unlock,
  Video,
} from "lucide-react";

export type ToolCategory =
  | "imagens"
  | "pdf"
  | "calculadoras"
  | "texto"
  | "social"
  | "video"
  | "audio"
  | "documentos"
  | "desenvolvimento"
  | "marketing"
  | "ecommerce"
  | "seo"
  | "ia"
  | "utilitarios"
  | "empresas";

export interface ToolCategoryDefinition {
  slug: ToolCategory;
  name: string;
  description: string;
  href: string;
  icon: LucideIcon;
}

export const toolCategories: ToolCategoryDefinition[] = [
  {
    slug: "imagens",
    name: "Imagens",
    description:
      "Remova fundo, converta formatos, comprima arquivos e use outras ferramentas para edição de imagens.",
    href: "/ferramentas/imagens",
    icon: ImageIcon,
  },
  {
    slug: "pdf",
    name: "PDFs",
    description:
      "Converta, organize, extraia imagens e use diversas ferramentas para arquivos PDF.",
    href: "/ferramentas/pdfs",
    icon: FileText,
  },
  {
    slug: "calculadoras",
    name: "Calculadoras",
    description:
      "Ferramentas para ROAS, ROI, margem, markup, desconto, porcentagem e muito mais.",
    href: "/ferramentas/calculadoras",
    icon: Calculator,
  },
  {
    slug: "texto",
    name: "Texto",
    description:
      "Conte palavras, caracteres, tempo de leitura e use outras ferramentas para textos.",
    href: "/ferramentas/texto",
    icon: Type,
  },
  {
    slug: "social",
    name: "Social Media",
    description:
      "Revise legendas, hashtags e formatação para publicar conteúdos em redes sociais.",
    href: "/ferramentas/social-media",
    icon: Tags,
  },
  {
    slug: "video",
    name: "Vídeos",
    description:
      "Edite, ajuste e converta vídeos diretamente em navegadores compatíveis.",
    href: "/ferramentas/videos",
    icon: FileImage,
  },
  {
    slug: "empresas",
    name: "Empresas",
    description:
      "Consulte CNPJ, CNAE, NCM, bancos e domínios .BR para apoiar pesquisas empresariais e comerciais.",
    href: "/ferramentas/empresas",
    icon: Building2,
  },
];

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  hubFilter: string;
  badge: string;
  icon: LucideIcon;
  featured?: boolean;
  available: boolean;
  seoTitle?: string;
  seoDescription?: string;
  keywords?: string[];
}

export const INDEXABLE_TOOL_SLUGS = [
  "adicionar-marca-dagua",
  "ajustar-velocidade-video",
  "alterar-volume-video",
  "baixar-video-instagram",
  "calculadora-de-desconto",
  "calculadora-de-engajamento",
  "calculadora-de-margem",
  "calculadora-de-markup",
  "calculadora-de-porcentagem",
  "calculadora-de-roas",
  "calculadora-de-roi",
  "calendario-editorial-redes-sociais",
  "capturar-frame-video",
  "compressor-de-imagens",
  "compressor-de-videos",
  "consulta-de-cnae",
  "consulta-de-ncm",
  "consulta-cnpj",
  "conversor-de-imagens",
  "conversor-heic",
  "conversor-svg-png",
  "compactar-pdf",
  "contador-de-caracteres-instagram",
  "contador-de-palavras",
  "desbloquear-pdf",
  "dividir-pdf",
  "dividir-video",
  "editar-pdf",
  "espelhar-e-girar-imagem",
  "espelhar-video",
  "excel-para-pdf",
  "gerador-de-favicon",
  "gerador-de-relatorio-social-media",
  "gerador-de-placeholder",
  "gerador-de-qr-code",
  "girar-pdf",
  "girar-video",
  "html-para-pdf",
  "hevc-para-mp4",
  "mp4-para-hevc",
  "mp4-para-mov",
  "mp4-para-avi",
  "mov-para-mp4",
  "imagens-para-pdf",
  "montar-pdf-para-impressao",
  "pdf-para-excel",
  "pdf-para-html",
  "pdf-para-imagens",
  "pdf-para-powerpoint",
  "pdf-para-word",
  "planejador-de-conteudo-social-media",
  "powerpoint-para-pdf",
  "preview-de-post-redes-sociais",
  "radar-de-tendencias",
  "recortar-imagem",
  "recortar-video",
  "redimensionar-imagem",
  "redimensionar-pdf",
  "redimensionar-video",
  "removedor-de-fundo",
  "remover-audio-video",
  "unir-pdfs",
  "video-para-audio",
  "word-para-pdf",
] as const;

const indexableToolSlugs = new Set<string>(INDEXABLE_TOOL_SLUGS);

export function isToolIndexable(slug: string) {
  return indexableToolSlugs.has(slug);
}

export const tools: Tool[] = [
  {
    slug: "removedor-de-fundo",
    name: "Removedor de Fundo",
    description: "Remova automaticamente o fundo de fotos e imagens e baixe o resultado em PNG transparente.",
    category: "imagens",
    hubFilter: "Otimizar",
    badge: "Imagem",
    icon: ImageIcon,
    featured: true,
    available: true,
    seoTitle: "Removedor de Fundo Online Grátis",
    seoDescription:
      "Remova automaticamente o fundo de imagens PNG, JPG e WebP e baixe o resultado em PNG transparente. Ferramenta online gratuita e sem instalação.",
    keywords: [
      "removedor de fundo",
      "remover fundo de imagem",
      "apagar fundo de foto",
      "background remover",
      "remover fundo online",
    ],
  },
  {
    slug: "compressor-de-imagens",
    name: "Compressor de Imagens",
    description:
      "Reduza o tamanho de imagens JPG, PNG e WebP para sites, lojas e compartilhamento.",
    category: "imagens",
    hubFilter: "Otimizar",
    badge: "Imagem",
    icon: WandSparkles,
    featured: true,
    available: true,
    seoTitle: "Compressor de Imagens Online: reduzir PNG, JPG e WebP | Kivai",
    seoDescription: "Comprima imagens PNG, JPG e WebP online, compare a redução e baixe uma cópia otimizada com processamento local no navegador.",
    keywords: ["compressor de imagens", "comprimir imagem", "reduzir tamanho de imagem", "otimizar jpg", "comprimir png"],
  },
  {
    slug: "conversor-de-imagens",
    name: "Conversor de Imagens",
    description:
      "Converta arquivos entre PNG, JPG e WebP com controle de qualidade.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagem",
    icon: FileImage,
    featured: true,
    available: true,
    seoTitle: "Conversor de Imagens PNG, JPG e WebP Online | Kivai",
    seoDescription: "Converta imagens entre PNG, JPG e WebP, ajuste a qualidade e preserve o original com processamento feito no navegador.",
    keywords: ["conversor de imagens", "converter png para jpg", "converter jpg para png", "converter webp", "mudar formato de imagem"],
  },
  {
    slug: "conversor-heic",
    name: "Conversor HEIC",
    description: "Converta fotos HEIC e HEIF do iPhone para JPG gratuitamente.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagem",
    icon: FileImage,
    available: true,
    seoTitle: "Conversor HEIC para JPG Online | Kivai",
    seoDescription: "Converta fotos HEIC e HEIF para JPG diretamente no navegador, sem instalar programas e sem alterar o arquivo original.",
    keywords: ["heic para jpg", "converter heic", "conversor heif", "foto iphone para jpg", "abrir heic"],
  },
  {
    slug: "redimensionar-imagem",
    name: "Redimensionar Imagem",
    description:
      "Altere largura e altura de imagens mantendo a qualidade e a proporção.",
    category: "imagens",
    hubFilter: "Otimizar",
    badge: "Imagem",
    icon: Maximize2,
    available: true,
    seoTitle: "Redimensionar Imagem Online em PNG, JPG e WebP | Kivai",
    seoDescription: "Altere largura e altura de imagens, preserve a proporção e exporte em PNG, JPG ou WebP diretamente no navegador.",
    keywords: ["redimensionar imagem", "mudar tamanho da imagem", "alterar dimensões da foto", "reduzir pixels", "resize imagem"],
  },
  {
    slug: "gerador-de-qr-code",
    name: "Gerador de QR Code",
    description:
      "Crie QR Codes para links, textos, Wi-Fi, e-mail, ligações e WhatsApp, com +55 automático, composições gráficas, texto e logo.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Utilidades",
    icon: QrCode,
    featured: true,
    available: true,
    seoTitle: "Gerador de QR Code para Link, Wi-Fi, Telefone e WhatsApp | Kivai",
    seoDescription: "Crie QR Codes para URL, texto, Wi-Fi, e-mail, telefone e WhatsApp. Personalize com chamadas, marca, logo e composições gráficas em PNG ou SVG.",
    keywords: ["gerador de qr code", "criar qr code", "qr code wifi", "qr code whatsapp", "qr code telefone", "qr code para link", "qr code personalizado", "qr code com logo"],
  },
  {
    slug: "gerador-de-favicon",
    name: "Gerador de Favicon",
    description:
      "Crie favicons para sites em tamanhos prontos para navegadores e dispositivos.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagens",
    icon: ImagePlus,
    featured: true,
    available: true,
    seoTitle: "Gerador de Favicon Online Grátis | Kivai",
    seoDescription: "Crie favicon.ico e ícones PNG para seu site diretamente no navegador.",
    keywords: ["gerador de favicon", "favicon ico", "criar favicon"],
  },
  {
    slug: "adicionar-marca-dagua",
    name: "Adicionar Marca-d'água",
    description: "Adicione texto ou imagem como marca-d'água em fotos diretamente no navegador.",
    category: "imagens",
    hubFilter: "Editar",
    badge: "Imagem",
    icon: ImagePlus,
    available: true,
    seoTitle: "Adicionar Marca d'Água em Imagem Online | Kivai",
    seoDescription: "Adicione texto ou logotipo como marca d'água, controle posição, tamanho e opacidade e baixe uma nova imagem em PNG.",
    keywords: ["adicionar marca d'água", "marca d'água em foto", "colocar logo na imagem", "proteger imagem", "watermark online"],
  },
  {
    slug: "conversor-svg-png",
    name: "Conversor SVG para PNG",
    description: "Converta arquivos SVG em imagens PNG com dimensões personalizadas.",
    category: "imagens",
    hubFilter: "Converter",
    badge: "Imagem",
    icon: FileImage,
    available: true,
    seoTitle: "Conversor SVG para PNG e Imagem para SVG | Kivai",
    seoDescription: "Renderize SVG em PNG com largura personalizada ou incorpore PNG, JPG e WebP em um arquivo SVG, diretamente no navegador.",
    keywords: ["svg para png", "converter svg", "png para svg", "conversor svg png", "renderizar svg"],
  },
  {
    slug: "espelhar-e-girar-imagem",
    name: "Espelhar e Girar Imagem",
    description: "Gire e espelhe imagens horizontal ou verticalmente no navegador.",
    category: "imagens",
    hubFilter: "Editar",
    badge: "Imagem",
    icon: RotateCw,
    available: true,
    seoTitle: "Espelhar e Girar Imagem Online | Kivai",
    seoDescription: "Gire imagens em 90, 180 ou 270 graus e faça espelhamento horizontal ou vertical com processamento local.",
    keywords: ["espelhar imagem", "girar imagem", "inverter foto", "rotacionar imagem", "flip imagem"],
  },
  {
    slug: "gerador-de-placeholder",
    name: "Gerador de Placeholder",
    description: "Crie placeholders LQIP leves com prévia e ajustes em tempo real.",
    category: "imagens",
    hubFilter: "Editar",
    badge: "Imagem",
    icon: ImageIcon,
    available: true,
    seoTitle: "Gerador de Placeholder LQIP e Data URL | Kivai",
    seoDescription: "Crie um placeholder LQIP leve em JPEG, ajuste largura e qualidade e copie o Data URL para usar em sites e aplicações.",
    keywords: ["gerador lqip", "placeholder de imagem", "data url imagem", "blur placeholder", "imagem de baixa qualidade"],
  },
  {
    slug: "recortar-imagem",
    name: "Recortar Imagem",
    description: "Recorte áreas de imagens e exporte o resultado diretamente no navegador.",
    category: "imagens",
    hubFilter: "Editar",
    badge: "Imagem",
    icon: Scissors,
    available: true,
    seoTitle: "Recortar Imagem Online por Coordenadas | Kivai",
    seoDescription: "Recorte uma área retangular de imagens PNG, JPG e WebP informando posição, largura e altura, com processamento local.",
    keywords: ["recortar imagem", "cortar foto", "crop imagem", "recorte por pixels", "cortar png"],
  },
  {
    slug: "pdf-para-imagens",
    name: "PDF para Imagens",
    description:
      "Extraia todas as páginas de um arquivo PDF em formato PNG ou JPG.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileText,
    featured: true,
    available: true,
    seoTitle: "PDF para Imagens: converter páginas em PNG ou JPG | Kivai",
    seoDescription: "Converta cada página de um PDF em imagem PNG ou JPG, visualize os resultados e faça o download diretamente no navegador.",
    keywords: ["pdf para imagens", "pdf para png", "pdf para jpg", "converter página pdf", "extrair páginas do pdf"],
  },
  {
    slug: "pdf-para-word",
    name: "PDF para Word",
    description: "Converta arquivos PDF em documentos editáveis do Word no formato DOCX.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileText,
    featured: true,
    available: true,
    seoTitle: "PDF para Word: Converter PDF em DOCX Online Grátis | Kivai",
    seoDescription: "Converta PDF para Word (DOCX) online e grátis. Transforme textos, títulos, listas e tabelas em documentos editáveis, sem instalar programas.",
    keywords: ["pdf para word", "converter pdf em word", "pdf para docx", "transformar pdf em word", "conversor pdf word online"],
  },
  {
    slug: "pdf-para-html",
    name: "PDF para HTML",
    description: "Converta o conteúdo de arquivos PDF em HTML para visualizar, editar ou reutilizar textos e estruturas em páginas da web.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: Code2,
    available: true,
    seoTitle: "PDF para HTML: converta PDF em HTML online | Kivai",
    seoDescription: "Converta PDF para HTML online. Extraia textos, títulos, tabelas e conteúdos do PDF para reutilizar em páginas da web de forma simples.",
    keywords: ["pdf para html", "converter pdf em html", "transformar pdf em html", "pdf html", "extrair html de pdf", "converter documento para html"],
  },
  {
    slug: "desbloquear-pdf",
    name: "Desbloquear PDF",
    description: "Remova a proteção de PDFs quando você possuir a senha ou autorização para modificar o documento.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: Unlock,
    available: true,
    seoTitle: "Desbloquear PDF Online: remover senha com autorização | Kivai",
    seoDescription: "Desbloqueie arquivos PDF utilizando a senha correta. Gere uma nova versão do documento sem proteção de abertura de forma simples com o Kivai.",
    keywords: ["desbloquear pdf", "remover senha pdf", "tirar senha de pdf", "remover proteção pdf", "pdf protegido", "desbloqueador de pdf"],
  },
  {
    slug: "html-para-pdf",
    name: "HTML para PDF",
    description: "Converta conteúdo HTML em um arquivo PDF pronto para salvar, compartilhar ou imprimir.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: Code2,
    available: true,
    seoTitle: "HTML para PDF: converta HTML em PDF online | Kivai",
    seoDescription: "Converta HTML para PDF online. Cole seu código ou envie um arquivo HTML, ajuste tamanho, orientação e margens e gere um PDF pronto para download.",
    keywords: ["html para pdf", "converter html em pdf", "html pdf", "transformar html em pdf", "gerar pdf de html"],
  },
  {
    slug: "pdf-para-excel",
    name: "PDF para Excel",
    description: "Extraia tabelas e dados de arquivos PDF para uma planilha Excel.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileSpreadsheet,
    available: true,
    seoTitle: "PDF para Excel: Converter PDF em XLSX Online Grátis | Kivai",
    seoDescription: "Converta PDF para Excel (XLSX) online e grátis. Extraia tabelas e dados de PDFs digitais, revise o conteúdo e baixe uma planilha editável.",
    keywords: ["pdf para excel", "converter pdf em excel", "pdf para xlsx", "extrair tabela de pdf", "conversor pdf excel online"],
  },
  {
    slug: "excel-para-pdf",
    name: "Excel para PDF",
    description: "Converta planilhas Excel em arquivos PDF organizados, prontos para compartilhar, imprimir ou arquivar.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileSpreadsheet,
    available: true,
    seoTitle: "Excel para PDF: converta XLSX em PDF online | Kivai",
    seoDescription: "Converta planilhas Excel em PDF online. Transforme arquivos XLSX em documentos PDF organizados e prontos para compartilhar ou imprimir.",
    keywords: ["excel para pdf", "converter excel em pdf", "xlsx para pdf", "planilha para pdf", "transformar excel em pdf"],
  },
  {
    slug: "editar-pdf",
    name: "Editar PDF",
    description: "Adicione textos, imagens, formas, desenhos e marcações às páginas do seu PDF.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: FilePenLine,
    available: true,
    seoTitle: "Editar PDF Online: adicione textos e imagens | Kivai",
    seoDescription: "Edite PDF online adicionando textos, imagens, formas, desenhos, destaques e assinaturas visuais de maneira simples com o Kivai.",
    keywords: ["editar pdf", "editor de pdf", "escrever em pdf", "adicionar texto no pdf", "editar pdf online", "desenhar em pdf", "adicionar imagem no pdf"],
  },
  {
    slug: "redimensionar-pdf",
    name: "Redimensionar PDF",
    description: "Redimensione páginas de PDF para A6, A5, A4, A3, A2 ou A1, mantendo o conteúdo proporcional.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: Scaling,
    available: true,
    seoTitle: "Redimensionar PDF para A4, A3, A5 e outros | Kivai",
    seoDescription: "Redimensione páginas de PDF para A6, A5, A4, A3, A2 ou A1. Ajuste orientação, margens e proporção de maneira simples com o Kivai.",
    keywords: ["redimensionar pdf", "mudar tamanho do pdf", "pdf para a4", "pdf para a3", "pdf para a5", "alterar tamanho de página pdf", "converter pdf para a4"],
  },
  {
    slug: "montar-pdf-para-impressao",
    name: "Montar PDF para Impressão",
    description: "Monte um PDF em uma nova folha de impressão, escolhendo o tamanho da página, o tamanho do conteúdo e sua posição.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: LayoutGrid,
    available: true,
    seoTitle: "Montar PDF para Impressão Online | Kivai",
    seoDescription: "Monte um PDF para impressão escolhendo tamanho da folha, tamanho do conteúdo, posição, margens e quantidade por página. Ideal para etiquetas, documentos, cartões e materiais gráficos.",
    keywords: ["montar pdf para impressão", "pdf para imprimir", "várias páginas por folha", "imprimir etiquetas pdf", "organizar pdf para impressão"],
  },
  {
    slug: "word-para-pdf",
    name: "Word para PDF",
    description: "Converta documentos DOCX do Word em arquivos PDF diretamente no navegador.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileText,
    featured: true,
    available: true,
    seoTitle: "Word para PDF: Converter DOCX em PDF Online Grátis | Kivai",
    seoDescription: "Converta Word para PDF online e grátis. Transforme arquivos DOCX em PDF preservando textos, imagens, tabelas e formatação, sem instalar programas.",
    keywords: ["word para pdf", "converter word em pdf", "docx para pdf", "transformar word em pdf", "conversor word pdf online"],
  },
  {
    slug: "pdf-para-powerpoint",
    name: "PDF para PowerPoint",
    description: "Converta páginas de um arquivo PDF em slides de uma apresentação PowerPoint.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileText,
    featured: true,
    available: true,
    seoTitle: "PDF para PowerPoint: Converter PDF em PPTX Online Grátis | Kivai",
    seoDescription: "Converta PDF para PowerPoint (PPTX) online e grátis. Escolha, organize e transforme páginas do PDF em slides com alta fidelidade visual.",
    keywords: ["pdf para powerpoint", "converter pdf em powerpoint", "pdf para pptx", "transformar pdf em slides", "conversor pdf powerpoint online"],
  },
  {
    slug: "powerpoint-para-pdf",
    name: "PowerPoint para PDF",
    description: "Converta apresentações PowerPoint em arquivos PDF de forma rápida, organizada e com ótima qualidade.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileText,
    available: true,
    seoTitle: "PowerPoint para PDF: converta PPTX em PDF online | Kivai",
    seoDescription: "Converta apresentações PowerPoint em PDF online. Transforme arquivos PPTX em PDF de forma rápida, fácil e gratuita com o Kivai.",
    keywords: ["powerpoint para pdf", "pptx para pdf", "converter powerpoint em pdf", "converter pptx em pdf", "powerpoint para pdf online"],
  },
  {
    slug: "imagens-para-pdf",
    name: "Imagens para PDF",
    description: "Transforme arquivos JPG, PNG e WebP em um único documento PDF.",
    category: "pdf",
    hubFilter: "Converter",
    badge: "PDF",
    icon: FileImage,
    available: true,
    seoTitle: "Imagens para PDF: juntar JPG, PNG e WebP | Kivai",
    seoDescription: "Reúna imagens JPG, PNG e WebP em um PDF com páginas A4, proporção preservada e processamento local no navegador.",
    keywords: ["imagens para pdf", "jpg para pdf", "png para pdf", "juntar imagens em pdf", "fotos para pdf"],
  },
  {
    slug: "unir-pdfs",
    name: "Unir PDFs",
    description: "Combine vários arquivos PDF em um único documento.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: Combine,
    available: true,
    seoTitle: "Unir PDFs Online na Ordem Desejada | Kivai",
    seoDescription: "Combine dois ou mais PDFs, organize a sequência dos documentos e baixe um único arquivo sem enviar o conteúdo ao servidor.",
    keywords: ["unir pdf", "juntar pdf", "combinar pdf", "mesclar pdf", "unir documentos pdf"],
  },
  {
    slug: "dividir-pdf",
    name: "Dividir PDF",
    description: "Separe cada página de um documento PDF em arquivos individuais.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: Scissors,
    available: true,
    seoTitle: "Dividir PDF em Páginas Individuais Online | Kivai",
    seoDescription: "Separe todas as páginas de um PDF em arquivos individuais e baixe o conjunto organizado em ZIP, diretamente no navegador.",
    keywords: ["dividir pdf", "separar páginas pdf", "pdf por página", "extrair páginas pdf", "cortar pdf"],
  },
  {
    slug: "girar-pdf",
    name: "Girar PDF",
    description: "Gire todas as páginas de um arquivo PDF em 90°, 180° ou 270°.",
    category: "pdf",
    hubFilter: "Editar",
    badge: "PDF",
    icon: RotateCw,
    available: true,
    seoTitle: "Girar Todas as Páginas do PDF Online | Kivai",
    seoDescription: "Gire todas as páginas de um PDF em 90, 180 ou 270 graus e baixe uma nova cópia processada localmente.",
    keywords: ["girar pdf", "rotacionar pdf", "virar páginas pdf", "pdf de cabeça para baixo", "corrigir orientação pdf"],
  },
  {
    slug: "compactar-pdf",
    name: "Compactar PDF",
    description:
      "Reduza o tamanho de arquivos PDF mantendo a melhor qualidade possível.",
    category: "pdf",
    hubFilter: "Otimizar",
    badge: "PDF",
    icon: Minimize2,
    available: true,
    seoTitle: "Compactar PDF Online com Três Níveis | Kivai",
    seoDescription: "Otimize a estrutura do PDF ou gere uma cópia visual rasterizada com compressão média ou alta e processamento local.",
    keywords: ["compactar pdf", "comprimir pdf", "reduzir tamanho pdf", "otimizar pdf", "diminuir arquivo pdf"],
  },
  {
    slug: "verificador-de-dominio-br",
    name: "Verificador de Domínio .BR",
    description: "Consulte o status e outras informações públicas de um domínio .br.",
    category: "empresas",
    hubFilter: "Domínios",
    badge: "Domínios",
    icon: Code2,
    available: true,
    seoTitle: "Verificador de Domínio .BR Online | Kivai",
    seoDescription: "Verifique o status de um domínio .br e consulte informações públicas como FQDN, expiração, servidores DNS e sugestões de extensões.",
    keywords: ["verificador de domínio .br", "consultar domínio .br", "domínio br", "registro.br", "status de domínio", "verificar domínio"],
  },
  {
    slug: "consulta-de-cnae",
    name: "Consulta de CNAE",
    description: "Consulte a classificação de atividades econômicas pelo código CNAE e visualize sua hierarquia no IBGE.",
    category: "empresas",
    hubFilter: "Empresa",
    badge: "Empresa",
    icon: Building2,
    available: true,
    seoTitle: "Consulta de CNAE Online Grátis | Kivai",
    seoDescription: "Consulte códigos CNAE online e veja descrição, seção, divisão, grupo e observações da atividade econômica.",
    keywords: ["consulta de cnae", "consultar cnae", "cnae online", "código cnae", "cnae ibge", "atividade econômica cnae"],
  },
  {
    slug: "consulta-de-banco",
    name: "Consulta de Banco",
    description: "Consulte dados de bancos e instituições financeiras a partir do código bancário.",
    category: "empresas",
    hubFilter: "Financeiro",
    badge: "Financeiro",
    icon: Building2,
    available: true,
    seoTitle: "Consulta de Banco Online Grátis | Kivai",
    seoDescription: "Consulte código, nome, nome completo e ISPB de bancos e instituições financeiras.",
    keywords: ["consulta de banco", "consultar banco", "código banco", "código bancário", "ISPB", "bancos do Brasil"],
  },
  {
    slug: "consulta-de-ncm",
    name: "Consulta de NCM",
    description: "Consulte códigos NCM, descrição, vigência e informações do ato legal associado ao produto.",
    category: "empresas",
    hubFilter: "Comércio",
    badge: "Comércio",
    icon: Tags,
    available: true,
    seoTitle: "Consulta de NCM Online Grátis | Kivai",
    seoDescription: "Consulte códigos NCM online e veja descrição, vigência e informações do ato legal associado ao produto.",
    keywords: ["consulta de ncm", "consultar ncm", "ncm online", "código ncm", "ncm produto", "ncm comércio exterior"],
  },
  {
    slug: "consulta-cnpj",
    name: "Consulta de CNPJ",
    description:
      "Consulte dados cadastrais, situação, atividades, endereço, contatos, quadro societário e informações tributárias de empresas pelo CNPJ.",
    category: "empresas",
    hubFilter: "Empresa",
    badge: "Empresa",
    icon: Building2,
    available: true,
    seoTitle: "Consulta de CNPJ Online Grátis | Kivai",
    seoDescription:
      "Consulte CNPJ online e veja dados cadastrais, situação, razão social, nome fantasia, endereço, CNAE, atividades secundárias, quadro societário e outras informações disponíveis.",
    keywords: [
      "consulta de cnpj",
      "consultar cnpj",
      "consulta cnpj grátis",
      "consultar cnpj online",
      "pesquisar cnpj",
      "dados de empresa pelo cnpj",
      "situação cadastral cnpj",
    ],
  },
  {
    slug: "calculadora-de-roas",
    name: "Calculadora de ROAS",
    description:
      "Calcule o retorno dos anúncios e estime o ROAS de equilíbrio da operação.",
    category: "calculadoras",
    hubFilter: "Marketing",
    badge: "Marketing",
    icon: BarChart3,
    available: true,
  },
  {
    slug: "calculadora-de-roi",
    name: "Calculadora de ROI",
    description:
      "Calcule a rentabilidade e descubra o ganho ou perda do seu investimento.",
    category: "calculadoras",
    hubFilter: "Financeiro",
    badge: "Negócios",
    icon: TrendingUp,
    available: true,
  },
  {
    slug: "calculadora-de-markup",
    name: "Calculadora de Markup",
    description:
      "Calcule o preço de venda, o lucro bruto e a margem resultante.",
    category: "calculadoras",
    hubFilter: "Vendas",
    badge: "Precificação",
    icon: Tags,
    available: true,
  },
  {
    slug: "calculadora-de-margem",
    name: "Calculadora de Margem",
    description: "Calcule a margem percentual e analise o lucro ou prejuízo por venda.",
    category: "calculadoras",
    hubFilter: "Vendas",
    badge: "Vendas",
    icon: Percent,
    available: true,
  },
  {
    slug: "calculadora-de-desconto",
    name: "Calculadora de Desconto",
    description: "Calcule o valor economizado e descubra o preço final.",
    category: "calculadoras",
    hubFilter: "Vendas",
    badge: "Vendas",
    icon: Percent,
    available: true,
  },
  {
    slug: "calculadora-de-porcentagem",
    name: "Calculadora de Porcentagem",
    description: "Resolva cálculos percentuais de forma simples e rápida.",
    category: "calculadoras",
    hubFilter: "Financeiro",
    badge: "Matemática",
    icon: Calculator,
    available: true,
  },
  {
    slug: "contador-de-palavras",
    name: "Contador de Palavras",
    description:
      "Analise palavras, caracteres, frases, limites e tempo de leitura em tempo real.",
    category: "texto",
    hubFilter: "Analisar",
    badge: "Texto",
    icon: Type,
    available: true,
  },
  {
    slug: "calculadora-de-engajamento",
    name: "Calculadora de Engajamento",
    description: "Calcule a taxa de engajamento por seguidores, alcance ou impressões a partir das interações das suas publicações.",
    category: "social",
    hubFilter: "Analisar",
    badge: "Social Media",
    icon: BarChart3,
    available: true,
    seoTitle: "Calculadora de Engajamento para Redes Sociais | Kivai",
    seoDescription: "Calcule gratuitamente a taxa de engajamento por seguidores, alcance ou impressões e analise as interações das suas publicações.",
    keywords: ["calculadora de engajamento", "taxa de engajamento", "calcular engajamento", "engajamento Instagram", "engajamento por alcance"],
  },
  {
    slug: "gerador-de-relatorio-social-media",
    name: "Gerador de Relatório Social Media",
    description: "Organize métricas, compare períodos e crie um relatório visual de desempenho para redes sociais.",
    category: "social",
    hubFilter: "Analisar",
    badge: "Social Media",
    icon: FileBarChart,
    available: true,
    seoTitle: "Gerador de Relatório Social Media Grátis | Kivai",
    seoDescription: "Crie relatórios de redes sociais com métricas, engajamento, crescimento, comparações e gráficos para acompanhar e apresentar resultados.",
    keywords: ["gerador de relatório social media", "relatório social media", "relatório de redes sociais", "relatório Instagram", "modelo de relatório social media"],
  },
  {
    slug: "calendario-editorial-redes-sociais",
    name: "Calendário Editorial para Redes Sociais",
    description: "Planeje publicações por data, rede, formato, objetivo e status em um calendário mensal.",
    category: "social",
    hubFilter: "Planejar",
    badge: "Social Media",
    icon: CalendarDays,
    available: true,
    seoTitle: "Calendário Editorial para Redes Sociais Grátis | Kivai",
    seoDescription: "Crie um calendário editorial para Instagram, TikTok, LinkedIn e outras redes. Planeje publicações, filtre conteúdos e exporte seu plano em CSV.",
    keywords: ["calendário editorial", "calendário de conteúdo", "planejamento de redes sociais", "calendário social media", "planejamento de conteúdo"],
  },
  {
    slug: "radar-de-tendencias",
    name: "Radar de Notícias e Tendências",
    description: "Encontre notícias recentes de marketing, inteligência artificial e e-commerce em fontes especializadas.",
    category: "social",
    hubFilter: "Pesquisar",
    badge: "Marketing",
    icon: Radar,
    available: true,
    seoTitle: "Radar de Notícias de Marketing, IA e E-commerce",
    seoDescription: "Busque notícias recentes de marketing, inteligência artificial e e-commerce em uma seleção rápida de fontes especializadas.",
    keywords: ["radar de notícias", "notícias de marketing", "notícias de inteligência artificial", "notícias de e-commerce", "tendências do mercado digital"],
  },
  {
    slug: "planejador-de-conteudo-social-media",
    name: "Planejador de Conteúdo Social Media",
    description: "Estruture objetivos, público, temas, formatos e ideias para organizar a criação de conteúdos para redes sociais.",
    category: "social",
    hubFilter: "Planejar",
    badge: "Social Media",
    icon: FilePenLine,
    available: true,
    seoTitle: "Planejador de Conteúdo Social Media Grátis | Kivai",
    seoDescription: "Organize objetivo, público, tema, formato, abordagem e briefing das suas publicações com o Planejador de Conteúdo Social Media do Kivai.",
    keywords: ["planejador de conteúdo social media", "planejador de conteúdo", "planejamento de conteúdo", "plano de conteúdo", "briefing para social media"],
  },
  {
    slug: "preview-de-post-redes-sociais",
    name: "Preview de Post para Redes Sociais",
    description: "Visualize imagem, perfil e legenda em uma simulação de publicação antes de postar nas redes sociais.",
    category: "social",
    hubFilter: "Visualizar",
    badge: "Social Media",
    icon: LayoutGrid,
    available: true,
    seoTitle: "Preview de Post para Redes Sociais Grátis | Kivai",
    seoDescription: "Visualize perfil, imagem, texto e legenda antes de publicar com o Preview de Post para Redes Sociais do Kivai.",
    keywords: ["preview de post para redes sociais", "preview de post", "simulador de post", "visualizar post antes de publicar", "preview Instagram"],
  },
  {
    slug: "contador-de-caracteres-instagram",
    name: "Contador de Caracteres para Instagram",
    description: "Conte caracteres e confira limites de textos para publicações no Instagram.",
    category: "social",
    hubFilter: "Analisar",
    badge: "Social Media",
    icon: Type,
    available: true,
  },
  {
    slug: "baixar-video-instagram",
    name: "Baixar Vídeo e Foto do Instagram",
    description: "Baixe Reels, vídeos e fotos de publicações públicas do Instagram sem conectar sua conta.",
    category: "video",
    hubFilter: "Baixar",
    badge: "Instagram",
    icon: Download,
    featured: true,
    available: true,
    seoTitle: "Baixar Vídeo, Foto e Reels do Instagram | Kivai",
    seoDescription: "Cole o link de um Reel ou publicação pública do Instagram e baixe o vídeo ou a foto disponível sem conectar sua conta.",
    keywords: ["baixar vídeo instagram", "baixar foto instagram", "baixar reels", "download instagram", "salvar reel", "baixar vídeo do instagram online"],
  },
  {
    slug: "hevc-para-mp4",
    name: "HEVC → MP4",
    description: "Converta vídeos HEVC/H.265 para MP4 e melhore a compatibilidade para reprodução, edição e compartilhamento.",
    category: "video",
    hubFilter: "Converter",
    badge: "Vídeo",
    icon: Video,
    available: true,
    seoTitle: "HEVC para MP4: converta H.265 para MP4 online | Kivai",
    seoDescription: "Converta vídeos HEVC/H.265 para MP4 online. Melhore a compatibilidade do seu vídeo para reprodução, edição e compartilhamento.",
    keywords: ["hevc para mp4", "converter hevc para mp4", "h265 para mp4", "h.265 para mp4", "converter vídeo hevc", "video hevc para mp4"],
  },
  {
    slug: "compressor-de-videos",
    name: "Compressor de Vídeos",
    description: "Comprima vídeos em diferentes formatos para reduzir o tamanho do arquivo mantendo a melhor qualidade possível.",
    category: "video",
    hubFilter: "Otimizar",
    badge: "Vídeo",
    icon: Minimize2,
    available: true,
    seoTitle: "Compressor de Vídeo Online: reduza MP4, MOV e mais | Kivai",
    seoDescription: "Comprima vídeos MP4, MOV, WebM, AVI, MKV e outros formatos. Reduza o tamanho do arquivo ajustando qualidade e resolução de forma simples.",
    keywords: ["compressor de vídeo", "comprimir vídeo", "reduzir tamanho vídeo", "diminuir vídeo", "comprimir mp4", "comprimir mov", "reduzir vídeo para whatsapp", "reduzir vídeo mb", "compressor de vídeo online"],
  },
  {
    slug: "mp4-para-hevc",
    name: "MP4 → HEVC",
    description: "Converta vídeos MP4 para HEVC/H.265 e reduza o tamanho mantendo boa qualidade visual.",
    category: "video",
    hubFilter: "Converter",
    badge: "Vídeo",
    icon: Video,
    available: true,
    seoTitle: "MP4 para HEVC: converta vídeo para H.265 online | Kivai",
    seoDescription: "Converta vídeos MP4 para HEVC/H.265 online. Reduza o tamanho do arquivo mantendo a resolução e boa qualidade visual.",
    keywords: ["mp4 para hevc", "converter mp4 para hevc", "mp4 para h265", "mp4 para h.265", "converter vídeo para hevc", "compactar mp4 com hevc"],
  },
  {
    slug: "mp4-para-mov",
    name: "MP4 → MOV",
    description: "Converta vídeos MP4 para MOV de forma simples, mantendo resolução, duração e qualidade sempre que possível.",
    category: "video",
    hubFilter: "Converter",
    badge: "Vídeo",
    icon: Video,
    available: true,
    seoTitle: "MP4 para MOV: converta vídeo MP4 em MOV online | Kivai",
    seoDescription: "Converta MP4 para MOV online. Transforme seus vídeos para MOV mantendo resolução, áudio e qualidade sempre que possível.",
    keywords: ["mp4 para mov", "converter mp4 para mov", "mp4 mov", "transformar mp4 em mov", "vídeo mp4 para mov", "converter vídeo mov"],
  },
  {
    slug: "mov-para-mp4",
    name: "MOV → MP4",
    description: "Converta vídeos MOV para MP4 mantendo resolução, duração, áudio e qualidade sempre que possível.",
    category: "video",
    hubFilter: "Converter",
    badge: "Vídeo",
    icon: Video,
    available: true,
    seoTitle: "MOV para MP4: converta vídeo MOV em MP4 online | Kivai",
    seoDescription: "Converta MOV para MP4 online. Transforme vídeos de celulares, câmeras e editores em MP4 mantendo qualidade, resolução e áudio sempre que possível.",
    keywords: ["mov para mp4", "converter mov para mp4", "mov mp4", "transformar mov em mp4", "vídeo mov para mp4", "converter vídeo iphone para mp4", "converter mov online"],
  },
  {
    slug: "mp4-para-avi",
    name: "MP4 → AVI",
    description: "Converta vídeos MP4 para AVI com o padrão de conversão do Hub Vídeos do Kivai.",
    category: "video",
    hubFilter: "Converter",
    badge: "Vídeo",
    icon: Video,
    available: true,
    seoTitle: "MP4 para AVI: converta vídeo MP4 em AVI online | Kivai",
    seoDescription: "Converta vídeos MP4 para AVI online de forma simples com o Kivai. Gere um arquivo AVI compatível para seus projetos e aplicações.",
    keywords: ["mp4 para avi", "converter mp4 para avi", "transformar mp4 em avi", "vídeo mp4 para avi", "converter vídeo avi"],
  },
  {
    slug: "ajustar-velocidade-video",
    name: "Ajustar Velocidade do Vídeo",
    description: "Acelere ou desacelere vídeos diretamente no navegador.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: TrendingUp,
    available: true,
  },
  {
    slug: "alterar-volume-video",
    name: "Alterar Volume do Vídeo",
    description: "Aumente ou reduza o volume de vídeos e exporte uma nova versão.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: BarChart3,
    available: true,
  },
  {
    slug: "capturar-frame-video",
    name: "Capturar Frame do Vídeo",
    description: "Capture um quadro do vídeo e salve como imagem PNG, JPG ou WebP.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: FileImage,
    available: true,
  },
  {
    slug: "dividir-video",
    name: "Dividir Vídeo",
    description: "Escolha um ponto de corte e gere duas partes do seu vídeo.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Scissors,
    available: true,
  },
  {
    slug: "espelhar-video",
    name: "Espelhar Vídeo",
    description: "Espelhe vídeos horizontal ou verticalmente no navegador.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: RotateCw,
    available: true,
  },
  {
    slug: "girar-video",
    name: "Girar Vídeo",
    description: "Corrija a orientação de vídeos com rotações de 90, 180 ou 270 graus.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: RotateCw,
    available: true,
  },
  {
    slug: "recortar-video",
    name: "Recortar Vídeo",
    description: "Recorte a área visível do vídeo e exporte o resultado no navegador.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Scissors,
    available: true,
  },
  {
    slug: "redimensionar-video",
    name: "Redimensionar Vídeo",
    description: "Altere as dimensões do vídeo sem enviar o arquivo para servidores.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Scaling,
    available: true,
  },
  {
    slug: "remover-audio-video",
    name: "Remover Áudio do Vídeo",
    description: "Remova a faixa de áudio de vídeos diretamente no navegador.",
    category: "video",
    hubFilter: "Edição",
    badge: "Vídeo",
    icon: Minimize2,
    available: true,
  },
  {
    slug: "video-para-audio",
    name: "Vídeo para Áudio",
    description: "Extraia a faixa de áudio de um vídeo diretamente no navegador.",
    category: "video",
    hubFilter: "Converter",
    badge: "Vídeo",
    icon: FileText,
    available: true,
  },
];

export function getToolHref(slug: string) {
  return `/ferramentas/${slug}`;
}

export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory) {
  return tools.filter((tool) => tool.category === category);
}
