import { planBenefits } from "@/lib/billing/plan-benefits";
import type { ManagedSiteContent } from "@/lib/site-cms/types";
export const plansContent: ManagedSiteContent = {
 id: "existing:planos", contentType: "page", slug: "planos", path: "/planos",
 title: "Ferramentas para analisar, planejar e organizar seu trabalho",
 shortDescription: "Comece grátis. Com Pro, salve calendários e briefings na conta e acompanhe o histórico do Instagram. Com Agency, organize também os projetos por cliente.",
 contentHtml: "<h2>O que está incluído</h2><p>Os limites de projetos somam calendários e briefings. No Pro, salve até 30 projetos pessoais. No Agency, salve até 200 projetos organizados por até 20 nomes de clientes. Clientes são pastas de organização: esta entrega não inclui membros de equipe, login de clientes ou aprovação externa.</p><h2>Como salvar e continuar em outro dispositivo</h2><p>Abra o calendário ou o planejador, dê um nome ao projeto e escolha Salvar na conta. Em outro dispositivo, entre na mesma conta e abra o projeto na ferramenta. As mudanças são salvas ao clicar no botão; não há edição colaborativa em tempo real. Use Salvar como novo projeto para reutilizar um modelo.</p><h2>Instagram e histórico</h2><p>As análises dependem das exportações oficiais da Meta que você importa. A primeira análise salva estabelece a referência; as seguintes permitem comparar períodos. Não coletamos automaticamente os dados do Instagram. O Agency não impõe um teto numérico de seguidores, mas a capacidade do navegador continua sendo um limite técnico.</p><h2>Pagamento e ativação</h2><p>Registre a contratação, pague no serviço financeiro e informe o pagamento no painel. O acesso é ativado após a conferência do administrador. O painel consulta a confirmação automaticamente enquanto estiver aberto e visível.</p><h2>Renovação e mudança de plano</h2><p>Na renovação do mesmo plano, inclusive ao mudar de mensal para anual, o novo período é acrescentado ao vencimento vigente. Na troca entre Pro e Agency, o novo plano entra em vigor na confirmação, com novo período contado dessa data; não há cálculo automático de crédito proporcional. Antes de pagar por uma troca antecipada, combine eventual saldo com o atendimento.</p><h2>Quando o acesso vence</h2><p>Novas gravações na conta ficam bloqueadas. Seus projetos existentes continuam disponíveis para abrir, exportar ou excluir. Ao sair do Agency, projetos de clientes permanecem consultáveis e podem ser copiados para uso pessoal dentro dos limites do Pro.</p><h2>Serviços contratados separadamente</h2><p>Gestão de redes sociais, criação de conteúdo por profissionais, tráfego pago e consultoria não estão incluídos na assinatura das ferramentas. Solicite uma proposta em Serviços.</p>",
 seoTitle: "Planos Kivai | Grátis, Pro e Agency", seoDescription: "Compare histórico do Instagram, calendários e briefings salvos no Pro e organização por cliente no Agency.",
 canonicalUrl: "", hubId: null, existingToolSlug: null, toolMode: "informational", technicalStatus: "not_applicable", displayLocation: "direct", showInMostUsed: false, displayOrder: 20,
 status: "published", indexable: true, includeInSitemap: true, publishedAt: null, createdAt: "", updatedAt: "", virtual: true,
 customData: { originalFields: [
   ...(["free", "pro", "agency"] as const).flatMap(code => [
     { key: `${code}-description`, label: `Resumo ${code}`, type: "textarea" as const, value: code === "free" ? "Ferramentas gratuitas para uso pontual, com rascunhos no navegador." : code === "pro" ? "Projetos pessoais salvos na conta e acompanhamento do Instagram." : "Organização de projetos por cliente e maior capacidade para sua operação." },
     { key: `${code}-features`, label: `Benefícios ${code} (um por linha)`, type: "textarea" as const, value: planBenefits[code].join("\n") },
   ]),
   { key: "tutorial-url", label: "Link de tutorial dos planos", type: "url", value: "" },
 ] },
};
