import type { Metadata } from "next";
import Link from "next/link";
import { DEFAULT_SOCIAL_IMAGE } from "@/lib/seo";
import CalculadoraEngajamentoClient from "./calculadora-client";

const url = "https://www.kivai.com.br/ferramentas/calculadora-de-engajamento";
const title = "Calculadora de Engajamento para Redes Sociais | Kivai";
const description = "Calcule gratuitamente a taxa de engajamento por seguidores, alcance ou impressões e analise as interações das suas publicações.";
export const metadata: Metadata = { title: { absolute: title }, description, keywords: ["calculadora de engajamento", "taxa de engajamento", "calcular engajamento", "engajamento Instagram", "engajamento TikTok", "engajamento por alcance", "média de engajamento"], alternates: { canonical: url }, robots: { index: true, follow: true }, openGraph: { title, description, url, type: "website", siteName: "Kivai", locale: "pt_BR", images: [{ url: DEFAULT_SOCIAL_IMAGE, width: 1200, height: 630, alt: "Kivai" }] }, twitter: { card: "summary_large_image", title, description, images: [DEFAULT_SOCIAL_IMAGE] } };
const faq = [
  ["O que é taxa de engajamento?", "É a relação percentual entre as interações registradas e uma base escolhida, como seguidores, alcance ou impressões."],
  ["Como calcular a taxa de engajamento?", "Some as interações, divida pela base analisada e multiplique por 100. A ferramenta faz essa operação automaticamente."],
  ["Quais interações devo incluir?", "Use métricas coerentes com sua análise, como curtidas, comentários, compartilhamentos, salvamentos, cliques e outras ações disponíveis."],
  ["Devo calcular por seguidores ou alcance?", "Seguidores relacionam ações ao tamanho da audiência do perfil; alcance relaciona ações às pessoas alcançadas. A escolha depende do objetivo e dos dados disponíveis."],
  ["Qual é a diferença entre alcance e impressões?", "Alcance costuma representar pessoas ou contas únicas expostas; impressões representam o total de exibições, inclusive repetições."],
  ["Como calcular engajamento no Instagram?", "Informe as interações disponibilizadas pelo Instagram e escolha seguidores, alcance ou impressões como base, mantendo o mesmo método nas comparações."],
  ["Como calcular engajamento no TikTok?", "Some as interações que deseja analisar e divida pela base disponível. A rede selecionada contextualiza o resultado, mas não altera a fórmula."],
  ["Como calcular a média de engajamento?", "Calcule a taxa de cada publicação e faça a média, ou some interações e bases para obter a taxa consolidada. A ferramenta mostra as duas."],
  ["Salvamentos e compartilhamentos contam como engajamento?", "Podem contar quando fazem parte da metodologia definida. O importante é aplicar os mesmos critérios ao comparar conteúdos."],
  ["Cliques podem entrar no cálculo?", "Sim, se forem relevantes para o objetivo da análise. Registre a metodologia para interpretar e comparar os resultados corretamente."],
  ["Existe uma taxa de engajamento ideal?", "Não existe uma taxa universal. Plataforma, formato, segmento, audiência, período e método influenciam o resultado."],
  ["A ferramenta publica ou acessa minhas redes sociais?", "Não. Todos os números são fornecidos pelo usuário e calculados localmente, sem conexão com contas externas."],
];
const schema = [{ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Calculadora de Engajamento", applicationCategory: "BusinessApplication", operatingSystem: "Navegador moderno", url, description, offers: { "@type": "Offer", price: "0", priceCurrency: "BRL" }, featureList: ["Engajamento por seguidores", "Engajamento por alcance", "Engajamento por impressões", "Média de publicações", "Taxa consolidada"] }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Início", item: "https://www.kivai.com.br" }, { "@type": "ListItem", position: 2, name: "Social Media", item: "https://www.kivai.com.br/ferramentas/social-media" }, { "@type": "ListItem", position: 3, name: "Calculadora de Engajamento", item: url }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }];
export default function Page() { return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><CalculadoraEngajamentoClient /><section className="border-t border-border bg-muted/10 py-12"><div className="mx-auto max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8">
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">O que é taxa de engajamento?</h2><p className="mt-4 leading-7 text-muted-foreground">A taxa de engajamento expressa a proporção entre interações e uma base de comparação. Curtidas, comentários, compartilhamentos, salvamentos e cliques podem compor o total, desde que a metodologia seja consistente. O percentual ajuda a comparar conteúdos, mas isoladamente não representa vendas, alcance futuro ou qualidade universal.</p></article>
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Seguidores, alcance ou impressões: qual método usar?</h2><div className="mt-5 grid gap-5 text-sm leading-6 text-muted-foreground md:grid-cols-3"><p><strong className="block text-foreground">Por seguidores</strong>Relaciona as interações ao tamanho total da audiência do perfil. Pode ser útil quando dados de distribuição da publicação não estão disponíveis.</p><p><strong className="block text-foreground">Por alcance</strong>Relaciona as interações às pessoas ou contas alcançadas pelo conteúdo. Ajuda a observar ações entre quem teve contato com a publicação.</p><p><strong className="block text-foreground">Por impressões</strong>Relaciona as interações ao total de exibições, incluindo visualizações repetidas. Nenhuma fórmula é universalmente a única correta.</p></div></article>
  <div className="grid gap-6 lg:grid-cols-2"><article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Como calcular engajamento</h2><ol className="mt-4 space-y-2 text-sm text-muted-foreground"><li>1. Escolha seguidores, alcance ou impressões.</li><li>2. Informe cada tipo de interação.</li><li>3. Preencha a base do método escolhido.</li><li>4. Confira o total e a taxa calculada.</li><li>5. Consulte a fórmula transparente.</li><li>6. Copie o resultado, se desejar.</li></ol></article><article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Exemplo prático</h2><p className="mt-4 leading-7 text-muted-foreground">Uma publicação recebeu 400 curtidas, 40 comentários, 30 compartilhamentos e 30 salvamentos: 500 interações. Com alcance de 10.000 pessoas, o cálculo é 500 ÷ 10.000 × 100, resultando em <strong className="text-foreground">5% de engajamento por alcance</strong>. Esse percentual precisa ser interpretado no contexto analisado.</p></article></div>
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Média das taxas e taxa consolidada</h2><p className="mt-4 leading-7 text-muted-foreground">A média simples atribui o mesmo peso à taxa de cada publicação. Já a taxa consolidada soma todas as interações e divide pela soma das bases, fazendo conteúdos com bases maiores influenciarem mais o resultado. As duas medidas podem ser úteis, mas respondem a perguntas diferentes e não devem ser confundidas.</p></article>
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Engajamento não é resultado de negócio</h2><p className="mt-4 leading-7 text-muted-foreground">Interações mostram comportamento dentro do conteúdo, mas não indicam necessariamente leads, vendas ou retorno financeiro. Conforme o objetivo, também pode ser necessário acompanhar cliques, conversões, CTR, CPA, ROAS e ROI. Para análises financeiras, use a <Link className="text-primary hover:underline" href="/ferramentas/calculadora-de-roas">Calculadora de ROAS</Link> e a <Link className="text-primary hover:underline" href="/ferramentas/calculadora-de-roi">Calculadora de ROI</Link>.</p></article>
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Perguntas frequentes</h2><div className="mt-5 space-y-3">{faq.map(([question, answer]) => <details key={question} className="border border-border p-4"><summary className="cursor-pointer font-medium">{question}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{answer}</p></details>)}</div></article>
  <nav aria-label="Ferramentas relacionadas" className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Ferramentas relacionadas</h2><div className="mt-4 flex flex-wrap gap-3"><Related href="/ferramentas/planejador-de-conteudo-social-media">Planejador de Conteúdo</Related><Related href="/ferramentas/calendario-editorial-redes-sociais">Calendário Editorial</Related><Related href="/ferramentas/preview-de-post-redes-sociais">Preview de Post</Related><Related href="/ferramentas/contador-de-caracteres-instagram">Contador de Caracteres</Related><Related href="/ferramentas/contador-de-hashtags-instagram">Contador de Hashtags</Related></div></nav>
</div></section></>; }
function Related({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="border border-border px-4 py-2 text-sm font-medium transition-colors hover:border-primary hover:text-primary">{children}</Link>; }
