"use client";
import { Button } from "@/components/ui/button";
import { defaultPrinters, type Printer } from "@/lib/duplex-print/catalog";

export function PrinterCatalogEditor({ value, onChange }: { value: unknown; onChange: (value: Printer[]) => void }) {
  const printers = (Array.isArray(value) ? value : defaultPrinters) as Printer[];
  const field = "mt-1 w-full rounded-md border bg-background p-2";
  function update(index: number, key: keyof Printer, value: string) { onChange(printers.map((p, i) => i === index ? { ...p, [key]: value } : p)); }
  return <section className="space-y-4 rounded-xl border p-5"><h2 className="font-semibold">Modelos de impressora</h2><p className="text-sm text-muted-foreground">Cadastre dados verificados. A confirmação exige fonte HTTPS e instruções completas. A calibração continua disponível para cada bandeja.</p>{printers.map((p, i) => <details key={i} className="rounded-lg border p-3"><summary>{p.brand} {p.model || "Novo modelo"}</summary><div className="mt-4 grid gap-3 sm:grid-cols-2">
    {([['brand', 'Marca', ['Epson', 'HP', 'Canon', 'Brother']], ['duplex', 'Duplex automático', ['unknown', 'yes', 'no']], ['status', 'Verificação das instruções', ['unconfirmed', 'confirmed']], ['edge', 'Borda recomendada', ['long', 'short']]] as const).map(([key, label, options]) => <label key={key} className="text-sm">{label}<select className={field} value={p[key]} onChange={e => update(i, key, e.target.value)}>{options.map(o => <option key={o} value={o}>{{ Epson: 'Epson', HP: 'HP', Canon: 'Canon', Brother: 'Brother', unknown: 'Desconhecido', yes: 'Sim', no: 'Não', unconfirmed: 'Não confirmada', confirmed: 'Confirmada', long: 'Longa', short: 'Curta' }[o] ?? o}</option>)}</select></label>)}
    {([['id', 'Identificador para futura URL'], ['model', 'Modelo'], ['source', 'Fonte oficial (HTTPS)'], ['tray', 'Bandeja / alimentação'], ['output', 'Saída do papel'], ['firstPass', 'Orientação e sequência da primeira impressão'], ['reinsertion', 'Reinserção: face, topo e sequência do segundo lado'], ['notes', 'Observações'], ['tutorialUrl', 'Tutorial / mídia (HTTPS)']] as const).map(([key, label]) => <label key={key} className="text-sm">{label}<textarea className={field} value={p[key]} onChange={e => update(i, key, e.target.value)} /></label>)}
    <Button type="button" variant="outline" onClick={() => onChange(printers.filter((_, j) => j !== i))}>Remover modelo</Button></div></details>)}<Button type="button" variant="outline" onClick={() => onChange([...printers, { id: `modelo-${Date.now()}`, brand: "Epson", model: "Novo modelo", duplex: "unknown", status: "unconfirmed", source: "", tray: "", output: "", firstPass: "", reinsertion: "", edge: "long", notes: "", tutorialUrl: "" }])}>Adicionar impressora</Button></section>;
}
