"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ExternalLink, FilePlus2, Pencil, Save, Search, Trash2, X } from "lucide-react";
import { PaginationControls } from "@/components/admin/pagination-controls";
import { RichTextEditor } from "@/components/admin/rich-text-editor";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { slugify } from "@/lib/blog/slug";
import { formatSiteEditDate } from "@/lib/site-cms/date";
import type { ManagedSiteContent, ManagedSiteService, SiteHub, SitePublicationStatus } from "@/lib/site-cms/types";

type HubDraft = Omit<SiteHub, "createdAt" | "publishedAt">;
const PAGE_SIZE = 10;
const fieldClass = "block space-y-1.5 text-sm";
const textareaClass = "min-h-24 w-full rounded-md border border-input bg-background p-3 text-sm";
const emptyHub = (): HubDraft => ({ id: "new", slug: "", name: "", description: "", path: "", contentHtml: "", seoTitle: "", seoDescription: "", status: "draft", indexable: false, includeInSitemap: false, updatedAt: "" });

function HubPublicationControls({ value, onChange }: { value: HubDraft; onChange: (patch: Partial<HubDraft>) => void }) {
  const published = value.status === "published";
  return <fieldset className="space-y-3 rounded-lg border border-white/10 bg-muted/10 p-4"><legend className="px-1 text-sm font-semibold">Publicação e Google</legend><label className={fieldClass}><span>Status</span><select value={value.status} onChange={(e) => onChange({ status: e.target.value as SitePublicationStatus })} className="h-10 w-full rounded-md border border-input bg-background px-3"><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="archived">Arquivado</option></select></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 size-4" disabled={!published} checked={published && value.indexable} onChange={(e) => onChange({ indexable: e.target.checked, ...(e.target.checked ? {} : { includeInSitemap: false }) })} /><span><strong>Permitir indexação</strong><small className="block text-muted-foreground">Desmarcado envia noindex.</small></span></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 size-4" disabled={!published || !value.indexable} checked={published && value.indexable && value.includeInSitemap} onChange={(e) => onChange({ includeInSitemap: e.target.checked })} /><span><strong>Incluir no sitemap</strong></span></label></fieldset>;
}

export function SiteCmsManager({ initialContents, initialHubs, initialServices }: { initialContents: ManagedSiteContent[]; initialHubs: SiteHub[]; initialServices: ManagedSiteService[] }) {
  const router = useRouter();
  const [tab, setTab] = useState<"contents" | "hubs" | "services">("contents");
  const [hubs, setHubs] = useState(initialHubs);
  const [query, setQuery] = useState("");
  const [contentPage, setContentPage] = useState(1);
  const [hubPage, setHubPage] = useState(1);
  const [servicePage, setServicePage] = useState(1);
  const [hubDraft, setHubDraft] = useState<HubDraft | null>(null);
  const [message, setMessage] = useState("");
  const hubNames = useMemo(() => new Map(hubs.map((hub) => [hub.id, hub.name])), [hubs]);
  const normalizedQuery = query.trim().toLocaleLowerCase("pt-BR");
  const filteredContents = useMemo(() => initialContents.filter((item) => !normalizedQuery || [item.title, item.path, item.contentType, item.shortDescription, item.hubId ? hubNames.get(item.hubId) : ""].some((value) => String(value ?? "").toLocaleLowerCase("pt-BR").includes(normalizedQuery))), [initialContents, normalizedQuery, hubNames]);
  const filteredHubs = useMemo(() => hubs.filter((hub) => !normalizedQuery || [hub.name, hub.slug, hub.path, hub.description].some((value) => value.toLocaleLowerCase("pt-BR").includes(normalizedQuery))), [hubs, normalizedQuery]);
  const filteredServices = useMemo(() => initialServices.filter((item) => !normalizedQuery || [item.title, item.slug, item.path, item.shortDescription, item.serviceType, item.audience].some((value) => value.toLocaleLowerCase("pt-BR").includes(normalizedQuery))), [initialServices, normalizedQuery]);
  const safeContentPage = Math.min(contentPage, Math.max(1, Math.ceil(filteredContents.length / PAGE_SIZE)));
  const safeHubPage = Math.min(hubPage, Math.max(1, Math.ceil(filteredHubs.length / PAGE_SIZE)));
  const contentSlice = filteredContents.slice((safeContentPage - 1) * PAGE_SIZE, safeContentPage * PAGE_SIZE);
  const hubSlice = filteredHubs.slice((safeHubPage - 1) * PAGE_SIZE, safeHubPage * PAGE_SIZE);
  const safeServicePage = Math.min(servicePage, Math.max(1, Math.ceil(filteredServices.length / PAGE_SIZE)));
  const serviceSlice = filteredServices.slice((safeServicePage - 1) * PAGE_SIZE, safeServicePage * PAGE_SIZE);

  function changeTab(next: "contents" | "hubs" | "services") { setTab(next); setQuery(""); setContentPage(1); setHubPage(1); setServicePage(1); }
  async function refreshHubs() { const response = await fetch("/api/admin/site-hubs"); if (response.ok) setHubs(await response.json()); router.refresh(); }
  async function saveHub(event: React.FormEvent) { event.preventDefault(); if (!hubDraft) return; setMessage("Salvando hub..."); const creating = hubDraft.id === "new"; const response = await fetch(creating ? "/api/admin/site-hubs" : `/api/admin/site-hubs/${hubDraft.id}`, { method: creating ? "POST" : "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(hubDraft) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Não foi possível salvar o hub."); setMessage("Hub salvo."); setHubDraft(null); await refreshHubs(); }
  async function removeHub(hub: SiteHub) { if (!window.confirm(`Excluir o hub “${hub.name}”? As ferramentas permanecerão publicadas, mas ficarão sem hub.`)) return; const response = await fetch(`/api/admin/site-hubs/${hub.id}`, { method: "DELETE" }); if (!response.ok) return setMessage((await response.json()).error); setMessage("Hub excluído."); await refreshHubs(); }

  return <div className="space-y-5">
    <div className="flex flex-col gap-3 rounded-xl border border-white/10 bg-card p-3 sm:flex-row sm:items-center sm:justify-between"><div className="grid grid-cols-3 gap-2"><Button type="button" variant={tab === "contents" ? "default" : "outline"} onClick={() => changeTab("contents")}>Conteúdos</Button><Button type="button" variant={tab === "services" ? "default" : "outline"} onClick={() => changeTab("services")}>Serviços</Button><Button type="button" variant={tab === "hubs" ? "default" : "outline"} onClick={() => changeTab("hubs")}>Hubs</Button></div>{tab === "contents" ? <Button asChild><Link href="/admin/site/conteudos/novo"><FilePlus2 />Adicionar conteúdo</Link></Button> : tab === "services" ? <Button asChild><Link href="/admin/site/servicos/novo"><FilePlus2 />Adicionar serviço</Link></Button> : <Button type="button" onClick={() => setHubDraft(emptyHub())}><FilePlus2 />Criar hub</Button>}</div>
    <label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => { setQuery(event.target.value); setContentPage(1); setHubPage(1); setServicePage(1); }} className="h-11 pl-10" placeholder={tab === "contents" ? "Pesquisar ferramenta, página, material, URL ou hub" : tab === "services" ? "Pesquisar serviço, público, tipo ou URL" : "Pesquisar hub por nome, URL ou descrição"} /></label>
    {message ? <p role="status" className="border border-white/10 bg-muted/10 p-3 text-sm">{message}</p> : null}

    {tab === "contents" ? <section className="overflow-hidden rounded-xl border border-white/10 bg-card"><div className="grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-3">{contentSlice.map((item) => <article key={item.id} className="flex min-w-0 flex-col rounded-lg border border-white/10 bg-background p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words text-sm font-semibold">{item.title}</h2><p className="mt-1 break-all text-xs text-muted-foreground">{item.path}</p></div><span className={`shrink-0 rounded-full border px-2 py-1 text-[10px] ${item.status === "published" ? "border-emerald-500/30 text-emerald-300" : "border-white/10 text-muted-foreground"}`}>{item.status === "published" ? "Publicado" : item.status === "draft" ? "Rascunho" : "Arquivado"}</span></div>{item.contentType === "tool" && item.technicalStatus === "pending" ? <p className="mt-3 rounded-md border border-amber-500/25 bg-amber-500/5 p-2 text-xs font-medium text-amber-200">Aguardando implementação no Codex/ChatGPT</p> : null}<div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-md bg-muted/15 p-2"><span className="block text-muted-foreground">Tipo</span>{item.contentType === "tool" ? "Ferramenta" : item.contentType === "resource" ? "Recurso" : "Página"}</div><div className="rounded-md bg-muted/15 p-2"><span className="block text-muted-foreground">Hub</span><span className="break-words">{item.hubId ? hubNames.get(item.hubId) ?? "Removido" : "Sem hub"}</span></div><div className="rounded-md bg-muted/15 p-2"><span className="block text-muted-foreground">Google</span>{item.indexable ? "Indexável" : "Noindex"}</div><div className="rounded-md bg-muted/15 p-2"><span className="block text-muted-foreground">Sitemap</span>{item.includeInSitemap ? "Incluído" : "Fora"}</div></div><p className="mt-3 text-xs text-muted-foreground"><strong>Última edição:</strong> {formatSiteEditDate(item.updatedAt)}</p>{item.virtual ? <p className="mt-2 text-[10px] font-medium uppercase tracking-wide text-primary">Conteúdo atual do código</p> : null}<div className="mt-auto grid grid-cols-[1fr_auto] gap-2 pt-4"><Button asChild size="sm"><Link href={`/admin/site/conteudos/${encodeURIComponent(item.id)}`}><Pencil />Editar em tela completa</Link></Button><Button asChild type="button" variant="outline" size="icon-sm"><a href={item.path} target="_blank" rel="noreferrer" title="Abrir página"><ExternalLink /></a></Button></div></article>)}</div>{!contentSlice.length ? <p className="p-10 text-center text-sm text-muted-foreground">Nenhum conteúdo encontrado.</p> : null}<PaginationControls page={safeContentPage} totalItems={filteredContents.length} onPageChange={setContentPage} /></section> : null}

    {tab === "hubs" ? <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(320px,460px)]"><section className="overflow-hidden rounded-xl border border-white/10 bg-card"><div className="grid gap-3 p-3 sm:grid-cols-2">{hubSlice.map((hub) => <article key={hub.id} className="min-w-0 rounded-lg border border-white/10 bg-background p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="font-semibold">{hub.name}</h2><p className="mt-1 break-all text-xs text-muted-foreground">{hub.path}</p></div><span className="text-xs text-muted-foreground">{hub.status}</span></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-muted-foreground">{hub.description || "Sem descrição"}</p><p className="mt-3 text-xs">{hub.indexable ? "Indexável" : "Noindex"} · {hub.includeInSitemap ? "No sitemap" : "Fora do sitemap"}</p><p className="mt-2 text-xs text-muted-foreground"><strong>Última edição:</strong> {formatSiteEditDate(hub.updatedAt)}</p><div className="mt-4 flex gap-2"><Button type="button" size="sm" className="flex-1" onClick={() => setHubDraft({ ...hub })}><Pencil />Editar</Button><Button asChild type="button" variant="outline" size="icon-sm"><a href={hub.path} target="_blank" rel="noreferrer"><ExternalLink /></a></Button><Button type="button" variant="destructive" size="icon-sm" onClick={() => removeHub(hub)}><Trash2 /></Button></div></article>)}</div>{!hubSlice.length ? <p className="p-10 text-center text-sm text-muted-foreground">Nenhum hub encontrado.</p> : null}<PaginationControls page={safeHubPage} totalItems={filteredHubs.length} onPageChange={setHubPage} /></section>
      {hubDraft ? <form onSubmit={saveHub} className="min-w-0 space-y-4 rounded-xl border border-white/10 bg-card p-4 sm:p-5 lg:sticky lg:top-6 lg:h-fit"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{hubDraft.id === "new" ? "Novo hub" : "Editar hub"}</h2><p className="text-xs text-muted-foreground">Conteúdo, SEO e publicação.</p></div><Button type="button" size="icon-sm" variant="ghost" onClick={() => setHubDraft(null)}><X /></Button></div><label className={fieldClass}><span>Nome *</span><Input required value={hubDraft.name} onChange={(e) => { const name = e.target.value; const slug = hubDraft.id === "new" ? slugify(name) : hubDraft.slug; setHubDraft({ ...hubDraft, name, slug, path: `/ferramentas/${slug}` }); }} /></label><label className={fieldClass}><span>Slug *</span><Input required value={hubDraft.slug} onChange={(e) => { const slug = slugify(e.target.value); setHubDraft({ ...hubDraft, slug, path: `/ferramentas/${slug}` }); }} /><small className="break-all text-muted-foreground">URL: /ferramentas/{hubDraft.slug || "slug"}</small></label><label className={fieldClass}><span>Descrição</span><textarea className={textareaClass} value={hubDraft.description} onChange={(e) => setHubDraft({ ...hubDraft, description: e.target.value })} /></label><div className={fieldClass}><span>Conteúdo do hub</span><RichTextEditor value={hubDraft.contentHtml} onChange={(contentHtml) => setHubDraft((current) => current ? { ...current, contentHtml } : current)} /></div><label className={fieldClass}><span>Título SEO</span><Input value={hubDraft.seoTitle} onChange={(e) => setHubDraft({ ...hubDraft, seoTitle: e.target.value })} /></label><label className={fieldClass}><span>Descrição SEO</span><textarea className={textareaClass} value={hubDraft.seoDescription} onChange={(e) => setHubDraft({ ...hubDraft, seoDescription: e.target.value })} /></label><HubPublicationControls value={hubDraft} onChange={(change) => setHubDraft({ ...hubDraft, ...change })} /><Button type="submit" className="w-full"><Save />Salvar hub</Button></form> : <aside className="h-fit rounded-xl border border-dashed border-white/15 p-8 text-center text-sm text-muted-foreground">Selecione um hub para editar ou crie um novo.</aside>}
    </div> : null}
    {tab === "services" ? <section className="overflow-hidden rounded-xl border border-white/10 bg-card"><div className="grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-3">{serviceSlice.map((item) => <article key={item.id} className="flex min-w-0 flex-col rounded-lg border border-white/10 bg-background p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words text-sm font-semibold">{item.title}</h2><p className="mt-1 break-all text-xs text-muted-foreground">{item.path}</p></div><span className={`shrink-0 rounded-full border px-2 py-1 text-[10px] ${item.status === "published" ? "border-emerald-500/30 text-emerald-300" : "border-white/10 text-muted-foreground"}`}>{item.status === "published" ? "Publicado" : item.status === "draft" ? "Rascunho" : "Arquivado"}</span></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-muted-foreground">{item.shortDescription || "Sem resumo"}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-md bg-muted/15 p-2"><span className="block text-muted-foreground">Lista /servicos</span>{item.showInServicesIndex ? `Sim · ordem ${item.displayOrder}` : "Oculto"}</div><div className="rounded-md bg-muted/15 p-2"><span className="block text-muted-foreground">Google</span>{item.indexable ? "Indexável" : "Noindex"}</div></div><p className="mt-3 text-xs text-muted-foreground"><strong>Última edição:</strong> {formatSiteEditDate(item.updatedAt)}</p>{item.virtual ? <p className="mt-2 text-[10px] font-medium uppercase tracking-wide text-primary">Conteúdo atual do código</p> : null}<div className="mt-auto grid grid-cols-[1fr_auto] gap-2 pt-4"><Button asChild size="sm"><Link href={`/admin/site/servicos/${encodeURIComponent(item.id)}`}><Pencil />Editar em tela completa</Link></Button><Button asChild type="button" variant="outline" size="icon-sm"><a href={item.path} target="_blank" rel="noreferrer"><ExternalLink /></a></Button></div></article>)}</div>{!serviceSlice.length ? <p className="p-10 text-center text-sm text-muted-foreground">Nenhum serviço encontrado.</p> : null}<PaginationControls page={safeServicePage} totalItems={filteredServices.length} onPageChange={setServicePage} /></section> : null}
  </div>;
}
