export type PercentageMode = "percentageOfValue" | "whatPercentage" | "percentageIncrease" | "percentageDecrease" | "increaseValue" | "decreaseValue" | "originalBeforeIncrease" | "originalBeforeDiscount";
export type PercentageResult = { value: number; answer: string; formula: string; steps: string[] };

export const modes: Record<PercentageMode, { label: string; description: string; firstLabel: string; secondLabel: string; firstPlaceholder: string; secondPlaceholder: string; examples: [string, string][] }> = {
  percentageOfValue: { label: "Calcular porcentagem de um valor", description: "Descubra quanto é uma porcentagem de um valor.", firstLabel: "Porcentagem (%)", secondLabel: "Valor", firstPlaceholder: "Ex.: 20", secondPlaceholder: "Ex.: 350", examples: [["10", "200"], ["15", "500"], ["25", "1000"], ["8", "450"]] },
  whatPercentage: { label: "Descobrir a porcentagem", description: "Descubra quanto um valor representa de outro.", firstLabel: "Valor parcial", secondLabel: "Valor total", firstPlaceholder: "Ex.: 80", secondPlaceholder: "Ex.: 200", examples: [["80", "200"], ["45", "300"], ["25", "400"], ["180", "240"]] },
  percentageIncrease: { label: "Calcular aumento percentual", description: "Compare o valor inicial e o final.", firstLabel: "Valor inicial", secondLabel: "Valor final", firstPlaceholder: "Ex.: 100", secondPlaceholder: "Ex.: 150", examples: [["100", "150"], ["200", "250"], ["80", "100"], ["500", "625"]] },
  percentageDecrease: { label: "Calcular redução percentual", description: "Descubra a redução entre dois valores.", firstLabel: "Valor inicial", secondLabel: "Valor final", firstPlaceholder: "Ex.: 150", secondPlaceholder: "Ex.: 100", examples: [["150", "100"], ["200", "150"], ["80", "60"], ["500", "400"]] },
  increaseValue: { label: "Aumentar um valor", description: "Aplique um acréscimo percentual ao valor.", firstLabel: "Valor", secondLabel: "Aumento (%)", firstPlaceholder: "Ex.: 250", secondPlaceholder: "Ex.: 15", examples: [["250", "15"], ["100", "20"], ["500", "10"], ["80", "25"]] },
  decreaseValue: { label: "Diminuir um valor", description: "Aplique uma redução percentual ao valor.", firstLabel: "Valor", secondLabel: "Desconto (%)", firstPlaceholder: "Ex.: 250", secondPlaceholder: "Ex.: 15", examples: [["250", "15"], ["100", "20"], ["500", "10"], ["80", "25"]] },
  originalBeforeIncrease: { label: "Descobrir valor antes do aumento", description: "Encontre o valor original antes de um aumento.", firstLabel: "Valor final", secondLabel: "Aumento (%)", firstPlaceholder: "Ex.: 120", secondPlaceholder: "Ex.: 20", examples: [["120", "20"], ["150", "50"], ["220", "10"], ["375", "25"]] },
  originalBeforeDiscount: { label: "Descobrir valor antes do desconto", description: "Encontre o valor original antes de um desconto.", firstLabel: "Valor final", secondLabel: "Desconto (%)", firstPlaceholder: "Ex.: 80", secondPlaceholder: "Ex.: 20", examples: [["80", "20"], ["90", "10"], ["75", "25"], ["160", "20"]] },
};

export function parseNumber(input: string) { const normalized = input.trim().replace(/\s/g, "").replace(/\.(?=\d{3}(?:\D|$))/g, "").replace(",", "."); const value = Number(normalized); return normalized && Number.isFinite(value) ? value : null; }
export function format(value: number) { return new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 2 }).format(value); }
export function calculate(mode: PercentageMode, firstInput: string, secondInput: string): PercentageResult | { error: string } {
  const a = parseNumber(firstInput); const b = parseNumber(secondInput);
  if (a === null) return { error: "Informe um valor válido." }; if (b === null) return { error: "Informe uma porcentagem válida." };
  let value: number; let answer: string; let formula: string; let steps: string[];
  if (mode === "percentageOfValue") { value = a * b / 100; answer = `${format(a)}% de ${format(b)} é ${format(value)}.`; formula = "porcentagem ÷ 100 × valor"; steps = [`${format(a)} ÷ 100 = ${format(a / 100)}`, `${format(a / 100)} × ${format(b)} = ${format(value)}`]; }
  else if (mode === "whatPercentage") { if (b === 0) return { error: "O valor total deve ser maior que zero." }; value = a / b * 100; answer = `${format(a)} representa ${format(value)}% de ${format(b)}.`; formula = "valor parcial ÷ valor total × 100"; steps = [`${format(a)} ÷ ${format(b)} × 100 = ${format(value)}%`]; }
  else if (mode === "percentageIncrease" || mode === "percentageDecrease") { if (a === 0) return { error: "O valor inicial deve ser diferente de zero." }; value = (mode === "percentageIncrease" ? b - a : a - b) / a * 100; answer = mode === "percentageIncrease" ? `De ${format(a)} para ${format(b)} houve aumento de ${format(value)}%.` : `De ${format(a)} para ${format(b)} houve redução de ${format(value)}%.`; formula = mode === "percentageIncrease" ? "(valor final − valor inicial) ÷ valor inicial × 100" : "(valor inicial − valor final) ÷ valor inicial × 100"; steps = [`(${format(mode === "percentageIncrease" ? b : a)} − ${format(mode === "percentageIncrease" ? a : b)}) ÷ ${format(a)} × 100 = ${format(value)}%`]; }
  else if (mode === "increaseValue" || mode === "decreaseValue") { value = a * (1 + (mode === "increaseValue" ? b : -b) / 100); answer = mode === "increaseValue" ? `Ao aumentar ${format(a)} em ${format(b)}%, o novo valor é ${format(value)}.` : `Ao diminuir ${format(a)} em ${format(b)}%, o novo valor é ${format(value)}.`; formula = mode === "increaseValue" ? "valor × (1 + porcentagem ÷ 100)" : "valor × (1 − porcentagem ÷ 100)"; steps = [`${format(a)} × (1 ${mode === "increaseValue" ? "+" : "−"} ${format(b)} ÷ 100) = ${format(value)}`]; }
  else { if (mode === "originalBeforeDiscount" && b >= 100) return { error: "O desconto deve ser menor que 100%." }; value = a / (1 + (mode === "originalBeforeIncrease" ? b : -b) / 100); answer = `O valor original era ${format(value)}.`; formula = mode === "originalBeforeIncrease" ? "valor final ÷ (1 + aumento ÷ 100)" : "valor final ÷ (1 − desconto ÷ 100)"; steps = [`${format(a)} ÷ (1 ${mode === "originalBeforeIncrease" ? "+" : "−"} ${format(b)} ÷ 100) = ${format(value)}`]; }
  return { value, answer, formula, steps };
}
