-- Expand the Admin-managed "Entenda cada plano" copy on the Instagram analyzer.
-- Update only the three plan-detail fields; preserve all other editorial settings.
update public.site_contents
set custom_data = jsonb_set(jsonb_set(jsonb_set(custom_data, '{freePlanDetail}', '["Analise uma conta do Instagram por vez, com até 50 mil seguidores, usando a exportação oficial da Meta.","Veja quem não segue você de volta, quem você não segue e os seguidores mútuos.","O arquivo da análise gratuita é processado no navegador, sem envio ao Kivai para gerar o resultado.","Use gratuitamente calendário, briefing, QR Code, marca d’água e relatório Social Media; calendário, briefing e relatório mantêm rascunhos neste navegador.","Baixe os resultados das ferramentas sem contratar uma assinatura.","Não inclui histórico de análises do Instagram nem projetos salvos na conta para abrir em outro dispositivo."]'::jsonb), '{proPlanDetail}', '["Inclui as ferramentas e exportações gratuitas.","Acompanhe até 5 perfis do Instagram, com até 500 mil seguidores por perfil.","Guarde um histórico privado por perfil e compare as exportações da Meta para identificar novos seguidores e quem deixou de seguir.","Atualize o histórico importando novas exportações; a coleta do Instagram não acontece automaticamente.","Salve até 30 projetos no total, entre calendários, briefings, QR Codes, modelos de marca d’água e relatórios Social Media.","Abra os projetos em outro dispositivo com a mesma conta, duplique modelos e exporte projetos em JSON.","Os projetos do Pro são pessoais, sem organização por nome de cliente."]'::jsonb), '{agencyPlanDetail}', '["Inclui todos os recursos do Pro para uma operação com vários clientes.","Acompanhe até 20 perfis do Instagram, mantendo o histórico e as comparações separados por perfil.","Importe novas exportações da Meta para atualizar cada histórico; a coleta não é automática.","Salve até 200 projetos no total, entre calendários, briefings, QR Codes, modelos de marca d’água e relatórios Social Media.","Organize os projetos por até 20 nomes de clientes e filtre a biblioteca por cliente.","Abra, duplique e exporte os projetos em outro dispositivo usando a mesma conta.","A organização por cliente não inclui login de clientes, membros de equipe ou aprovação externa."]'::jsonb), updated_at = now()
where slug = 'instagram-follow-analyzer' and custom_data is not null;

update public.instagram_analyzer_plan_variants
set config = jsonb_set(jsonb_set(jsonb_set(config, '{freePlanDetail}', '["Analise uma conta do Instagram por vez, com até 50 mil seguidores, usando a exportação oficial da Meta.","Veja quem não segue você de volta, quem você não segue e os seguidores mútuos.","O arquivo da análise gratuita é processado no navegador, sem envio ao Kivai para gerar o resultado.","Use gratuitamente calendário, briefing, QR Code, marca d’água e relatório Social Media; calendário, briefing e relatório mantêm rascunhos neste navegador.","Baixe os resultados das ferramentas sem contratar uma assinatura.","Não inclui histórico de análises do Instagram nem projetos salvos na conta para abrir em outro dispositivo."]'::jsonb), '{proPlanDetail}', '["Inclui as ferramentas e exportações gratuitas.","Acompanhe até 5 perfis do Instagram, com até 500 mil seguidores por perfil.","Guarde um histórico privado por perfil e compare as exportações da Meta para identificar novos seguidores e quem deixou de seguir.","Atualize o histórico importando novas exportações; a coleta do Instagram não acontece automaticamente.","Salve até 30 projetos no total, entre calendários, briefings, QR Codes, modelos de marca d’água e relatórios Social Media.","Abra os projetos em outro dispositivo com a mesma conta, duplique modelos e exporte projetos em JSON.","Os projetos do Pro são pessoais, sem organização por nome de cliente."]'::jsonb), '{agencyPlanDetail}', '["Inclui todos os recursos do Pro para uma operação com vários clientes.","Acompanhe até 20 perfis do Instagram, mantendo o histórico e as comparações separados por perfil.","Importe novas exportações da Meta para atualizar cada histórico; a coleta não é automática.","Salve até 200 projetos no total, entre calendários, briefings, QR Codes, modelos de marca d’água e relatórios Social Media.","Organize os projetos por até 20 nomes de clientes e filtre a biblioteca por cliente.","Abra, duplique e exporte os projetos em outro dispositivo usando a mesma conta.","A organização por cliente não inclui login de clientes, membros de equipe ou aprovação externa."]'::jsonb), updated_at = now()
where plan_code in ('free','pro','agency') and config is not null;
