import type { Metadata } from "next";
import Link from "next/link";
import { DEFAULT_SOCIAL_IMAGE } from "@/lib/seo";
import PreviewClient from "./preview-client";

const url = "https://www.kivai.com.br/ferramentas/preview-de-post-redes-sociais";
const title = "Preview de Post para Redes Sociais Grátis | Kivai";
const description = "Visualize perfil, imagem, texto e legenda antes de publicar com o Preview de Post para Redes Sociais do Kivai.";
export const metadata: Metadata = { title: { absolute: title }, description, keywords: ["preview de post para redes sociais", "preview de post", "simulador de post", "visualizar post antes de publicar", "preview Instagram", "preview Facebook", "preview LinkedIn"], alternates: { canonical: url }, robots: { index: true, follow: true }, openGraph: { title, description, url, type: "website", siteName: "Kivai", locale: "pt_BR", images: [{ url: DEFAULT_SOCIAL_IMAGE, width: 1200, height: 630, alt: "Kivai" }] }, twitter: { card: "summary_large_image", title, description, images: [DEFAULT_SOCIAL_IMAGE] } };
const faq = [
  ["O que é um preview de post?", "É uma simulação visual que reúne perfil, imagem e legenda para ajudar na revisão de uma publicação antes de ela ser apresentada ou postada."],
  ["A ferramenta publica meu conteúdo?", "Não. O Kivai apenas monta a visualização no navegador e não publica, agenda ou envia conteúdo para redes sociais."],
  ["Preciso conectar meu Instagram ou outra conta?", "Não. A ferramenta não solicita acesso a contas e não utiliza credenciais de plataformas."],
  ["Preciso criar uma conta no Kivai?", "Não. O preview funciona sem login ou cadastro."],
  ["Posso usar uma imagem minha?", "Sim. Você pode selecionar arquivos JPG, PNG ou WebP de até 12 MB para o avatar e para a publicação."],
  ["A imagem é enviada para alguma rede social?", "Não. Nesta versão, as imagens são carregadas em uma URL temporária dentro do navegador e não são transmitidas ao Kivai nem às plataformas."],
  ["Quais plataformas possuem visualização?", "A ferramenta oferece composições próprias para Instagram, Facebook, LinkedIn, X e Threads."],
  ["O preview é exatamente igual ao aplicativo oficial?", "Não. É uma simulação para revisão. Interfaces, cortes e tipografia podem mudar conforme plataforma, dispositivo e atualizações."],
  ["Posso usar o preview para apresentar posts a clientes?", "Sim. Ele pode apoiar a conferência e a apresentação visual de uma proposta, deixando claro que se trata de uma simulação."],
  ["Posso copiar minha legenda?", "Sim. O botão Copiar legenda envia o texto atual para a área de transferência e mostra uma confirmação discreta."],
  ["Posso baixar o preview?", "Sim. O card pode ser exportado como PNG, sem incluir campos, navegação, anúncios ou botões da ferramenta."],
  ["O layout das redes sociais pode mudar?", "Sim. Por isso, recomenda-se conferir o conteúdo no aplicativo oficial antes da publicação definitiva."],
];
const schema = [{ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Preview de Post para Redes Sociais", applicationCategory: "MultimediaApplication", operatingSystem: "Navegador moderno", url, description, offers: { "@type": "Offer", price: "0", priceCurrency: "BRL" }, featureList: ["Preview multirrede", "Upload local de imagens", "Proporções de post", "Cópia de legenda", "Exportação PNG"] }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Início", item: "https://www.kivai.com.br" }, { "@type": "ListItem", position: 2, name: "Social Media", item: "https://www.kivai.com.br/ferramentas/social-media" }, { "@type": "ListItem", position: 3, name: "Preview de Post para Redes Sociais", item: url }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }];
export default function Page() { return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><PreviewClient /><section className="border-t border-border bg-muted/10 py-12"><div className="mx-auto max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8">
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">O que é um preview de post para redes sociais?</h2><p className="mt-4 leading-7 text-muted-foreground">Um preview de post combina os principais elementos de uma publicação em uma simulação visual: identificação do perfil, imagem, proporção e legenda. Ele permite observar a hierarquia do conteúdo, conferir quebras de linha e avaliar se texto e imagem formam um conjunto coerente antes de abrir a plataforma escolhida. A visualização não reproduz oficialmente nenhuma rede e pode diferir do resultado final.</p></article>
  <div className="grid gap-6 lg:grid-cols-2"><article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Por que revisar antes de publicar?</h2><p className="mt-4 leading-7 text-muted-foreground">A revisão antecipada ajuda a encontrar legendas incompletas, parágrafos difíceis de ler, imagens cortadas e informações de perfil incorretas. Também oferece uma referência concreta para conversas entre social media, designer, cliente e equipe de aprovação. O objetivo é melhorar a conferência, sem prometer alcance ou engajamento.</p></article><article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Preview não é publicação real</h2><p className="mt-4 leading-7 text-muted-foreground">O Kivai não publica, agenda, acessa contas ou coleta métricas. O card é uma composição própria para apoiar revisão e apresentação. Redes sociais podem alterar tipografia, espaçamento, proporções e outros elementos a qualquer momento, e cada dispositivo pode exibir o conteúdo de maneira diferente.</p></article></div>
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Como usar o Preview de Post para Redes Sociais</h2><ol className="mt-5 grid gap-3 text-sm text-muted-foreground sm:grid-cols-2"><li>1. Escolha a rede social desejada.</li><li>2. Informe nome e usuário do perfil.</li><li>3. Adicione uma foto de perfil, se desejar.</li><li>4. Selecione a imagem da publicação.</li><li>5. Escolha proporção e enquadramento.</li><li>6. Digite a legenda com suas quebras de linha.</li><li>7. Compare a composição no preview.</li><li>8. Revise texto, imagem e identificação.</li><li>9. Copie a legenda ou baixe o card em PNG.</li></ol></article>
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Cuidados ao adaptar conteúdo entre plataformas</h2><div className="mt-5 grid gap-5 text-sm leading-6 text-muted-foreground md:grid-cols-3"><p><strong className="block text-foreground">Imagem e proporção</strong>Uma imagem quadrada, vertical ou horizontal ocupa espaços diferentes. Use Preencher para cobrir o frame ou Ajustar para preservar toda a imagem.</p><p><strong className="block text-foreground">Texto e contexto</strong>Instagram, Facebook, LinkedIn, X e Threads favorecem comportamentos de leitura distintos. Revise abertura, tamanho e quebras de linha para cada uso.</p><p><strong className="block text-foreground">Aprovação transparente</strong>Ao apresentar o card a um cliente, informe que ele é uma simulação. A plataforma oficial pode aplicar cortes ou mudanças visuais.</p></div></article>
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Exemplos de uso</h2><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Social media", "Visualizar uma pauta antes de enviar para aprovação."], ["Agência", "Apresentar uma proposta de publicação ao cliente."], ["Empresa", "Conferir legenda, perfil e imagem antes da postagem."], ["Criador", "Comparar o mesmo conteúdo em diferentes redes."]].map(([name, text]) => <div key={name} className="border border-border p-4"><h3 className="font-semibold">{name}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>)}</div></article>
  <article className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Perguntas frequentes</h2><div className="mt-5 space-y-3">{faq.map(([question, answer]) => <details key={question} className="border border-border p-4"><summary className="cursor-pointer font-medium">{question}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{answer}</p></details>)}</div></article>
  <nav aria-label="Ferramentas relacionadas" className="border border-border bg-background p-5 sm:p-6"><h2 className="text-2xl font-semibold">Ferramentas relacionadas</h2><div className="mt-4 flex flex-wrap gap-3"><Related href="/ferramentas/planejador-de-conteudo-social-media">Planejador de Conteúdo</Related><Related href="/ferramentas/calendario-editorial-redes-sociais">Calendário Editorial</Related><Related href="/ferramentas/contador-de-caracteres-instagram">Contador de Caracteres</Related><Related href="/ferramentas/contador-de-hashtags-instagram">Contador de Hashtags</Related><Related href="/ferramentas/quebra-de-linha-instagram">Quebra de Linha para Instagram</Related></div></nav>
</div></section></>; }
function Related({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="border border-border px-4 py-2 text-sm font-medium transition-colors hover:border-primary hover:text-primary">{children}</Link>; }
