"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Bookmark, Copy, Download, Heart, ImagePlus, MessageCircle, MoreHorizontal, Repeat2, RotateCcw, Send, Share2, ThumbsUp, Trash2 } from "lucide-react";
import { ToolPageShell } from "@/components/tools/tool-page-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

const STORAGE_KEY = "kivai:preview-post-social:v1";
const platforms = ["Instagram", "Facebook", "LinkedIn", "X", "Threads"] as const;
const formats = { square: ["Quadrado", "1 / 1"], portrait: ["Retrato", "4 / 5"], landscape: ["Paisagem", "1.91 / 1"] } as const;
type Platform = typeof platforms[number]; type Format = keyof typeof formats; type Fit = "cover" | "contain";
type Settings = { platform: Platform; name: string; username: string; professional: string; caption: string; format: Format; fit: Fit; position: number };
const initial: Settings = { platform: "Instagram", name: "Nome do perfil", username: "usuario", professional: "Descrição profissional", caption: "Digite sua legenda para visualizar o post.", format: "square", fit: "cover", position: 50 };
const MAX_IMAGE_SIZE = 12 * 1024 * 1024;

export default function PreviewClient() {
  const [settings, setSettings] = useState<Settings>(initial); const [avatar, setAvatar] = useState(""); const [postImage, setPostImage] = useState("");
  const [avatarName, setAvatarName] = useState(""); const [imageName, setImageName] = useState(""); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [confirmClear, setConfirmClear] = useState(false); const [ready, setReady] = useState(false);
  const avatarInput = useRef<HTMLInputElement>(null); const imageInput = useRef<HTMLInputElement>(null); const previewRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    try {
      const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "null") as Partial<Settings> | null;
      if (stored && platforms.includes(stored.platform as Platform)) {
        // Restore browser-only preferences after hydration.
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setSettings({ ...initial, ...stored });
      }
    } catch { localStorage.removeItem(STORAGE_KEY); }
    setReady(true);
  }, []);
  useEffect(() => { if (ready) localStorage.setItem(STORAGE_KEY, JSON.stringify(settings)); }, [settings, ready]);
  function update<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings((current) => ({ ...current, [key]: value })); }
  function upload(event: ChangeEvent<HTMLInputElement>, kind: "avatar" | "post") { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setError("Use uma imagem JPG, PNG ou WebP."); return; } if (file.size > MAX_IMAGE_SIZE) { setError("A imagem deve ter no máximo 12 MB."); return; } const url = URL.createObjectURL(file); setError(""); if (kind === "avatar") { if (avatar) URL.revokeObjectURL(avatar); setAvatar(url); setAvatarName(file.name); } else { if (postImage) URL.revokeObjectURL(postImage); setPostImage(url); setImageName(file.name); } }
  function remove(kind: "avatar" | "post") { if (kind === "avatar") { if (avatar) URL.revokeObjectURL(avatar); setAvatar(""); setAvatarName(""); } else { if (postImage) URL.revokeObjectURL(postImage); setPostImage(""); setImageName(""); } }
  async function copyCaption() { try { await navigator.clipboard.writeText(settings.caption); setFeedback("Legenda copiada."); } catch { setFeedback("Não foi possível copiar a legenda."); } window.setTimeout(() => setFeedback(""), 2200); }
  async function downloadPreview() { if (!previewRef.current) return; setFeedback("Preparando imagem…"); try { const { toPng } = await import("html-to-image"); const dataUrl = await toPng(previewRef.current, { cacheBust: true, pixelRatio: 2, backgroundColor: "#ffffff", skipFonts: true }); const link = document.createElement("a"); link.download = `preview-${settings.platform.toLowerCase()}.png`; link.href = dataUrl; link.click(); setFeedback("Preview baixado em PNG."); } catch { setFeedback("Não foi possível gerar a imagem neste navegador."); } window.setTimeout(() => setFeedback(""), 2500); }
  function clearAll() { remove("avatar"); remove("post"); setSettings(initial); setError(""); setFeedback(""); setConfirmClear(false); localStorage.removeItem(STORAGE_KEY); }
  const hasChanges = avatar || postImage || JSON.stringify(settings) !== JSON.stringify(initial);
  return <ToolPageShell title="Preview de Post para Redes Sociais" description="Visualize perfil, imagem e legenda em uma simulação de publicação antes de apresentar ou postar seu conteúdo." categoryName="Social Media" categoryHref="/ferramentas/social-media" breadcrumbRootName="Início" breadcrumbRootHref="/" privacyMessage="As imagens são usadas somente no seu navegador para montar a visualização e não são enviadas ao Kivai.">
    <Card><CardHeader><CardTitle className="text-base">Escolha a plataforma</CardTitle><CardDescription>A troca atualiza a simulação imediatamente, sem recarregar a página.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2" role="group" aria-label="Plataforma do preview">{platforms.map((platform) => <Button key={platform} variant={settings.platform === platform ? "default" : "outline"} aria-pressed={settings.platform === platform} onClick={() => update("platform", platform)}>{platform}</Button>)}</div></CardContent></Card>
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,.8fr)_minmax(340px,1.2fr)]">
      <Card><CardHeader><CardTitle className="text-base">Configuração do post</CardTitle><CardDescription>Personalize os dados usados somente nesta visualização.</CardDescription></CardHeader><CardContent className="space-y-5">
        <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-medium sm:col-span-2">Perfil</legend><Field label="Nome do perfil"><input value={settings.name} onChange={(event) => update("name", event.target.value)} /></Field><Field label="Nome de usuário"><input value={settings.username} onChange={(event) => update("username", event.target.value.replace(/^@/, ""))} /></Field>{settings.platform === "LinkedIn" && <Field label="Descrição profissional" className="sm:col-span-2"><input value={settings.professional} onChange={(event) => update("professional", event.target.value)} placeholder="Especialista em Marketing Digital" /></Field>}<Upload label="Foto do perfil" name={avatarName} accept="image/jpeg,image/png,image/webp" inputRef={avatarInput} onChange={(event) => upload(event, "avatar")} onRemove={() => remove("avatar")} /></fieldset>
        <fieldset className="space-y-4 border-t border-border pt-5"><legend className="font-medium">Imagem da publicação</legend><Upload label="Imagem do post" name={imageName} accept="image/jpeg,image/png,image/webp" inputRef={imageInput} onChange={(event) => upload(event, "post")} onRemove={() => remove("post")} /><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium">Formato<select value={settings.format} onChange={(event) => update("format", event.target.value as Format)} className="min-h-10 border border-border bg-background px-3">{Object.entries(formats).map(([key, [label, ratio]]) => <option key={key} value={key}>{label} ({ratio.replace(" / ", ":")})</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Enquadramento<select value={settings.fit} onChange={(event) => update("fit", event.target.value as Fit)} className="min-h-10 border border-border bg-background px-3"><option value="cover">Preencher</option><option value="contain">Ajustar</option></select></label></div>{postImage && <label className="grid gap-1.5 text-sm font-medium">Posição horizontal: {settings.position}%<input type="range" min="0" max="100" value={settings.position} onChange={(event) => update("position", Number(event.target.value))} /></label>}</fieldset>
        <label className="grid gap-1.5 border-t border-border pt-5 text-sm font-medium">Legenda<textarea rows={8} value={settings.caption} onChange={(event) => update("caption", event.target.value)} className="min-w-0 border border-border bg-background p-3" placeholder="Digite sua legenda, hashtags e emojis" /><span className="text-right text-xs font-normal text-muted-foreground" aria-live="polite">{settings.caption.length} {settings.caption.length === 1 ? "caractere" : "caracteres"}</span></label><p className="text-xs leading-5 text-muted-foreground">Os limites e a apresentação podem mudar. Confira os requisitos no aplicativo oficial antes de publicar.</p>{error && <p role="alert" className="border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
        <div className="flex flex-wrap gap-2"><Button onClick={copyCaption} disabled={!settings.caption}><Copy />Copiar legenda</Button><Button variant="outline" onClick={() => hasChanges ? setConfirmClear(true) : clearAll()}><RotateCcw />Limpar preview</Button>{feedback && <p role="status" className="w-full text-sm text-primary">{feedback}</p>}</div>
      </CardContent></Card>
      <div className="space-y-4 lg:sticky lg:top-24"><div ref={previewRef} className="mx-auto w-full max-w-[620px]"><PostPreview settings={settings} avatar={avatar} postImage={postImage} /></div><p className="mx-auto max-w-[620px] text-xs leading-5 text-muted-foreground">Esta visualização é uma simulação. O layout final pode variar conforme atualizações da plataforma, dispositivo e formato da publicação.</p><Button className="w-full max-w-[620px]" onClick={downloadPreview}><Download />Baixar preview em PNG</Button></div>
    </div>
    {confirmClear && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/65 p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setConfirmClear(false); }}><div role="dialog" aria-modal="true" aria-labelledby="clear-preview-title" className="w-full max-w-md border border-border bg-background p-6"><h2 id="clear-preview-title" className="text-xl font-semibold">Limpar este preview?</h2><p className="mt-3 text-sm text-muted-foreground">Textos, preferências e imagens selecionadas serão removidos.</p><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => setConfirmClear(false)}>Cancelar</Button><Button variant="destructive" onClick={clearAll}>Limpar preview</Button></div></div></div>}
  </ToolPageShell>;
}

function Field({ label, className, children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={cn("grid gap-1.5 text-sm font-medium [&_input]:min-h-10 [&_input]:min-w-0 [&_input]:border [&_input]:border-border [&_input]:bg-background [&_input]:px-3", className)}>{label}{children}</label>; }
function Upload({ label, name, accept, inputRef, onChange, onRemove }: { label: string; name: string; accept: string; inputRef: React.RefObject<HTMLInputElement | null>; onChange: (event: ChangeEvent<HTMLInputElement>) => void; onRemove: () => void }) { return <div className="grid gap-1.5 text-sm font-medium sm:col-span-2"><span>{label}</span><input ref={inputRef} type="file" aria-label={label} accept={accept} className="sr-only" onChange={onChange} /><div className="flex flex-wrap items-center gap-2"><Button type="button" variant="outline" onClick={() => inputRef.current?.click()}><ImagePlus />{name ? "Trocar imagem" : "Escolher imagem"}</Button>{name && <><span className="max-w-full truncate text-xs font-normal text-muted-foreground">{name}</span><Button type="button" variant="destructive" size="sm" onClick={onRemove}><Trash2 />Remover</Button></>}</div></div>; }
function Avatar({ src, name }: { src: string; name: string }) {
  const initials = name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "K";
  // Blob URLs selected by the user are not compatible with Next image optimization.
  // eslint-disable-next-line @next/next/no-img-element
  return src ? <img src={src} alt="Foto de perfil selecionada" className="size-11 rounded-full object-cover" /> : <span role="img" aria-label="Avatar neutro" className="flex size-11 items-center justify-center rounded-full bg-primary/15 text-sm font-semibold text-primary">{initials}</span>;
}
function PostImage({ src, settings }: { src: string; settings: Settings }) {
  const ratio = formats[settings.format][1];
  return <div className="flex w-full items-center justify-center overflow-hidden bg-muted/50" style={{ aspectRatio: ratio }}>{src ? <>
    {/* Blob URLs selected by the user are intentionally rendered without optimization. */}
    {/* eslint-disable-next-line @next/next/no-img-element */}
    <img src={src} alt="Imagem selecionada para o post" className={cn("size-full", settings.fit === "cover" ? "object-cover" : "object-contain")} style={{ objectPosition: `${settings.position}% 50%` }} />
  </> : <div className="flex flex-col items-center gap-2 px-4 text-center text-muted-foreground"><ImagePlus className="size-9" /><span className="text-sm">Sua imagem aparecerá aqui</span></div>}</div>;
}
function PostPreview({ settings, avatar, postImage }: { settings: Settings; avatar: string; postImage: string }) { const username = settings.username || "usuario"; const caption = settings.caption || "Digite sua legenda para visualizar o post."; const header = <div className="flex items-center gap-3 p-4"><Avatar src={avatar} name={settings.name} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{settings.name || "Nome do perfil"}</p>{settings.platform === "LinkedIn" ? <p className="truncate text-xs text-neutral-500">{settings.professional || "Descrição profissional"}</p> : <p className="truncate text-xs text-neutral-500">@{username}</p>}</div><MoreHorizontal className="size-5" aria-hidden /></div>;
  if (settings.platform === "X" || settings.platform === "Threads") return <article aria-label={`Simulação de post no ${settings.platform}`} className="overflow-hidden border border-neutral-200 bg-white text-neutral-950 shadow-sm"><div className="flex gap-3 p-4"><Avatar src={avatar} name={settings.name} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-2"><strong className="text-sm">{settings.name || "Nome do perfil"}</strong><span className="text-xs text-neutral-500">@{username}</span></div><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6">{caption}</p>{postImage && <div className="mt-3 overflow-hidden rounded-xl border border-neutral-200"><PostImage src={postImage} settings={settings} /></div>}<div className="mt-4 flex justify-between text-neutral-500" aria-label="Ações ilustrativas"><MessageCircle className="size-4" /><Repeat2 className="size-4" /><Heart className="size-4" /><Share2 className="size-4" /></div></div></div></article>;
  if (settings.platform === "Facebook" || settings.platform === "LinkedIn") return <article aria-label={`Simulação de post no ${settings.platform}`} className="overflow-hidden border border-neutral-200 bg-white text-neutral-950 shadow-sm">{header}<p className="whitespace-pre-wrap break-words px-4 pb-4 text-sm leading-6">{caption}</p><PostImage src={postImage} settings={settings} /><div className="grid grid-cols-3 border-t border-neutral-200 p-2 text-xs text-neutral-600" aria-label="Ações ilustrativas"><span className="flex items-center justify-center gap-1.5 py-2"><ThumbsUp className="size-4" />Reagir</span><span className="flex items-center justify-center gap-1.5 py-2"><MessageCircle className="size-4" />Comentar</span><span className="flex items-center justify-center gap-1.5 py-2"><Share2 className="size-4" />Compartilhar</span></div></article>;
  return <article aria-label="Simulação de post no Instagram" className="overflow-hidden border border-neutral-200 bg-white text-neutral-950 shadow-sm">{header}<PostImage src={postImage} settings={settings} /><div className="flex items-center gap-4 px-4 py-3" aria-label="Ações ilustrativas"><Heart className="size-5" /><MessageCircle className="size-5" /><Send className="size-5" /><Bookmark className="ml-auto size-5" /></div><p className="whitespace-pre-wrap break-words px-4 pb-4 text-sm leading-6"><strong className="mr-2">{username}</strong>{caption}</p></article>;
}
