"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { BarChart3, Bell, Bookmark, Copy, Download, Globe2, Heart, Home, ImagePlus, MessageCircle, MoreHorizontal, Repeat2, RotateCcw, Search, Send, Share2, ThumbsUp, Trash2, UsersRound } from "lucide-react";
import { ToolPageShell } from "@/components/tools/tool-page-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

const STORAGE_KEY = "kivai:preview-post-social:v1";
const platforms = ["Instagram", "Facebook", "LinkedIn", "X", "Threads"] as const;
const formats = { square: ["Quadrado", "1 / 1"], portrait: ["Retrato", "4 / 5"], landscape: ["Paisagem", "1.91 / 1"] } as const;
type Platform = typeof platforms[number]; type Format = keyof typeof formats; type Fit = "cover" | "contain";
type Settings = { platform: Platform; name: string; username: string; professional: string; caption: string; format: Format; fit: Fit; position: number };
const initial: Settings = { platform: "Instagram", name: "Nome do perfil", username: "usuario", professional: "Descrição profissional", caption: "Digite sua legenda para visualizar o post.", format: "square", fit: "cover", position: 50 };
const MAX_IMAGE_SIZE = 12 * 1024 * 1024;

export default function PreviewClient() {
  const [settings, setSettings] = useState<Settings>(initial); const [avatar, setAvatar] = useState(""); const [postImage, setPostImage] = useState("");
  const [avatarName, setAvatarName] = useState(""); const [imageName, setImageName] = useState(""); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [confirmClear, setConfirmClear] = useState(false); const [ready, setReady] = useState(false);
  const avatarInput = useRef<HTMLInputElement>(null); const imageInput = useRef<HTMLInputElement>(null); const previewRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    try {
      const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "null") as Partial<Settings> | null;
      if (stored && platforms.includes(stored.platform as Platform)) {
        // Restore browser-only preferences after hydration.
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setSettings({ ...initial, ...stored });
      }
    } catch { localStorage.removeItem(STORAGE_KEY); }
    setReady(true);
  }, []);
  useEffect(() => { if (ready) localStorage.setItem(STORAGE_KEY, JSON.stringify(settings)); }, [settings, ready]);
  function update<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings((current) => ({ ...current, [key]: value })); }
  function upload(event: ChangeEvent<HTMLInputElement>, kind: "avatar" | "post") { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setError("Use uma imagem JPG, PNG ou WebP."); return; } if (file.size > MAX_IMAGE_SIZE) { setError("A imagem deve ter no máximo 12 MB."); return; } const url = URL.createObjectURL(file); setError(""); if (kind === "avatar") { if (avatar) URL.revokeObjectURL(avatar); setAvatar(url); setAvatarName(file.name); } else { if (postImage) URL.revokeObjectURL(postImage); setPostImage(url); setImageName(file.name); } }
  function remove(kind: "avatar" | "post") { if (kind === "avatar") { if (avatar) URL.revokeObjectURL(avatar); setAvatar(""); setAvatarName(""); } else { if (postImage) URL.revokeObjectURL(postImage); setPostImage(""); setImageName(""); } }
  async function copyCaption() { try { await navigator.clipboard.writeText(settings.caption); setFeedback("Legenda copiada."); } catch { setFeedback("Não foi possível copiar a legenda."); } window.setTimeout(() => setFeedback(""), 2200); }
  async function downloadPreview() { if (!previewRef.current) return; setFeedback("Preparando imagem…"); try { const { toPng } = await import("html-to-image"); const dataUrl = await toPng(previewRef.current, { cacheBust: true, pixelRatio: 2, backgroundColor: "#ffffff", skipFonts: true }); const link = document.createElement("a"); link.download = `preview-${settings.platform.toLowerCase()}.png`; link.href = dataUrl; link.click(); setFeedback("Preview baixado em PNG."); } catch { setFeedback("Não foi possível gerar a imagem neste navegador."); } window.setTimeout(() => setFeedback(""), 2500); }
  function clearAll() { remove("avatar"); remove("post"); setSettings(initial); setError(""); setFeedback(""); setConfirmClear(false); localStorage.removeItem(STORAGE_KEY); }
  const hasChanges = avatar || postImage || JSON.stringify(settings) !== JSON.stringify(initial);
  return <ToolPageShell title="Preview de Post para Redes Sociais" description="Visualize perfil, imagem e legenda em uma simulação de publicação antes de apresentar ou postar seu conteúdo." categoryName="Social Media" categoryHref="/ferramentas/social-media" breadcrumbRootName="Início" breadcrumbRootHref="/" privacyMessage="As imagens são usadas somente no seu navegador para montar a visualização e não são enviadas ao Kivai.">
    <Card><CardHeader><CardTitle className="text-base">Escolha a plataforma</CardTitle><CardDescription>A troca atualiza a simulação imediatamente, sem recarregar a página.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2" role="group" aria-label="Plataforma do preview">{platforms.map((platform) => <Button key={platform} variant={settings.platform === platform ? "default" : "outline"} aria-pressed={settings.platform === platform} onClick={() => update("platform", platform)}>{platform}</Button>)}</div></CardContent></Card>
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,.8fr)_minmax(340px,1.2fr)]">
      <Card><CardHeader><CardTitle className="text-base">Configuração do post</CardTitle><CardDescription>Personalize os dados usados somente nesta visualização.</CardDescription></CardHeader><CardContent className="space-y-5">
        <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-medium sm:col-span-2">Perfil</legend><Field label="Nome do perfil"><input value={settings.name} onChange={(event) => update("name", event.target.value)} /></Field><Field label="Nome de usuário"><input value={settings.username} onChange={(event) => update("username", event.target.value.replace(/^@/, ""))} /></Field>{settings.platform === "LinkedIn" && <Field label="Descrição profissional" className="sm:col-span-2"><input value={settings.professional} onChange={(event) => update("professional", event.target.value)} placeholder="Especialista em Marketing Digital" /></Field>}<Upload label="Foto do perfil" name={avatarName} accept="image/jpeg,image/png,image/webp" inputRef={avatarInput} onChange={(event) => upload(event, "avatar")} onRemove={() => remove("avatar")} /></fieldset>
        <fieldset className="space-y-4 border-t border-border pt-5"><legend className="font-medium">Imagem da publicação</legend><Upload label="Imagem do post" name={imageName} accept="image/jpeg,image/png,image/webp" inputRef={imageInput} onChange={(event) => upload(event, "post")} onRemove={() => remove("post")} /><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium">Formato<select value={settings.format} onChange={(event) => update("format", event.target.value as Format)} className="min-h-10 border border-border bg-background px-3">{Object.entries(formats).map(([key, [label, ratio]]) => <option key={key} value={key}>{label} ({ratio.replace(" / ", ":")})</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Enquadramento<select value={settings.fit} onChange={(event) => update("fit", event.target.value as Fit)} className="min-h-10 border border-border bg-background px-3"><option value="cover">Preencher</option><option value="contain">Ajustar</option></select></label></div>{postImage && <label className="grid gap-1.5 text-sm font-medium">Posição horizontal: {settings.position}%<input type="range" min="0" max="100" value={settings.position} onChange={(event) => update("position", Number(event.target.value))} /></label>}</fieldset>
        <label className="grid gap-1.5 border-t border-border pt-5 text-sm font-medium">Legenda<textarea rows={8} value={settings.caption} onChange={(event) => update("caption", event.target.value)} className="min-w-0 border border-border bg-background p-3" placeholder="Digite sua legenda, hashtags e emojis" /><span className="text-right text-xs font-normal text-muted-foreground" aria-live="polite">{settings.caption.length} {settings.caption.length === 1 ? "caractere" : "caracteres"}</span></label><p className="text-xs leading-5 text-muted-foreground">Os limites e a apresentação podem mudar. Confira os requisitos no aplicativo oficial antes de publicar.</p>{error && <p role="alert" className="border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
        <div className="flex flex-wrap gap-2"><Button onClick={copyCaption} disabled={!settings.caption}><Copy />Copiar legenda</Button><Button variant="outline" onClick={() => hasChanges ? setConfirmClear(true) : clearAll()}><RotateCcw />Limpar preview</Button>{feedback && <p role="status" className="w-full text-sm text-primary">{feedback}</p>}</div>
      </CardContent></Card>
      <div className="space-y-4 lg:sticky lg:top-24"><div ref={previewRef} className="mx-auto w-full max-w-[620px]"><PostPreview settings={settings} avatar={avatar} postImage={postImage} /></div><p className="mx-auto max-w-[620px] text-xs leading-5 text-muted-foreground">Esta visualização é uma simulação. O layout final pode variar conforme atualizações da plataforma, dispositivo e formato da publicação.</p><Button className="w-full max-w-[620px]" onClick={downloadPreview}><Download />Baixar preview em PNG</Button></div>
    </div>
    {confirmClear && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/65 p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setConfirmClear(false); }}><div role="dialog" aria-modal="true" aria-labelledby="clear-preview-title" className="w-full max-w-md border border-border bg-background p-6"><h2 id="clear-preview-title" className="text-xl font-semibold">Limpar este preview?</h2><p className="mt-3 text-sm text-muted-foreground">Textos, preferências e imagens selecionadas serão removidos.</p><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => setConfirmClear(false)}>Cancelar</Button><Button variant="destructive" onClick={clearAll}>Limpar preview</Button></div></div></div>}
  </ToolPageShell>;
}

function Field({ label, className, children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={cn("grid gap-1.5 text-sm font-medium [&_input]:min-h-10 [&_input]:min-w-0 [&_input]:border [&_input]:border-border [&_input]:bg-background [&_input]:px-3", className)}>{label}{children}</label>; }
function Upload({ label, name, accept, inputRef, onChange, onRemove }: { label: string; name: string; accept: string; inputRef: React.RefObject<HTMLInputElement | null>; onChange: (event: ChangeEvent<HTMLInputElement>) => void; onRemove: () => void }) { return <div className="grid gap-1.5 text-sm font-medium sm:col-span-2"><span>{label}</span><input ref={inputRef} type="file" aria-label={label} accept={accept} className="sr-only" onChange={onChange} /><div className="flex flex-wrap items-center gap-2"><Button type="button" variant="outline" onClick={() => inputRef.current?.click()}><ImagePlus />{name ? "Trocar imagem" : "Escolher imagem"}</Button>{name && <><span className="max-w-full truncate text-xs font-normal text-muted-foreground">{name}</span><Button type="button" variant="destructive" size="sm" onClick={onRemove}><Trash2 />Remover</Button></>}</div></div>; }
function Avatar({ src, name }: { src: string; name: string }) {
  const initials = name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "K";
  // Blob URLs selected by the user are not compatible with Next image optimization.
  // eslint-disable-next-line @next/next/no-img-element
  return src ? <img src={src} alt="Foto de perfil selecionada" className="size-11 rounded-full object-cover" /> : <span role="img" aria-label="Avatar neutro" className="flex size-11 items-center justify-center rounded-full bg-primary/15 text-sm font-semibold text-primary">{initials}</span>;
}
function PostImage({ src, settings }: { src: string; settings: Settings }) {
  const ratio = formats[settings.format][1];
  return <div className="flex w-full items-center justify-center overflow-hidden bg-neutral-100 text-neutral-500" style={{ aspectRatio: ratio }}>{src ? <>
    {/* Blob URLs selected by the user are intentionally rendered without optimization. */}
    {/* eslint-disable-next-line @next/next/no-img-element */}
    <img src={src} alt="Imagem selecionada para o post" className={cn("size-full", settings.fit === "cover" ? "object-cover" : "object-contain")} style={{ objectPosition: `${settings.position}% 50%` }} />
  </> : <div className="flex flex-col items-center gap-2 px-4 text-center"><ImagePlus className="size-9" /><span className="text-sm">Sua imagem aparecerá aqui</span></div>}</div>;
}
function PostPreview({ settings, avatar, postImage }: { settings: Settings; avatar: string; postImage: string }) {
  const username = settings.username || "usuario"; const name = settings.name || "Nome do perfil"; const caption = settings.caption || "Digite sua legenda para visualizar o post.";

  if (settings.platform === "Instagram") return <PlatformFrame platform="Instagram"><article aria-label="Simulação de post no Instagram" className="mx-auto max-w-[470px] overflow-hidden border-x border-b border-neutral-200 bg-white text-neutral-950 shadow-sm">
    <div className="flex items-center gap-3 px-3 py-2.5"><Avatar src={avatar} name={name} /><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold leading-4">{username}</p><p className="truncate text-[11px] leading-4 text-neutral-700">Publicação no feed</p></div><MoreHorizontal className="size-5" aria-hidden /></div>
    <PostImage src={postImage} settings={settings} />
    <div className="flex items-center gap-4 px-3 py-3" aria-label="Ações ilustrativas do Instagram"><Heart className="size-6" strokeWidth={1.8} /><MessageCircle className="size-6" strokeWidth={1.8} /><Repeat2 className="size-6" strokeWidth={1.8} /><Send className="size-6" strokeWidth={1.8} /><Bookmark className="ml-auto size-6" strokeWidth={1.8} /></div>
    <div className="px-3 pb-4 text-[13px] leading-5"><p className="font-semibold">Curtidas</p><p className="mt-1 whitespace-pre-wrap break-words"><strong className="mr-2">{username}</strong>{caption}</p><p className="mt-1 text-xs text-neutral-500">Ver comentários</p></div>
  </article></PlatformFrame>;

  if (settings.platform === "Facebook") return <PlatformFrame platform="Facebook"><article aria-label="Simulação de post no Facebook" className="mx-auto max-w-[560px] overflow-hidden rounded-lg border border-neutral-200 bg-white text-neutral-950 shadow-sm">
    <div className="flex items-center gap-3 px-4 pb-2 pt-3"><Avatar src={avatar} name={name} /><div className="min-w-0 flex-1"><p className="truncate text-[15px] font-semibold">{name}</p><p className="flex items-center gap-1 text-xs text-neutral-500">Agora · <Globe2 className="size-3" aria-label="Público" /></p></div><MoreHorizontal className="size-6 text-neutral-600" aria-hidden /></div>
    <p className="whitespace-pre-wrap break-words px-4 pb-3 text-[15px] leading-5">{caption}</p><PostImage src={postImage} settings={settings} />
    <div className="flex items-center justify-between border-b border-neutral-200 px-4 py-2 text-xs text-neutral-500"><span className="flex items-center gap-1"><span className="flex size-5 items-center justify-center rounded-full bg-[#1877f2] text-white"><ThumbsUp className="size-3 fill-current" /></span>Reações</span><span>Comentários · Compartilhamentos</span></div>
    <div className="grid grid-cols-3 px-2 py-1 text-sm font-medium text-neutral-600" aria-label="Ações ilustrativas do Facebook"><PreviewAction icon={<ThumbsUp />} label="Curtir" /><PreviewAction icon={<MessageCircle />} label="Comentar" /><PreviewAction icon={<Share2 />} label="Compartilhar" /></div>
  </article></PlatformFrame>;

  if (settings.platform === "LinkedIn") return <PlatformFrame platform="LinkedIn"><article aria-label="Simulação de post no LinkedIn" className="mx-auto max-w-[552px] overflow-hidden rounded-lg border border-[#d6d6d6] bg-white text-neutral-950 shadow-sm">
    <div className="flex items-start gap-3 px-4 pb-2 pt-3"><Avatar src={avatar} name={name} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold leading-5">{name}</p><p className="truncate text-xs text-neutral-500">{settings.professional || "Descrição profissional"}</p><p className="flex items-center gap-1 text-xs text-neutral-500">Agora · <Globe2 className="size-3" aria-label="Público" /></p></div><MoreHorizontal className="size-5" aria-hidden /></div>
    <p className="whitespace-pre-wrap break-words px-4 pb-3 text-sm leading-5">{caption}</p><PostImage src={postImage} settings={settings} />
    <div className="flex items-center justify-between border-b border-neutral-200 px-4 py-2 text-xs text-neutral-500"><span className="flex items-center gap-1"><span className="flex size-4 items-center justify-center rounded-full bg-[#0a66c2] text-white"><ThumbsUp className="size-2.5 fill-current" /></span>Reações</span><span>Comentários · Republicações</span></div>
    <div className="grid grid-cols-4 px-1 py-1 text-[10px] font-semibold text-neutral-600 sm:text-xs" aria-label="Ações ilustrativas do LinkedIn"><PreviewAction icon={<ThumbsUp />} label="Gostei" /><PreviewAction icon={<MessageCircle />} label="Comentar" /><PreviewAction icon={<Repeat2 />} label="Republicar" /><PreviewAction icon={<Send />} label="Enviar" /></div>
  </article></PlatformFrame>;

  if (settings.platform === "X") return <PlatformFrame platform="X"><article aria-label="Simulação de post no X" className="mx-auto max-w-[600px] border-b border-neutral-200 bg-white px-4 py-3 text-neutral-950">
    <div className="flex gap-3"><Avatar src={avatar} name={name} /><div className="min-w-0 flex-1"><div className="flex min-w-0 items-center gap-1 text-[15px]"><strong className="truncate">{name}</strong><span className="truncate text-neutral-500">@{username} · agora</span><MoreHorizontal className="ml-auto size-5 shrink-0 text-neutral-500" aria-hidden /></div><p className="mt-0.5 whitespace-pre-wrap break-words text-[15px] leading-5">{caption}</p><div className="mt-3 overflow-hidden rounded-2xl border border-neutral-200"><PostImage src={postImage} settings={settings} /></div><div className="mt-3 flex items-center justify-between text-neutral-500" aria-label="Ações ilustrativas do X"><MessageCircle className="size-[18px]" /><Repeat2 className="size-[18px]" /><Heart className="size-[18px]" /><BarChart3 className="size-[18px]" /><Bookmark className="size-[18px]" /><Share2 className="size-[18px]" /></div></div></div>
  </article></PlatformFrame>;

  return <PlatformFrame platform="Threads"><article aria-label="Simulação de post no Threads" className="mx-auto max-w-[620px] bg-white px-4 py-4 text-neutral-950">
    <div className="grid grid-cols-[44px_minmax(0,1fr)] gap-3"><div className="flex flex-col items-center"><Avatar src={avatar} name={name} /><span className="mt-2 w-0.5 flex-1 bg-neutral-200" aria-hidden /><span className="mt-2 flex -space-x-1" aria-hidden><span className="size-2 rounded-full bg-neutral-300" /><span className="size-2 rounded-full bg-neutral-400" /></span></div><div className="min-w-0"><div className="flex items-center gap-2"><strong className="truncate text-[15px]">{username}</strong><span className="ml-auto text-sm text-neutral-500">agora</span><MoreHorizontal className="size-5 text-neutral-500" aria-hidden /></div><p className="mt-1 whitespace-pre-wrap break-words text-[15px] leading-5">{caption}</p><div className="mt-3 overflow-hidden rounded-xl border border-neutral-200"><PostImage src={postImage} settings={settings} /></div><div className="mt-3 flex items-center gap-4" aria-label="Ações ilustrativas do Threads"><Heart className="size-5" /><MessageCircle className="size-5" /><Repeat2 className="size-5" /><Send className="size-5" /></div><p className="mt-3 text-sm text-neutral-500">Ver atividade · Respostas e curtidas</p></div></div>
  </article></PlatformFrame>;
}

function PreviewAction({ icon, label }: { icon: React.ReactElement<{ className?: string }>; label: string }) { return <span className="flex min-w-0 items-center justify-center gap-1 py-2.5 [&_svg]:size-4 sm:[&_svg]:size-[18px]"><span aria-hidden>{icon}</span><span className="truncate">{label}</span></span>; }

function PlatformFrame({ platform, children }: { platform: Platform; children: React.ReactNode }) {
  if (platform === "Instagram") return <div className="mx-auto max-w-[470px] overflow-hidden rounded-lg border border-neutral-200 bg-white shadow-sm"><div className="flex h-12 items-center border-b border-neutral-200 px-3 text-neutral-950"><span className="font-serif text-xl font-semibold italic tracking-tight">Instagram</span><div className="ml-auto flex items-center gap-4"><Home className="size-5" aria-hidden /><Send className="size-5" aria-hidden /></div></div>{children}</div>;
  if (platform === "Facebook") return <div className="mx-auto max-w-[600px] overflow-hidden rounded-lg border border-neutral-200 bg-[#f0f2f5] shadow-sm"><div className="flex h-13 items-center gap-3 border-b border-neutral-200 bg-white px-3 text-neutral-950"><span className="flex size-8 items-center justify-center rounded-full bg-[#0866ff] text-xl font-bold text-white">f</span><span className="flex h-8 min-w-0 flex-1 items-center gap-2 rounded-full bg-[#f0f2f5] px-3 text-xs text-neutral-500"><Search className="size-4" aria-hidden />Pesquisar no Facebook</span><Bell className="size-5 text-neutral-600" aria-hidden /></div><div className="p-3">{children}</div></div>;
  if (platform === "LinkedIn") return <div className="mx-auto max-w-[600px] overflow-hidden rounded-md border border-neutral-200 bg-[#f3f2ef] shadow-sm"><div className="flex min-h-14 items-center gap-3 border-b border-neutral-200 bg-white px-3 text-neutral-950"><span className="flex size-8 items-center justify-center rounded-sm bg-[#0a66c2] text-lg font-bold text-white">in</span><span className="hidden h-8 min-w-0 flex-1 items-center gap-2 rounded bg-[#edf3f8] px-3 text-xs text-neutral-600 sm:flex"><Search className="size-4" aria-hidden />Pesquisar</span><span className="ml-auto flex items-center gap-4 text-[10px] text-neutral-600"><span className="flex flex-col items-center"><Home className="size-5" />Início</span><span className="flex flex-col items-center"><UsersRound className="size-5" />Minha rede</span><span className="flex flex-col items-center"><Bell className="size-5" />Notificações</span></span></div><div className="p-3">{children}</div></div>;
  if (platform === "X") return <div className="mx-auto max-w-[600px] overflow-hidden border-x border-neutral-200 bg-white text-neutral-950 shadow-sm"><div className="flex h-12 items-center border-b border-neutral-200 px-4"><span className="text-xl font-semibold">𝕏</span><span className="mx-auto font-semibold">Página inicial</span><Search className="size-5" aria-hidden /></div><div className="grid h-12 grid-cols-2 border-b border-neutral-200 text-sm font-medium"><span className="flex items-center justify-center border-b-2 border-[#1d9bf0]">Para você</span><span className="flex items-center justify-center text-neutral-500">Seguindo</span></div>{children}</div>;
  return <div className="mx-auto max-w-[620px] overflow-hidden rounded-lg border border-neutral-200 bg-white text-neutral-950 shadow-sm"><div className="grid h-13 grid-cols-[1fr_auto_1fr] items-center border-b border-neutral-200 px-4"><span className="text-xl font-semibold">@</span><span className="font-semibold">Para você</span><MoreHorizontal className="ml-auto size-5" aria-hidden /></div>{children}</div>;
}
