import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Sparkles } from "lucide-react";
import type { SiteService } from "@/lib/site-cms/types";

export function PublicServicePage({ service }: { service: SiteService }) {
  const visible = (key: string) => service.blockVisibility?.[key] !== false;
  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    {visible("hero") ? <section className="relative overflow-hidden border-b border-white/5"><div aria-hidden="true" className="absolute left-1/2 top-0 -z-10 h-[520px] w-[900px] -translate-x-1/2 rounded-full bg-primary/15 blur-[150px]" /><div className="mx-auto max-w-6xl px-4 pb-16 pt-20 sm:px-6 lg:px-8"><Link href="/servicos" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Voltar para Serviços</Link><div className="mx-auto mt-14 max-w-4xl text-center">{service.badge ? <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1.5 text-sm font-medium text-primary"><Sparkles className="size-4" />{service.badge}</div> : null}<h1 className="mt-6 text-4xl font-semibold tracking-tight sm:text-5xl lg:text-6xl">{service.title}</h1>{visible("summary") && service.shortDescription ? <p className="mx-auto mt-6 max-w-3xl text-base leading-8 text-muted-foreground sm:text-lg">{service.shortDescription}</p> : null}{visible("audience") && service.audience ? <p className="mt-4 text-sm text-muted-foreground"><strong>Indicado para:</strong> {service.audience}</p> : null}{visible("cta") ? <a href={service.ctaUrl || "/contato"} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-3.5 text-sm font-semibold text-primary-foreground">{service.ctaLabel || "Solicitar orçamento"}<ArrowRight className="size-4" /></a> : null}</div></div></section> : <div className="mx-auto max-w-6xl px-4 pt-24 sm:px-6 lg:px-8"><Link href="/servicos" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Voltar para Serviços</Link></div>}
    {visible("cover") && service.coverImageUrl ? <div className="mx-auto mt-10 max-w-5xl px-4"><div className="relative aspect-[16/7] overflow-hidden rounded-3xl border border-white/10"><Image src={service.coverImageUrl} alt="" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 1024px" /></div></div> : null}
    {visible("content") && service.contentHtml ? <article className="prose prose-invert mx-auto max-w-4xl px-4 py-16 prose-headings:tracking-tight prose-p:leading-8 prose-a:text-primary sm:px-6" dangerouslySetInnerHTML={{ __html: service.contentHtml }} /> : null}
  </main>;
}
